# everyday
alias -g 2.="../.."
alias -g 3.="../../.."
alias -g 4.="../../../.."
alias -g 5.="../../../../.."

alias v="nvim"
alias cp="cp -r"
alias rm="rm -r"
alias md="mkdir -p"
alias mf="install -Dm644 /dev/null"
alias ls="eza --icons --group-directories-first"
alias l="eza --icons --group-directories-first -1"
alias lsa="eza --icons --group-directories-first -a"
alias la="eza --icons --group-directories-first -1a"
alias ll="eza --icons --group-directories-first -l"
alias L="eza --icons --group-directories-first -la"
alias l.="eza --icons --group-directories-first -d .*"
alias t="tmux has && tmux a || tmux"
alias w="witr"
alias wp="witr --port"
alias wi="witr --pid"
alias px="ps aux | rg"
alias bc="bc -l"
alias b="bat"
alias -g BH="--help | bat -plain --language help"

alias p="podman"
alias pu="podman compose up"
alias pd="podman compose down"
alias pg="podman start"
alias ph="podman stop"
alias pr="podman compose restart"
alias prs="podman restart"
alias ps="podman ps"
alias psa="podman ps -a"
alias pl="podman logs --since 1m"
alias plg="podman logs"

alias se="sudo systemctl enable"
alias sd="sudo systemctl disable"
alias sg="sudo systemctl start"
alias sh="sudo systemctl stop"
alias ss="sudo systemctl status"
alias sr="sudo systemctl restart"
alias sE="sudo systemctl edit --full"
alias sue="systemctl --user enable"
alias sud="systemctl --user disable"
alias sug="systemctl --user start"
alias suh="systemctl --user stop"
alias sus="systemctl --user status"
alias sur="systemctl --user restart"
alias suE="systemctl --user edit --full"

alias sx="${BROWSER:-firefox} --search"

alias lg="lazygit"
alias ld="lazydocker"
alias lh="lazyssh"
alias lm="vi-mongo"

# XDG_* environment variables
alias gpg="gpg --homedir '$XDG_DATA_HOME/gnupg'"
alias gpg2='gpg2 --homedir "$XDG_DATA_HOME/gnupg"'
alias nvidia-settings="nvidia-settings --config='$XDG_CONFIG_HOME/nvidia/nvidia-settings.conf'"
alias wget="wget --hsts-file='$XDG_DATA_HOME/wget-hst' "
alias xbindkeys="xbindkeys -f '$XDG_CONFIG_HOME/xbindkeys/config'"
