# everyday
alias -g ...="../.."
alias -g ....="../../.."
alias -g .....="../../../.."
alias -g ......="../../../../.."

alias v="nvim"
alias cp="cp -r"
alias rm="rm -r"
alias md="mkdir -p"
alias mf="install -D /dev/null"
alias ls="eza --icons --group-directories-first"
alias l="eza --icons --group-directories-first -1"
alias lsa="eza --icons --group-directories-first -a"
alias la="eza --icons --group-directories-first -1a"
alias ll="eza --icons --group-directories-first -l"
alias L="eza --icons --group-directories-first -la"
alias l.="eza --icons --group-directories-first -d .*"
alias t="tmux a || tmux"
alias w="witr"
alias ser="sudo systemctl"
alias seru="systemctl --user"
alias px="ps aux | rg"
alias b="bat"
alias -g BH="--help | bat -plain --language help"

alias p="podman"
alias pu="podman compose up -d"
alias pd="podman compose down"
alias ps="podman ps"
alias psa="podman ps -a"
alias pst="podman start"
alias psp="podman stop"
alias pr="podman compose restart"
alias prs="podman restart"
alias pl="podman logs --since 1m"
alias plg="podman logs"

# XDG_* environment variables
alias gpg="gpg --homedir '$XDG_DATA_HOME/gnupg'"
alias gpg2='gpg2 --homedir "$XDG_DATA_HOME/gnupg"'
alias nvidia-settings="nvidia-settings --config='$XDG_CONFIG_HOME/nvidia/nvidia-settings.conf'"
alias wget="wget --hsts-file='$XDG_DATA_HOME/wget-hst' "
alias xbindkeys="xbindkeys -f '$XDG_CONFIG_HOME/xbindkeys/config'"
