# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "catppuccin_macchiato"
format = """$directory$line_break $character"""
right_format = """$all"""
command_timeout = 1000

# Starship modules
[character]

success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = "[❮](subtext1)"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold mauve"
# ignore_branches = ['master', 'main']

[directory]
fish_style_pwd_dir_length = 3
truncation_symbol = '…/'
truncation_length = 1

[direnv]
disabled = false

[lua]
disabled = true

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
disabled = true
