#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &

# bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor DP1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a mplayer2 state=floating
