# 3proxy
# Autogenerated from man page /usr/share/man/man8/3proxy.8.gz
complete -c 3proxy -l install --description '(Windows NT family only) install   3proxy as a system service.'
complete -c 3proxy -l remove --description '(Windows NT family only) remove 3proxy from system services SIGNALS Under Uni…'

