# aespipe
# Autogenerated from man page /usr/share/man/man1/aespipe.1.gz
complete -c aespipe -s A --description 'Read passphrase of gpg encrypted key file from gpg-agent instead of the termi…'
complete -c aespipe -s C --description 'Runs hashed passphrase through itercountk thousand iterations of AES-256 befo…'
complete -c aespipe -s d --description 'Decrypt data.'
complete -c aespipe -s e --description 'Following encryption types are recognized: AES128 (default), AES192 and AES25…'
complete -c aespipe -s G --description 'Set gpg home directory to gpghome, so that gpg uses public/private keys on gp…'
complete -c aespipe -s H --description 'Uses phash function to hash passphrase.'
complete -c aespipe -s K --description 'Passphrase is piped to gpg so that gpg can decrypt file gpgkey which contains…'
complete -c aespipe -s O --description 'Set IV offset in 512 byte units.  Default is zero.'
complete -c aespipe -s p --description 'Read the passphrase from file descriptor fdnumber instead of the terminal.'
complete -c aespipe -s P --description 'Read the passphrase from file cleartextkey instead of the terminal.'
complete -c aespipe -s q --description 'Be quiet and don\'t complain about write errors.'
complete -c aespipe -s S --description 'Sets encryption passphrase seed pseed which is appended to user supplied pass…'
complete -c aespipe -s T --description 'Asks passphrase twice instead of just once.'
complete -c aespipe -s v --description 'Verbose mode.'
complete -c aespipe -s w --description 'Wait number seconds before asking passphrase.'

