# affcompare
# Autogenerated from man page /usr/share/man/man1/affcompare.1.gz
complete -c affcompare -s e --description 'Just report about existence (use with -r).'
complete -c affcompare -s p --description 'Report about the results of preening.'
complete -c affcompare -s r --description 'dir1 dir2  Recursively compare what\'s in dir1 with dir2, and report what\'s in…'
complete -c affcompare -s s --description 'Check to see if named files are on Amazon S3. RE . PP Other options: . RS.'
complete -c affcompare -s a --description 'Print what\'s the same (all).'
complete -c affcompare -s b --description 'Print the numbers of differing sectors.'
complete -c affcompare -s c --description 'Print the contents of differing sectors.'
complete -c affcompare -s h --description 'Show help page.'
complete -c affcompare -s m --description 'Just report about the data (ignore metadata).'
complete -c affcompare -s P --description 'Just examine the differences on page \'n\'.'
complete -c affcompare -s q --description 'Quiet.  No output except for errors.'
complete -c affcompare -s V --description 'Just print the version number and exit.'
complete -c affcompare -s v --description 'Verbose.  Show each file as it is compared.'

