# affconvert
# Autogenerated from man page /usr/share/man/man1/affconvert.1.gz
complete -c affconvert -s q --description 'Quiet mode.  Don\'t ask questions, don\'t print status.'
complete -c affconvert -s V --description 'Just print the version number and exit. RE . PP AFF output options: . RS.'
complete -c affconvert -o 'a<ext>' --description 'Use \'ext\' for aff files (default is aff; afd for AFD files).'
complete -c affconvert -s L --description 'Use the LZMA compression algorithm (better but slower).'
complete -c affconvert -o Mn --description 'Set maximum size of output file.  Suffix with k, m or g.  Use with -o.'
complete -c affconvert -o 'O<dir>' --description 'Use \'dir\' as the output directory.  Example: -Otest.'
complete -c affconvert -o 'o<dir>.afd' --description 'Output to \'dir\'. afd (can only convert one at a time).'
complete -c affconvert -o 's<n>' --description 'Set the image_pagesize as \'n\' (default 16777216).'
complete -c affconvert -s x --description 'Don\'t compress the AFF file.'
complete -c affconvert -o 'X<n>' --description 'Set compression to \'n\'; default is 7. RE . PP Raw output options: . RS.'
complete -c affconvert -o 'e<ext>' --description 'Use \'ext\' for the raw files (default is raw).  Implies in -r.'
complete -c affconvert -s r --description 'Generate raw output. RE . PP Dangerous input options: . RS.'
complete -c affconvert -s y --description 'Always answer yes/no questions \'yes. \'.'
complete -c affconvert -s Z --description 'Do not automatically probe for gzip/bzip2 compression.'
complete -c affconvert -s z --description 'ZAP (delete) the output file if it already exists.  EXAMPLES Convert file1.'

