# affdiskprint
# Autogenerated from man page /usr/share/man/man1/affdiskprint.1.gz
complete -c affdiskprint -s x --description 'Verify the diskprint.'
complete -c affdiskprint -s V --description 'Just print the version number and exit.'
complete -c affdiskprint -s h --description 'Print this help.'

