# affsign
# Autogenerated from man page /usr/share/man/man1/affsign.1.gz
complete -c affsign -s n --description 'Ask for a chain-of-custody note.'
complete -c affsign -s v --description 'Just print the version number and exit. RE . PP Signature Options: . RS.'
complete -c affsign -s k --description 'Specify private key for signing.'
complete -c affsign -s c --description 'Specify a X.'
complete -c affsign -s Z --description 'ZAP (remove) all signature segments.'

