# affsegment
# Autogenerated from man page /usr/share/man/man1/affsegment.1.gz
complete -c affsegment -s c --description 'Create AFF files if they do not exist.'
complete -c affsegment -o ssegval --description 'Sets the value of a segment; may be repeated.'
complete -c affsegment -o psegname --description 'Prints the contents of the segment name for each file.'
complete -c affsegment -s V --description 'Just print the version number and exit.'
complete -c affsegment -o dname --description 'Delete segment \'name\'.'
complete -c affsegment -s h -s '?' --description 'Print this message.'
complete -c affsegment -s Q --description 'interpert 8-byte segments as a 64-bit value.'
complete -c affsegment -s A --description 'Print the 32-bit arg, not the segment value.'
complete -c affsegment -s x --description 'Print the segment as a hex string. RE . PP Setting the segment values: . RS.'
complete -c affsegment -o sname --description 'Take the new value of segment \'name\' from stdin.'
complete -c affsegment -o sname/arg --description 'Sets segment \'name\' arg to be \'arg\' (may be repeated). RE .'

