# affstats
# Autogenerated from man page /usr/share/man/man1/affstats.1.gz
complete -c affstats -s m --description 'Print all output in megabytes.'
complete -c affstats -s V --description 'Just print the version number and exit.'

