# affuse
# Autogenerated from man page /usr/share/man/man1/affuse.1.gz
complete -c affuse -s d -s o --description 'Enable debug output (implies in -f).'
complete -c affuse -s f --description 'Foreground operation.'
complete -c affuse -s s --description 'Disable multi-threaded operation.'

