# affverify
# Autogenerated from man page /usr/share/man/man1/affverify.1.gz
complete -c affverify -s a --description 'Print all segments.'
complete -c affverify -s V --description 'Just print the version number and exit.'
complete -c affverify -s v --description 'Verbose.'

