# affxml
# Autogenerated from man page /usr/share/man/man1/affxml.1.gz
complete -c affxml -s j --description 'Just print information about segname (may be repeated).'
complete -c affxml -s s --description 'Output \'stats\' for the file data (may a long time).'
complete -c affxml -s V --description 'Just print the version number and exit.'
complete -c affxml -s x --description 'Don\'t include the infile filename in output.'

