# airgraph-ng
# Autogenerated from man page /usr/share/man/man1/airgraph-ng.1.gz
complete -c airgraph-ng -s h --description 'Shows the help screen.'
complete -c airgraph-ng -s i --description 'Airodump-ng CSV file.'
complete -c airgraph-ng -s o --description 'Output png file.'
complete -c airgraph-ng -s g --description 'Choose the Graph Type.'
complete -c airgraph-ng -s a --description 'Print the about.'

