# alacritty
# Autogenerated from man page /usr/share/man/man1/alacritty.1.gz
complete -c alacritty -l class --description 'Defines the window class hint on Linux [default: Alacritty,Alacritty]  On Way…'
complete -c alacritty -s e -l command --description 'Command and args to execute (must be last argument).'
complete -c alacritty -l config-file --description 'Specify alternative configuration file  Alacritty looks for the configuration…'
complete -c alacritty -s d -l dimensions --description 'Defines the window dimensions.'
complete -c alacritty -l embed --description 'Defines the X11 window ID (as a decimal integer) to embed Alacritty within.'
complete -c alacritty -s o -l option --description 'Override configuration file options [example: cursor. style=Beam].'
complete -c alacritty -l position --description 'Defines the window position.'
complete -c alacritty -s t -l title --description 'Defines the window title [default: Alacritty].'

