# alfred-gpsd
# Autogenerated from man page /usr/share/man/man8/alfred-gpsd.8.gz
complete -c alfred-gpsd -s v -l version --description 'Print the version.'
complete -c alfred-gpsd -s h -l help --description 'Display a brief help message.'
complete -c alfred-gpsd -s u -l unix-path --description 'path to unix socket used for alfred server communication.'
complete -c alfred-gpsd -s s -l server --description 'Start up in server mode.'
complete -c alfred-gpsd -s l -l location --description 'Rather than read the current location from gpsd, use a fixed location.'
complete -c alfred-gpsd -s g -l gpsd --description 'Specify the server hostname and optional port of where gpsd is listening.'

