# alfred
# Autogenerated from man page /usr/share/man/man8/alfred.8.gz
complete -c alfred -s v -l version --description 'Print the version.'
complete -c alfred -s h -l help --description 'Display a brief help message.'
complete -c alfred -s u -l unix-path --description 'path to unix socket used for client-server communication.'
complete -c alfred -s s -l set-data --description 'Sets new data to distribute from stdin for the supplied data type (0-255).'
complete -c alfred -s r -l request --description 'Collect data from the network and prints it on the network.'
complete -c alfred -s d -l verbose --description 'Show extra information in the data output.'
complete -c alfred -s V -l req-version --description 'Specify the data version set for -s.'
complete -c alfred -s M -l modeswitch --description '.'
complete -c alfred -s I -l change-interface --description 'Change the alfred server to use the new interface(s).'
complete -c alfred -s i -l interface --description 'Specify the interface (or comma separated list of interfaces) to listen on.'
complete -c alfred -s b --description 'Specify the batman-adv interface configured on the system (default: bat0).'
complete -c alfred -s m -l master --description 'Start up the daemon in master mode, which accepts data from slaves and syncs …'
complete -c alfred -s c -l update-command --description 'Specify command to execute on data change.'
complete -c alfred -s p -l sync-period --description 'Specify alfred synchronization period, in seconds.'
complete -c alfred -s 4 --description 'Specify the IPv4 multicast group address and enable IPv4 data-sharing (disabl…'

