# anacron
# Autogenerated from man page /usr/share/man/man8/anacron.8.gz
complete -c anacron -s f --description 'Forces execution of all jobs, ignoring any timestamps.'
complete -c anacron -s u --description 'Updates the timestamps of all jobs to the current date, but does not run any.'
complete -c anacron -s s --description 'Serializes execution of jobs.'
complete -c anacron -s n --description 'Runs jobs immediately and ignores the specified delays in the  /etc/anacronta…'
complete -c anacron -s d --description 'Does not fork Anacron to the background.'
complete -c anacron -s q --description 'Suppresses any messages to standard error.   Only applicable with  -d .'
complete -c anacron -s t --description 'Uses the specified anacrontab, rather than the  /etc/anacrontab default one.'
complete -c anacron -s T --description 'Anacrontab testing.'
complete -c anacron -s S --description 'Uses the specified spooldir to store timestamps in.'
complete -c anacron -s V --description 'Prints version information, and exits.'
complete -c anacron -s h --description 'Prints short usage message, and exits.'

