# androiddump
# Autogenerated from man page /usr/share/man/man1/androiddump.1.gz
complete -c androiddump -l help --description 'Print program arguments.'
complete -c androiddump -l version --description 'Print program version.'
complete -c androiddump -l extcap-version --description 'Print extcapized version.'
complete -c androiddump -l debug --description 'Print additional messages.'
complete -c androiddump -l extcap-interfaces --description 'List available interfaces.'
complete -c androiddump -l extcap-interface --description 'Use specified interfaces.'
complete -c androiddump -l extcap-dlts --description 'List DLTs of specified interface.'
complete -c androiddump -l extcap-config --description 'List configuration options of specified interface.'
complete -c androiddump -l capture --description 'Start capturing from specified interface save saved it in place specified by …'
complete -c androiddump -l fifo --description 'Save captured packet to file or send it through pipe.'
complete -c androiddump -l adb-server-ip --description 'Use other then default (127. 0. 0. 1) \\s-1ADB\\s0 daemon\'s \\s-1IP\\s0 address.'
complete -c androiddump -l adb-server-tcp-port --description 'Use other then default (5037) \\s-1ADB\\s0 daemon\'s \\s-1TCP\\s0 port.'
complete -c androiddump -l logcat-text --description 'If \\s-1TRUE\\s0 then use text logcat rather then binary.'
complete -c androiddump -l bt-server-tcp-port --description 'Use other then default Bluetooth server \\s-1TCP\\s0 port on Android side.'
complete -c androiddump -l bt-forward-socket --description 'If \\s-1TRUE\\s0 then socket from Android side is forwarded to host side.'
complete -c androiddump -l bt-local-ip --description 'Use other then default (127. 0. 0.'

