# arpspoof
# Autogenerated from man page /usr/share/man/man8/arpspoof.8.gz
complete -c arpspoof -s i --description 'Specify the interface to use.'
complete -c arpspoof -s c --description 'Specify which hardware address t use when restoring the arp configuration; wh…'
complete -c arpspoof -s t --description 'Specify a particular host to ARP poison (if not specified, all hosts on the L…'
complete -c arpspoof -s r --description 'Poison both hosts (host and target) to capture traffic in both directions.'

