# atftp
# Autogenerated from man page /usr/share/man/man1/atftp.1.gz
complete -c atftp -s g -l get --description 'Non interactive invocation only.'
complete -c atftp -l mget --description 'Non interactive invocation only.'
complete -c atftp -s p -l put --description 'Non interactive invocation only.'
complete -c atftp -s P -l password --description 'Give password to tftp server.'
complete -c atftp -s l -l local-file --description 'Non interactive invocation only.'
complete -c atftp -s r -l remote-file --description 'Non interactive invocation only.'
complete -c atftp -l tftp-timeout --description 'Number of seconds for timeout of the client.  Default is 5 seconds.'
complete -c atftp -l option --description 'Set option "name" to "value".'
complete -c atftp -l mtftp --description 'Set mtftp possible options.'
complete -c atftp -l no-source-port-checking --description 'See atftpd\'s man page.'
complete -c atftp -l verbose --description 'Instruct atftp to be verbose.'
complete -c atftp -l trace --description 'This is useful for debugging purpose to display all packet going to and from …'
complete -c atftp -s V -l version --description 'Print version.'
complete -c atftp -s h -l help --description 'Print a summary of command line arguments.'

