# atmarpd
# Autogenerated from man page /usr/share/man/man8/atmarpd.8.gz
complete -c atmarpd -s b --description 'Run in background (i. e.  in a forked child process) after initializing.'
complete -c atmarpd -s d --description 'Enables (lots of) debugging output.  By default, atmarpd is comparably quiet.'
complete -c atmarpd -o Ddump_dir --description 'Changes the directory where atmarpd writes its table (atmarpd. table).'
complete -c atmarpd -o llogfile --description 'Write diagnostic messages to the specified file instead of to standard error.'
complete -c atmarpd -s m --description 'Enables merging of incoming calls if the address is known.'
complete -c atmarpd -s n --description 'Prints addresses in numeric format only, i. e.'
complete -c atmarpd -s D --description 'Changes the directory where atmarpd writes its table (atmarpd. table).'
complete -c atmarpd -s l --description 'Write diagnostic messages to the specified file instead of to standard error.'
complete -c atmarpd -s V --description 'Prints the version number of atmarpd on standard output and exits.'

