# atmaddr
# Autogenerated from man page /usr/share/man/man8/atmaddr.8.gz
complete -c atmaddr -s a --description 'append the specified address at the end of the list.'
complete -c atmaddr -s d --description 'delete the specified address from the list.'
complete -c atmaddr -s n --description 'numeric address output only.  No address to name translation is attempted.'
complete -c atmaddr -s r --description 'reset (clear) the local address list of the specified interface.'
complete -c atmaddr -s V --description 'print the version number of atmaddr on standard output and exit.'

