# atmarp
# Autogenerated from man page /usr/share/man/man8/atmarp.8.gz
complete -c atmarp -s a --description 'list the current ATMARP table.'
complete -c atmarp -s c --description 'create the specified IP interface.'
complete -c atmarp -s q --description 'sets the QOS and the send buffer size to use as the default for all VCs gener…'
complete -c atmarp -s s --description 'set up a PVC or create an SVC entry.  The following options are recognized: .'
complete -c atmarp -s d --description 'delete the specified ARP entry.'
complete -c atmarp -s V --description 'print the version number of atmarp on standard output and exit.'

