# atmloop
# Autogenerated from man page /usr/share/man/man8/atmloop.8.gz
complete -c atmloop -s s --description 'set loopback mode.'
complete -c atmloop -o llevel --description 'enable local loopback.'
complete -c atmloop -o rlevel --description 'enable remote loopback.'
complete -c atmloop -o qlevel --description 'query loopback levels supported by the interface.'
complete -c atmloop -s l --description 'enable local loopback.'
complete -c atmloop -s r --description 'enable remote loopback.'
complete -c atmloop -s q --description 'query loopback levels supported by the interface.'
complete -c atmloop -s V --description 'print version number of atmloop on standard output and exit.'

