# atmtcp
# Autogenerated from man page /usr/share/man/man8/atmtcp.8.gz
complete -c atmtcp -s d --description 'print detailed progress information on standard error.'
complete -c atmtcp -s v --description 'print some progress information on standard error.'
complete -c atmtcp -s V --description 'print version number of atmtcp on standard output and exit.'

