# autossh
# Autogenerated from man page /usr/share/man/man1/autossh.1.gz
complete -c autossh -s M --description 'specifies the base monitoring port to use.'
complete -c autossh -s f --description 'causes autossh to drop to the background before running ssh.'
complete -c autossh -s V --description 'causes autossh to display its version number and exit.'

