# b43-fwcutter
# Autogenerated from man page /usr/share/man/man1/b43-fwcutter.1.gz
complete -c b43-fwcutter -s l -l list --description 'List supported driver versions.'
complete -c b43-fwcutter -s i -l identify --description 'Only identify the driver file (don\'t extract).'
complete -c b43-fwcutter -s w -l target-dir --description 'Extract and write firmware to DIR.'
complete -c b43-fwcutter -s a -l alt-iv --description 'Extract alternative initvals (only 3. 10. x. x).'
complete -c b43-fwcutter -s v -l version --description 'Print b43-fwcutter version.'
complete -c b43-fwcutter -s h -l help --description 'Print help information AUTHORS b43 development team, http://wireless. kernel.'

