# batctl
# Autogenerated from man page /usr/share/man/man8/batctl.8.gz
complete -c batctl -s t -s r --description 'batctl will monitor for events from the netlink kernel interface of batman-ad…'
complete -c batctl -s c --description 'Layer 2 ping of a MAC address or bat-host name.'
complete -c batctl -s p --description 'batctl will display all packets that are seen on the given interface(s).'
complete -c batctl -s l --description 'Analyses the B. A. T. M. A. N.'
complete -c batctl -s m --description '.'
complete -c batctl -s h --description '.'
complete -c batctl -s v --description 'commands: [meshif <netdev>] interface|if [-M] [add|del iface(s)] If no parame…'
complete -c batctl -s w --description '.'
complete -c batctl -s n --description '.'
complete -c batctl -s H --description 'The originator table also supports the "-t" filter option to remove all origi…'

