# bdeinfo
# Autogenerated from man page /usr/share/man/man1/bdeinfo.1.gz
complete -c bdeinfo -s h --description 'shows this help.'
complete -c bdeinfo -s k --description 'the full volume encryption key and tweak key formatted in base16 and separate…'
complete -c bdeinfo -s o --description 'specify the volume offset in bytes fl p Ar password specify the password.'
complete -c bdeinfo -s r --description 'specify the recovery password.'
complete -c bdeinfo -s s --description 'specify the file containing the startup key.'
complete -c bdeinfo -s v --description 'verbose output to stderr.'
complete -c bdeinfo -s V --description 'print version El ENVIRONMENT None FILES None EXAMPLES -literal # bdeinfo -p P…'

