# bladeRF-cli
# Autogenerated from man page /usr/share/man/man1/bladeRF-cli.1.gz
complete -c bladeRF-cli -s d -l device --description 'Use the specified bladeRF device.'
complete -c bladeRF-cli -s f -l flash-firmware --description 'Write the provided FX3 firmware file to flash.'
complete -c bladeRF-cli -s l -l load-fpga --description 'Load the provided FPGA bitstream.'
complete -c bladeRF-cli -s L -l flash-fpga --description 'Write the provided FPGA image to flash for autoloading.'
complete -c bladeRF-cli -s p -l probe --description 'Probe for devices, print results, then exit.'
complete -c bladeRF-cli -s e -l exec --description 'Execute the specified interactive mode command.'
complete -c bladeRF-cli -s s -l script --description 'Run provided script.'
complete -c bladeRF-cli -s i -l interactive --description 'Enter interactive mode.'
complete -c bladeRF-cli -l lib-version --description 'Print libbladeRF version and exit.'
complete -c bladeRF-cli -s v -l verbosity --description 'Set the libbladeRF verbosity level.'
complete -c bladeRF-cli -l version --description 'Print CLI version and exit.'
complete -c bladeRF-cli -s h -l help --description 'Show this help text.'
complete -c bladeRF-cli -l help-interactive --description 'Print help information for all interactive commands. SS "Notes:".'

