# bonesi
# Autogenerated from man page /usr/share/man/man1/bonesi.1.gz
complete -c bonesi -s i -l ips --description 'read ip addresses from this file.'
complete -c bonesi -s p -l protocol --description 'udp (default), icmp or tcp.'
complete -c bonesi -s r -l send_rate --description 'packets per second, 0 = infinite (default).'
complete -c bonesi -s s -l playload_size --description 'size of the paylod, (default: 32).'
complete -c bonesi -s o -l stats_file --description 'filename for the statistics, (default: \'stats\').'
complete -c bonesi -s c -l max_packets --description 'maximum number of packets (requests at tcp/http) . br 0 = infinite (default).'
complete -c bonesi -l integer --description 'IPs are integers in host byte order instead of in dotted notation.'
complete -c bonesi -s t -l max_bots --description 'determine max_bots in the 24bit prefix randomly (1-256).'
complete -c bonesi -s u -l url --description 'the url (default: \'/\') (only for tcp/http).'
complete -c bonesi -s l -l url_list --description 'filename with url list (only for tcp/http).'
complete -c bonesi -s b -l useragent_list --description 'filename with useragent list (only for tcp/http).'
complete -c bonesi -s d -l device --description 'network listening device (only for tcp/http).'
complete -c bonesi -s v -l verbose --description 'print additional debug messages.'
complete -c bonesi -s h -l help --description 'print the help message and exit EXAMPLES Send 2 udp packets per second with a…'

