# bruteforce-luks
# Autogenerated from man page /usr/share/man/man1/bruteforce-luks.1.gz
complete -c bruteforce-luks -s b --description 'Beginning of the password.  Default: "".'
complete -c bruteforce-luks -s e --description 'End of the password.  Default: "".'
complete -c bruteforce-luks -s f --description 'Read the passwords from a file instead of generating them.'
complete -c bruteforce-luks -s h --description 'Show help and quit.'
complete -c bruteforce-luks -s l --description 'Minimum password length (beginning and end included).  Default: 1.'
complete -c bruteforce-luks -s m --description 'Maximum password length (beginning and end included).  Default: 8.'
complete -c bruteforce-luks -s s --description 'Password character set.'
complete -c bruteforce-luks -s t --description 'Number of threads to use.  Default: 1.'
complete -c bruteforce-luks -s v --description 'Print progress info every n seconds.'
complete -c bruteforce-luks -s w --description 'Restore the state of a previous session if the file exists, then write the st…'

