# bsqlodbc
# Autogenerated from man page /usr/share/man/man1/bsqlodbc.1.gz
complete -c bsqlodbc -s U --description 'Database server login name.'
complete -c bsqlodbc -s P --description 'Database server password.'
complete -c bsqlodbc -s S --description 'Database server to which to connect.'
complete -c bsqlodbc -s D --description 'Database to use.'
complete -c bsqlodbc -s i --description 'Name of script file, containing SQL.'
complete -c bsqlodbc -s o --description 'Name of output file, holding result data.'
complete -c bsqlodbc -s e --description 'Name of file for errors.'
complete -c bsqlodbc -s t --description 'Specifies the field terminator.  Default is two spaces ( \\ ).'
complete -c bsqlodbc -s h --description 'Print column headers with the data to the same file.'
complete -c bsqlodbc -s q --description 'Do not print column metadata, return status, or rowcount.  Overrides h.'
complete -c bsqlodbc -s v --description 'Verbose mode, for more information about the ODBC interaction.'
complete -c bsqlodbc -s V --description 'Specify ODBC version (2 or 3).'

