# btcflash
# Autogenerated from man page /usr/share/man/man1/btcflash.1.gz
complete -c btcflash -o help --description 'Prints a short summary of the   p options and exists.'
complete -c btcflash -o version --description 'Print version information and exit.'
complete -c btcflash -s d --description 'Set the misc debug value to # (with debug=#) or increment the misc debug leve…'
complete -c btcflash -o silent -s s --description 'Do not print out a status report for failed SCSI commands.'
complete -c btcflash -s v --description 'Increment the level of general verbosity by one.  This is used e. g.'
complete -c btcflash -s V --description 'Increment the verbose level with respect of SCSI command transport by one.'
complete -c btcflash -o scanbus --description 'Scan all SCSI devices on all SCSI busses and print the inquiry strings.'
complete -c btcflash -o dd --description 'this equals to  debug= 2.'
complete -c btcflash -o debug --description 'slows down the process and may be the reason for a buffer underrun.'
complete -c btcflash -o VV --description 'will show data buffer content in addition.  Using.'

