# buddy-ng
# Autogenerated from man page /usr/share/man/man1/buddy-ng.1.gz
complete -c buddy-ng -s h --description 'Shows the help screen.'
complete -c buddy-ng -s p --description 'Don\'t drop privileges AUTHOR This manual page was written by Thomas d\'Otreppe.'

