# caca-config
# Autogenerated from man page /usr/share/man/man1/caca-config.1.gz
complete -c caca-config -l cflags --description 'Print the compiler flags that are necessary to compile a program or library t…'
complete -c caca-config -l exec-prefix --description 'If specified, use  DIR instead of the installation exec prefix that libcaca w…'
complete -c caca-config -l libs --description 'Print the linker flags that are necessary to link a program or library that u…'
complete -c caca-config -l prefix --description 'If specified, use PREFIX instead of the installation prefix that libcaca was …'
complete -c caca-config -l version --description 'Prints the currently installed version of libcaca on standard output.'

