# calc
# Autogenerated from man page /usr/share/man/man1/calc.1.gz
complete -c calc -s c --description 'Continue reading command lines even after a scan/parse error has caused the a…'
complete -c calc -s C --description 'Permit the execution of custom builtin functions.'
complete -c calc -s d --description 'Disable the printing of the opening title.'
complete -c calc -s D --description 'Force the initial value of config("calc_debug"), config("resource_debug") and…'
complete -c calc -s e --description 'Ignore any environment variables on startup.'
complete -c calc -s f --description 'This flag is required when using calc in  "shell script mode" .'
complete -c calc -s h --description 'Print a help message.   This option implies  -q .'
complete -c calc -s i --description 'Become interactive if possible.'
complete -c calc -s m --description 'This flag sets the permission mode of  calc .'
complete -c calc -s O --description 'Use the old classic defaults instead of the default configuration.'
complete -c calc -s p --description 'Pipe processing is enabled by use of  -p .  For example: . sp 1 . in +5n .'
complete -c calc -s q --description 'Disable the reading of the startup scripts.'
complete -c calc -s s --description 'By default, all  calc_cmd args are evaluated and executed.'
complete -c calc -s u --description 'Disable buffering of stdin and stdout.'
complete -c calc -s v --description 'Print the  calc version number and exit.'
complete -c calc -s n --description 'to setup a modified form of the default calc configuration.  The.'

