# cargo
# Autogenerated from man page /usr/share/man/man1/cargo.1.gz
complete -c cargo -s V --description '.'
complete -c cargo -l version --description '.'
complete -c cargo -l list --description '.'
complete -c cargo -l explain --description '.'
complete -c cargo -s v --description '.'
complete -c cargo -l verbose --description '.'
complete -c cargo -s q --description '.'
complete -c cargo -l quiet --description '.'
complete -c cargo -l color --description '.'
complete -c cargo -l frozen --description '.'
complete -c cargo -l locked --description '.'
complete -c cargo -l offline --description '.'
complete -c cargo -s h --description '.'
complete -c cargo -l help --description '.'
complete -c cargo -s Z --description '.'

