# cargo-pkgid
# Autogenerated from man page /usr/share/man/man1/cargo-pkgid.1.gz
complete -c cargo-pkgid -s p --description '.'
complete -c cargo-pkgid -l package --description '.'
complete -c cargo-pkgid -s v --description '.'
complete -c cargo-pkgid -l verbose --description '.'
complete -c cargo-pkgid -s q --description '.'
complete -c cargo-pkgid -l quiet --description '.'
complete -c cargo-pkgid -l color --description '.'
complete -c cargo-pkgid -l manifest-path --description '.'
complete -c cargo-pkgid -l frozen --description '.'
complete -c cargo-pkgid -l locked --description '.'
complete -c cargo-pkgid -l offline --description '.'
complete -c cargo-pkgid -s h --description '.'
complete -c cargo-pkgid -l help --description '.'
complete -c cargo-pkgid -s Z --description '.'

