# cargo-generate-lockfile
# Autogenerated from man page /usr/share/man/man1/cargo-generate-lockfile.1.gz
complete -c cargo-generate-lockfile -s v --description '.'
complete -c cargo-generate-lockfile -l verbose --description '.'
complete -c cargo-generate-lockfile -s q --description '.'
complete -c cargo-generate-lockfile -l quiet --description '.'
complete -c cargo-generate-lockfile -l color --description '.'
complete -c cargo-generate-lockfile -l manifest-path --description '.'
complete -c cargo-generate-lockfile -l frozen --description '.'
complete -c cargo-generate-lockfile -l locked --description '.'
complete -c cargo-generate-lockfile -l offline --description '.'
complete -c cargo-generate-lockfile -s h --description '.'
complete -c cargo-generate-lockfile -l help --description '.'
complete -c cargo-generate-lockfile -s Z --description '.'

