# cargo-fetch
# Autogenerated from man page /usr/share/man/man1/cargo-fetch.1.gz
complete -c cargo-fetch -l target --description '.'
complete -c cargo-fetch -s v --description '.'
complete -c cargo-fetch -l verbose --description '.'
complete -c cargo-fetch -s q --description '.'
complete -c cargo-fetch -l quiet --description '.'
complete -c cargo-fetch -l color --description '.'
complete -c cargo-fetch -l manifest-path --description '.'
complete -c cargo-fetch -l frozen --description '.'
complete -c cargo-fetch -l locked --description '.'
complete -c cargo-fetch -l offline --description '.'
complete -c cargo-fetch -s h --description '.'
complete -c cargo-fetch -l help --description '.'
complete -c cargo-fetch -s Z --description '.'

