# cccheck
# Autogenerated from man page /usr/share/man/man1/cccheck.1.gz
complete -c cccheck -l assembly --description 'The assembly to perform static verification.'
complete -c cccheck -l debug --description 'Shows debug information about process of proving the assertions.'
complete -c cccheck -l method --description 'String for finding method.'
complete -c cccheck -l help --description 'Show help for cccheck, listing configuration options.'

