# ccmakedep
# Autogenerated from man page /usr/share/man/man1/ccmakedep.1.gz
complete -c ccmakedep -s a --description 'Append the dependencies to the file instead of replacing existing dependencie…'
complete -c ccmakedep -o cc --description 'Use this compiler to generate dependencies.'
complete -c ccmakedep -s f --description 'Filename.'
complete -c ccmakedep -s s --description 'Starting string delimiter.'
complete -c ccmakedep -s v --description 'Be verbose: display the C compiler command before running it.'
complete -c ccmakedep -s D --description 'and.'
complete -c ccmakedep -s U --description 'options to define and undefine symbols and.'
complete -c ccmakedep -s I --description 'to set the include path.'
complete -c ccmakedep -o f- --description 'sends the output to standard output instead of modifying an existing file.'

