# cdb
# Autogenerated from man page /usr/share/man/man1/cdb.1.gz
complete -c cdb -o nnum --description 'causes cdb to find and write a record with a given number num starting with 1…'
complete -c cdb -s m --description 'newline will be added after every value printed.'
complete -c cdb -s t --description 'use given tmpname as temporary file.   Defaults to dbname. tmp (i. e.'
complete -c cdb -s p --description 'permissions for the newly created file (usually an octal number, like 0644).'
complete -c cdb -s w --description 'warn about duplicate keys.'
complete -c cdb -s e --description 'abort on duplicate keys (implies -w).'
complete -c cdb -s r --description 'replace existing key with new one in case of duplicate.'
complete -c cdb -s 0 --description 'zero-fill existing records when duplicate records are added.'
complete -c cdb -s u --description 'do not add duplicate records.'
complete -c cdb -s c --description 'create mode.'
complete -c cdb -s d --description 'dump mode.'
complete -c cdb -s h --description 'print short help and exit.'
complete -c cdb -s l --description 'list mode.'
complete -c cdb -s q --description 'query mode.'
complete -c cdb -s s --description 'statistics mode.'

