# cert-sync
# Autogenerated from man page /usr/share/man/man1/cert-sync.1.gz
complete -c cert-sync -l quiet --description 'Suppress verbose output.'
complete -c cert-sync -l user --description 'Populate the per-user store in the user\'s home directory, instead of the  sys…'

