# cg_annotate
# Autogenerated from man page /usr/share/man/man1/cg_annotate.1.gz
complete -c cg_annotate -s h -l help --description 'Show the help message.'
complete -c cg_annotate -l version --description 'Show the version number.'
complete -c cg_annotate -l show --description 'Specifies which events to show (and the column order).'
complete -c cg_annotate -l sort --description 'Specifies the events upon which the sorting of the function-by-function entri…'
complete -c cg_annotate -l threshold --description 'Sets the threshold for the function-by-function summary.'
complete -c cg_annotate -l show-percs --description 'When enabled, a percentage is printed next to all event counts.'
complete -c cg_annotate -l auto --description 'When enabled, automatically annotates every file that is mentioned in the fun…'
complete -c cg_annotate -l context --description 'Print N lines of context before and after each annotated line.'
complete -c cg_annotate -o 'I<dir>' -l include --description 'Adds a directory to the list in which to search for files.'
complete -c cg_annotate -o I/--include --description 'options can be given to add multiple directories.'

