# checksec
# Autogenerated from man page /usr/share/man/man1/checksec.1.gz
complete -c checksec -l output -l format --description 'Output the results in different formats for ingestion to other applications.'
complete -c checksec -l help --description 'Displays the help text.'
complete -c checksec -l file --description 'Checks individual files for security features compiled into the executable.'
complete -c checksec -l dir --description 'Recursively checks all executable files in the directory for security feature…'
complete -c checksec -l proc --description 'Checks the security features of a running process by name.'
complete -c checksec -l proc-all --description 'Checks the security features of all running processes.'
complete -c checksec -l proc-libs --description 'Checks the security features of the all libraries of a running process ID.'
complete -c checksec -l kernel --description 'Checks the security features of the running kernel or a specified kernel conf…'
complete -c checksec -l fortify-file --description 'Checks the fortifiability of a file and if any of the fortifiable features ha…'
complete -c checksec -l fortify-proc --description 'Checks the fortifiability of a running process and if any of the fortifiable …'
complete -c checksec -l version --description 'Shows the current version of the running software.'
complete -c checksec -l update -l upgrade --description 'Checks source for a signed update and updates the application if available.'
complete -c checksec -l debug --description 'AUTHORS Brian Davis <slimm609 at gmail dot com>.'

