# ciscodump
# Autogenerated from man page /usr/share/man/man1/ciscodump.1.gz
complete -c ciscodump -l help --description 'PD Print program arguments.'
complete -c ciscodump -l version --description 'Print program version.'
complete -c ciscodump -l extcap-interfaces --description 'List available interfaces.'
complete -c ciscodump -l extcap-interface --description 'Use specified interfaces.'
complete -c ciscodump -l extcap-dlts --description 'List DLTs of specified interface.'
complete -c ciscodump -l extcap-config --description 'List configuration options of specified interface.'
complete -c ciscodump -l capture --description 'Start capturing from specified interface and save it in place specified by --…'
complete -c ciscodump -l fifo --description 'Save captured packet to file or send it through pipe.'
complete -c ciscodump -l remote-host --description 'The address of the remote host for capture.'
complete -c ciscodump -l remote-port --description 'The \\s-1SSH\\s0 port of the remote host.'
complete -c ciscodump -l remote-username --description 'The username for ssh authentication.'
complete -c ciscodump -l remote-password --description 'The password to use (if not ssh-agent and pubkey are used).'
complete -c ciscodump -l remote-filter --description 'The remote filter on the router.'
complete -c ciscodump -l sshkey --description 'The path to a private key for authentication.'
complete -c ciscodump -l remote-interface --description 'The remote network interface to capture from.'

