# clddb-tool
# Autogenerated from man page /usr/share/man/man8/clddb-tool.8.gz
complete -c clddb-tool -s h -l help --description 'Show the help message and exit.'
complete -c clddb-tool -s p -l path --description 'Open the sqlite database located at  dbpath instead of R /var/lib/nfs/nfsdcld…'
complete -c clddb-tool -s v -l version --description 'The schema version to downgrade to.'
complete -c clddb-tool -s s -l summary --description 'option is not given, also prints the clients in the reboot epoch tables.'

