# cmark-gfm
# Autogenerated from man page /usr/share/man/man1/cmark-gfm.1.gz
complete -c cmark-gfm -l to -s t --description 'Specify output format (html, man, xml, latex, commonmark).'
complete -c cmark-gfm -l width --description 'Specify a column width to which to wrap the output.'
complete -c cmark-gfm -l hardbreaks --description 'Render soft breaks (newlines inside paragraphs in the CommonMark source) as h…'
complete -c cmark-gfm -l nobreaks --description 'Render soft breaks as spaces.'
complete -c cmark-gfm -l sourcepos --description 'Include source position attribute.'
complete -c cmark-gfm -l normalize --description 'Consolidate adjacent text nodes.'
complete -c cmark-gfm -l extension -s e --description 'Specify an extension name to use.'
complete -c cmark-gfm -l list-extensions --description 'List available extensions and quit.'
complete -c cmark-gfm -l validate-utf8 --description 'Validate UTF-8, replacing illegal sequences with U+FFFD.'
complete -c cmark-gfm -l smart --description 'Use smart punctuation.'
complete -c cmark-gfm -l - --description ' will be rendered as ellipses.'
complete -c cmark-gfm -l safe --description 'Do not render raw HTML or potentially dangerous URLs.'
complete -c cmark-gfm -l help --description 'Print usage information.'
complete -c cmark-gfm -l version --description 'Print version.'

