# combine_tessdata
# Autogenerated from man page /usr/share/man/man1/combine_tessdata.1.gz
complete -c combine_tessdata -s c --description '.'
complete -c combine_tessdata -s d --description '.'
complete -c combine_tessdata -s e --description '.'
complete -c combine_tessdata -s o --description '.'
complete -c combine_tessdata -s u --description 'CAVEATS.'

