# copydatabase
# Autogenerated from man page /usr/share/man/man1/copydatabase.1.gz
complete -c copydatabase -l no-renumber --description 'Preserve the numbering of document ids (useful if you have external reference…'
complete -c copydatabase -l help --description 'display this help and exit.'
complete -c copydatabase -l version --description 'output version information and exit.'

