# create-native-map
# Autogenerated from man page /usr/share/man/man1/create-native-map.1.gz
complete -c create-native-map -l autoconf-header --description 'HEADER is a header file name in the syntax typically used with the C   #inclu…'
complete -c create-native-map -l autoconf-member --description 'Specify that any access to   MEMBER should be wrapped within a   #ifdef HAVE_…'
complete -c create-native-map -l exclude-native-symbol --description 'SYMBOL is a   [DllImport] -marked method that should  not have a prototype ge…'
complete -c create-native-map -l impl-header --description 'Insert a   #include statement within the generated   . c file for   HEADER .'
complete -c create-native-map -l impl-macro --description 'Insert a  #define statement within the generated  . c file.'
complete -c create-native-map -l library --description 'Create prototypes for  [DllImport] -marked methods which reference the native…'
complete -c create-native-map -l public-header --description 'Insert a   #include statement within the generated   . h file for   HEADER .'
complete -c create-native-map -l public-macro --description 'Insert a  #define statement within the generated  . h file.'
complete -c create-native-map -l rename-member --description 'This is used when   FROM is a C macro, and thus must be altered in order to b…'
complete -c create-native-map -o marked --description 'not have a prototype generated for it.'
complete -c create-native-map -l rename-namespace --description 'By default, the C "namespace" (symbol prefix) is the C# namespace; types  wit…'
complete -c create-native-map -o decorated --description 'MapAttribute properties: NativeType Contains the corresponding C type.'

