# cronnext
# Autogenerated from man page /usr/share/man/man1/cronnext.1.gz
complete -c cronnext -s i --description 'Consider only the crontabs of the specified users.'
complete -c cronnext -s e --description 'Do not consider the crontabs of the specified users.'
complete -c cronnext -s s --description 'Do not consider the system crontab, usually the  /etc/crontab file.'
complete -c cronnext -s a --description 'Use the crontabs installed in the system in addition to the ones passed as fi…'
complete -c cronnext -s t --description 'Determine the next job from this time, instead of now.'
complete -c cronnext -s q --description 'Do not check jobs over this time, expressed in the same way as in option  -t .'
complete -c cronnext -s j --description 'Only look for jobs that contain command as a substring.'
complete -c cronnext -s l --description 'Print the whole entries of the jobs that are the next to be executed by cron.'
complete -c cronnext -s c --description 'Print every entry in every crontab with the next time it is executed.'
complete -c cronnext -s f --description 'Print all jobs that are executed in the given interval.  Requires option -q.'
complete -c cronnext -s h --description 'Print usage output and exit.'
complete -c cronnext -s V --description 'Print version and exit.  AUTHOR.'

