# crunch
# Autogenerated from man page /usr/share/man/man1/crunch.1.gz
complete -c crunch -s b --description '.'
complete -c crunch -s c --description '.'
complete -c crunch -s d --description '.'
complete -c crunch -s e --description '.'
complete -c crunch -s f --description '.'
complete -c crunch -s i --description '.'
complete -c crunch -s l -s t -s l -s t --description '.'
complete -c crunch -s m -s p -s p --description '.'
complete -c crunch -s o --description '.'
complete -c crunch -s q --description '.'
complete -c crunch -s r -s r -s s -s s -s r --description '.'
complete -c crunch -s u --description '.'
complete -c crunch -s z --description '.'

