# ctdb
# Autogenerated from man page /usr/share/man/man1/ctdb.1.gz
complete -c ctdb -s n --description 'The node specified by PNN should be queried for the requested information.'
complete -c ctdb -s Y --description 'Produce output in machine readable form for easier parsing by scripts.'
complete -c ctdb -s x --description 'Use SEPARATOR to delimit fields in machine readable output.  This implies -Y.'
complete -c ctdb -s X --description 'Produce output in machine readable form for easier parsing by scripts.'
complete -c ctdb -s t --description 'Indicates that ctdb should wait up to TIMEOUT seconds for a response to most …'
complete -c ctdb -s T --description 'Indicates that TIMELIMIT is the maximum run time (in seconds) for the ctdb co…'
complete -c ctdb -s '?' -l help --description 'Print some help text to the screen.'
complete -c ctdb -l usage --description 'Print usage information to the screen.'
complete -c ctdb -s d -l debug --description 'Change the debug level for the command.  Default is NOTICE.'
complete -c ctdb -l print-emptyrecords --description '.'
complete -c ctdb -l print-datasize --description '.'
complete -c ctdb -l print-lmaster --description '.'
complete -c ctdb -l print-hash --description '.'
complete -c ctdb -l print-recordflags --description '.'

