# curvetun
# Autogenerated from man page /usr/share/man/man8/curvetun.8.gz
complete -c curvetun -s d -l dev --description 'Defines the name of the tunnel device that is being created.'
complete -c curvetun -s p -l port --description 'Defines the port the curvetun server should listen on.'
complete -c curvetun -s t -l stun --description 'If needed, this options enables an STUN lookup in order to show public IP to …'
complete -c curvetun -s c -l client --description 'Starts curvetun in client mode and connects to the given connection alias tha…'
complete -c curvetun -s k -l keygen --description 'Generate private and public keypair.  This must be done initially.'
complete -c curvetun -s x -l export --description 'Export user and key combination to stdout as a one-liner.'
complete -c curvetun -s C -l dumpc --description 'Dump all known clients that may connect to the local curvetun server and exit.'
complete -c curvetun -s S -l dumps --description 'Dump all known servers curvetun as a client can connect to, and exit.'
complete -c curvetun -s D -l nofork --description 'Do not fork off as a client or server on startup.'
complete -c curvetun -s s -l server --description 'Start curvetun in server mode.'
complete -c curvetun -s N -l no-logging --description 'Disable all curvetun logging of user information.'
complete -c curvetun -s u -l udp --description 'Use UDP as a carrier protocol instead of TCP.'
complete -c curvetun -s 4 -l ipv4 --description 'Defines IPv4 as the underlying network protocol to be used on the tunnel devi…'
complete -c curvetun -s 6 -l ipv6 --description 'Defines IPv6 as the underlying network protocol to be used on the tunnel devi…'
complete -c curvetun -s v -l version --description 'Show version information and exit.'
complete -c curvetun -s h -l help --description 'Show user help and exit.'

