# cvereport
# Autogenerated from man page /usr/share/man/man1/cvereport.1.gz
complete -c cvereport -s d --description '.'
complete -c cvereport -s D --description 'versions of the installed software ACKNOWLEDGEMENT FILE FORMAT The XML file f…'

