# datacopy
# Autogenerated from man page /usr/share/man/man1/datacopy.1.gz
complete -c datacopy -s t --description 'Truncate target table before loading data.'
complete -c datacopy -s a --description 'Append data to target table.'
complete -c datacopy -s c --description 'Create the target table with the same schema as the source table.'
complete -c datacopy -s b --description 'The number of rows per batch of data copied.'
complete -c datacopy -s p --description 'The number of bytes, per network packet, sent to and from the servers.'
complete -c datacopy -s T --description 'Specify size of TEXT/IMAGE column from network.'
complete -c datacopy -s v --description 'Produce verbose output, including diagnostic timings.'
complete -c datacopy -s d --description 'Produce freetds TDSDUMP output.  (Serious debug only!).'
complete -c datacopy -s S --description 'The connection information for the source server and the location/name of the…'
complete -c datacopy -s D --description 'The connection information for the destination server and the location/name o…'
complete -c datacopy -s E --description 'Keep identity values.'

