# dave
# Autogenerated from man page /usr/share/man/man1/dave.1p.gz
complete -c dave -o debug --description 'el.'
complete -c dave -s h --description 'el.'
complete -c dave -o man --description 'el.'
complete -c dave -s p --description 'el.'
complete -c dave -s u --description 'el.'
complete -c dave -o tmpdir --description 'el.'

