# daxctl-online-memory
# Autogenerated from man page /usr/share/man/man1/daxctl-online-memory.1.gz
complete -c daxctl-online-memory -s r -l region --description '.'
complete -c daxctl-online-memory -l no-movable --description '.'
complete -c daxctl-online-memory -l movable --description 'memory such that it is not movable.'
complete -c daxctl-online-memory -s u -l human --description '.'
complete -c daxctl-online-memory -s v -l verbose --description '.'

