# daxctl-reconfigure-device
# Autogenerated from man page /usr/share/man/man1/daxctl-reconfigure-device.1.gz
complete -c daxctl-reconfigure-device -s r -l region --description '.'
complete -c daxctl-reconfigure-device -s m -l mode --description '.'
complete -c daxctl-reconfigure-device -s N -l no-online --description '.'
complete -c daxctl-reconfigure-device -l no-movable --description '.'
complete -c daxctl-reconfigure-device -l movable --description 'memory such that it is not movable.'
complete -c daxctl-reconfigure-device -s f -l force --description '.'
complete -c daxctl-reconfigure-device -s u -l human --description '.'
complete -c daxctl-reconfigure-device -s v -l verbose --description '.'

