# dc3dd
# Autogenerated from man page /usr/share/man/man1/dc3dd.1.gz
complete -c dc3dd -l help --description 'display this help and exit.'
complete -c dc3dd -l version --description 'output version information and exit.'
complete -c dc3dd -l ---- --description 'usage:.'
complete -c dc3dd -l ------------ --description 'basic options:.'
complete -c dc3dd -o DDEFAULT_OUTPUT_FILE_SIZE --description 'value in BYTES.'
complete -c dc3dd -o DDEFAULT_HASH_SHA256 -o DDEFAULT_HASH_SHA512 --description '.'
complete -c dc3dd -l --------------- --description 'advanced options:.'
complete -c dc3dd -l ----------- --description 'help options:.'
complete -c dc3dd -l flags --description 'display compile-time flags and exit.'

