# dcfldd
# Autogenerated from man page /usr/share/man/man1/dcfldd.1.gz
complete -c dcfldd -l help --description 'Display a help page and exit.'
complete -c dcfldd -l version --description 'Output version information and exit.'

