# dmitry
# Autogenerated from man page /usr/man/man1/dmitry.1.gz
complete -c dmitry -s o --description 'Create an ascii text output of the results to the "filename" specified.'
complete -c dmitry -s i --description 'Perform an Internet Number whois lookup on the target.'
complete -c dmitry -s w --description 'Perform a whois lookup on the \'host\' target.'
complete -c dmitry -s n --description 'Retrieve netcraft.'
complete -c dmitry -s s --description 'Perform a SubDomain search on the specified target.'
complete -c dmitry -s e --description 'Perform an EmailAddress search on the specified target.'
complete -c dmitry -s p --description 'Perform a TCP Portscan on the host target.'
complete -c dmitry -s f --description 'This option will cause the TCP Portscan module to report/display output of fi…'
complete -c dmitry -s b --description 'This option will cause the TCP Portscan module to output Banners if they are …'
complete -c dmitry -s t --description 'This sets the Time To Live (TTL) of the Portscan module when scanning individ…'

