# dns2tcpc
# Autogenerated from man page /usr/share/man/man1/dns2tcpc.1.gz
complete -c dns2tcpc -s h --description 'Help Menu.'
complete -c dns2tcpc -s c --description 'Enable DNS compression.'
complete -c dns2tcpc -s z --description 'Use this domain as endpoint.'
complete -c dns2tcpc -s d --description 'Change debug level.  Levels available are 1, 2 or 3.'
complete -c dns2tcpc -s r --description 'Remote resource to access.'
complete -c dns2tcpc -s k --description 'Pre shared key used for authentication (identification).'
complete -c dns2tcpc -s f --description 'Configuration file to use.'
complete -c dns2tcpc -s T --description 'Request type to use.  Actually only KEY and TXT requests are supported.'
complete -c dns2tcpc -s e --description 'Command to execute, I/O are redirected in the tunnel.'
complete -c dns2tcpc -s l --description 'Local port accepting incomming connections (or - for stdin on UNIX systems).'
complete -c dns2tcpc -s t --description 'Maximum DNS server\'s answer delay in seconds.'

