# dpauxmon
# Autogenerated from man page /usr/share/man/man1/dpauxmon.1.gz
complete -c dpauxmon -l help --description 'PD Print program arguments.'
complete -c dpauxmon -l version --description 'Print program version.'
complete -c dpauxmon -l extcap-interfaces --description 'List available interfaces.'
complete -c dpauxmon -l extcap-interface --description 'Use specified interfaces.'
complete -c dpauxmon -l extcap-dlts --description 'List DLTs of specified interface.'
complete -c dpauxmon -l extcap-config --description 'List configuration options of specified interface.'
complete -c dpauxmon -l capture --description 'Start capturing from specified interface and save it in place specified by --…'
complete -c dpauxmon -l fifo --description 'Save captured packet to file or send it through pipe.'

