# dubdv
# Autogenerated from man page /usr/share/man/man1/dubdv.1.gz
complete -c dubdv -l version --description 'show dubdv version number.'
complete -c dubdv -s v -l verbose --description 'show encoder statistics / status information.'
complete -c dubdv -s a -l audio-input --description 'Choose audio-input-filter: [none, >wav<, dsp] WAV is the default audio_input …'
complete -c dubdv -s o -l output --description 'Choose output-filter: [>raw<].'
complete -c dubdv -s t -l truncate --description 'truncate output at end of DV input.'
complete -c dubdv -s r -l repeat --description 'repeat the first video frame count times.'
complete -c dubdv -s '?' -l help --description 'Show help message.'
complete -c dubdv -l usage --description 'Display brief usage message.'

