# ebfc
# Autogenerated from man page /usr/share/man/man1/ebfc.1.gz
complete -c ebfc -s x --description 'Compile the source code into a standalone executable file, named foo .'
complete -c ebfc -s l --description 'Compile the source code into a function, named foo (), in a shared library fi…'
complete -c ebfc -s c --description 'Compile the source code into a function, named foo (), in an object file, nam…'
complete -c ebfc -o xc --description 'Compile the source code into an object file, named foo.'
complete -c ebfc -o lc --description 'Compile the source code into a function, named foo (), in an object file, nam…'
complete -c ebfc -s f --description 'Use FUNCTION as the name of the function to contain the compiled program.'
complete -c ebfc -s o --description 'Use FILE as the target filename.'
complete -c ebfc -s i --description 'Use FILE as the name of the source file to place in the target file.'
complete -c ebfc -s s --description 'option is not used.'
complete -c ebfc -s h --description 'Display help and exit.'
complete -c ebfc -s v --description 'Display version number and exit.'
complete -c ebfc -s z --description 'Read the source file in compressed Brainfuck format.'

