# efi-updatevar
# Autogenerated from man page /usr/share/man/man1/efi-updatevar.1.gz
complete -c efi-updatevar -s a --description 'append a value to the variable instead of replacing it.'
complete -c efi-updatevar -s e --description 'use EFI Signature List instead of signed update (only works in Setup Mode.'
complete -c efi-updatevar -s b --description 'Add hash of <binfile> to the signature list.'
complete -c efi-updatevar -s f --description 'Add or Replace the key file (. esl or . auth) to the <var>.'
complete -c efi-updatevar -s c --description 'Add or Replace the x509 certificate to the <var> (with <guid> if provided).'
complete -c efi-updatevar -s g --description 'Optional <guid> for the X509 Certificate.'
complete -c efi-updatevar -s k --description 'Secret key file for authorising User Mode updates.'
complete -c efi-updatevar -s d --description 'Delete the signature list <list> (or just a single <entry> within the list).'
complete -c efi-updatevar -l engine --description 'Use engine <eng> for private key EXAMPLES.'

