# elftoc
# Autogenerated from man page /usr/share/man/man1/elftoc.1.gz
complete -c elftoc -s e -l force-end --description 'Force inclusion of a final _end field in the C struct.'
complete -c elftoc -s E -l exclude-end --description 'Do not include a final _end field, even if padding is present at the end of t…'
complete -c elftoc -s w -l width --description 'Set the maximum line width in the output to R N .'
complete -c elftoc -s i -l indent --description 'Set the number of spaces to indent to R N .'
complete -c elftoc -s s -l structname --description 'Set the name of the C struct in the generated source code to R NAME .'
complete -c elftoc -s v -l varname --description 'Set the name of the variable in the generated source code to R NAME .'
complete -c elftoc -s m -l allow-misaligned --description 'A misaligned section in the ELF file would cause padding bytes to be inserted…'
complete -c elftoc -s q -l quiet --description 'Suppress warning messages regarding invalid and contradictory values in the E…'
complete -c elftoc -s o -l output --description 'Write the C source code to  FILENAME instead of to standard output.'
complete -c elftoc -l help --description 'Display help and exit.'
complete -c elftoc -l version --description 'Display version information and exit.'

