# esi
# Autogenerated from man page /usr/share/man/man8/esi.8.gz
complete -c esi -s f --description 'force overwriting an existing ESI.'
complete -c esi -s V --description 'print version number of esi on standard output and exit.'

