# ewfinfo
# Autogenerated from man page /usr/share/man/man1/ewfinfo.1.gz
complete -c ewfinfo -s A --description 'the codepage of header section, options: ascii (default), windows-874, window…'
complete -c ewfinfo -s d --description 'the date format, options: ctime (default), dm (day/month), md (month/day), is…'
complete -c ewfinfo -s e --description 'only show EWF read error information.'
complete -c ewfinfo -s f --description 'specify the output format, options: text (default), dfxml.'
complete -c ewfinfo -s h --description 'shows this help.'
complete -c ewfinfo -s i --description 'only show EWF acquiry information.'
complete -c ewfinfo -s m --description 'only show EWF media information.'
complete -c ewfinfo -s v --description 'verbose output to stderr.'
complete -c ewfinfo -s V --description 'print version El ENVIRONMENT None FILES None EXAMPLES -literal # ewfinfo \\-d …'

