# ewfmount
# Autogenerated from man page /usr/share/man/man1/ewfmount.1.gz
complete -c ewfmount -s f --description 'specify the input format, options: raw (default), files (restricted to logica…'
complete -c ewfmount -s h --description 'shows this help.'
complete -c ewfmount -s v --description 'verbose output to stderr.'
complete -c ewfmount -s V --description 'print version.'
complete -c ewfmount -s X --description 'extended options to pass to sub system El ENVIRONMENT None FILES None EXAMPLE…'

