# ewfrecover
# Autogenerated from man page /usr/share/man/man1/ewfrecover.1.gz
complete -c ewfrecover -s A --description 'the codepage of header section, options: ascii (default), windows-874, window…'
complete -c ewfrecover -s h --description 'shows this help.'
complete -c ewfrecover -s l --description 'logs recover errors and the digest (hash) to the log filename.'
complete -c ewfrecover -s p --description 'the process buffer size (default is the chunk size).'
complete -c ewfrecover -s t --description 'the target file to recover to (default is recover).'
complete -c ewfrecover -s v --description 'verbose output to stderr.'
complete -c ewfrecover -s V --description 'print version.'
complete -c ewfrecover -s x --description 'use the chunk data instead of the buffered read and write functions.'

