# exabgp
# Autogenerated from man page /usr/share/man/man1/exabgp.1.gz
complete -c exabgp -l folder --description 'Specify the directory where the configuration file can be found.'
complete -c exabgp -l env --description 'Specify where the environment configuration file can be found.'
complete -c exabgp -l full-ini --description 'Display the full environment configuration using on stdout using the ini form…'
complete -c exabgp -l diff-ini --description 'Display the non-default environment configuration on stdout using the ini for…'
complete -c exabgp -l full-env --description 'Display the full environment configuration on stdout using the env format.'
complete -c exabgp -l diff-env --description 'Display the non-default configuration on stdout using the env format.'
complete -c exabgp -l debug --description 'Start the python debugger on serious logging on and on reception of the SIGTE…'
complete -c exabgp -l signal --description 'Issue a SIGUSR1 signal to reload the configuration after the specified number…'
complete -c exabgp -l once --description 'Only perform one attempt to connect to peers, used mostly for debugging.'
complete -c exabgp -l pdb --description 'Start the python debugger on critical logging, reception of SIGTERM, and on u…'
complete -c exabgp -l memory --description 'Display memory usage information on program exit.'
complete -c exabgp -l profile --description 'Enable collection of profiling information to the given file.'
complete -c exabgp -l test --description 'Only do a configuration validity check.'
complete -c exabgp -l decode --description 'Decode a raw route packet in hexadecimal string.'
complete -c exabgp -l help --description 'Display summary of usage and configuration of exabgp.'
complete -c exabgp -l version --description 'Display the exabgp version number and exit.'

