# extract
# Autogenerated from man page /usr/share/man/man1/extract.1.gz
complete -c extract -s b --description 'Display the output in BiBTeX format.'
complete -c extract -s g --description 'Use grep-friendly output (all keywords on a single line for each file).'
complete -c extract -s h --description 'Print a brief summary of the options.'
complete -c extract -s i --description 'Run plugins in-process (for debugging).'
complete -c extract -s l --description 'Use the specified libraries to extract keywords.'
complete -c extract -s L --description 'Print a list of all known keyword types.'
complete -c extract -s m --description 'Load the file into memory and perform extraction from memory (for debugging).'
complete -c extract -s n --description 'Do not use the default set of extractors (typically all standard extractors, …'
complete -c extract -s p --description 'Print only the keywords matching the specified type.'
complete -c extract -s v --description 'Print the version number and exit.'
complete -c extract -s V --description 'Be verbose.'
complete -c extract -s x --description 'Exclude keywords of the specified type from the output.'

