# extraclangtools
# Autogenerated from man page /usr/share/man/man1/extraclangtools.1.gz
complete -c extraclangtools -s p --description '.'
complete -c extraclangtools -o prefix --description 'Prepend the given path to non-absolute file paths in the header list file.'
complete -c extraclangtools -o module-map-path --description 'Generate a module map and output it to the given file.'
complete -c extraclangtools -o problem-files-list --description 'For use only with module map assistant.'
complete -c extraclangtools -o root-module --description 'Put modules generated by the -module-map-path option in an enclosing module w…'
complete -c extraclangtools -o block-check-header-list-only --description 'Limit the #include-inside-extern-or-namespace-block check to only those heade…'
complete -c extraclangtools -o no-coverage-check --description 'Don\'t do the coverage check for a module map.'
complete -c extraclangtools -o coverage-check-only --description 'Only do the coverage check for a module map.'
complete -c extraclangtools -o display-file-lists --description 'Display lists of good files (no compile errors), problem files, and a combine…'
complete -c extraclangtools -o callbacks --description 'This option specifies a comma-separated list of globs describing the list of …'
complete -c extraclangtools -o output --description 'By default, pp-trace outputs the trace information to stdout.'
complete -c extraclangtools -l - --description '.'
complete -c extraclangtools -o qualified-name --description '$ clang-rename -offset=42 -new-name=bar1 -offset=150 -new-name=bar2 test.'

