# fbsetroot
# Autogenerated from man page /usr/share/man/man1/fbsetroot.1.gz
complete -c fbsetroot -o solid --description 'Sets the root window to specified color.'
complete -c fbsetroot -o mod --description 'Creates a modula pattern.  You must specify -bg and -fg colors.'
complete -c fbsetroot -o display --description 'Tells fbsetroot to connect to the specified display.'
complete -c fbsetroot -o bg -o background --description 'Background color.  Needed for -mod patterns.'
complete -c fbsetroot -o fg -o foreground --description 'Foreground color.  Needed for -mod patterns.'
complete -c fbsetroot -o from --description 'Start color for rendering textures.  Needed for -gradient patterns.'
complete -c fbsetroot -o to --description 'Ending color for rendering textures.  Needed for -gradient patterns.'
complete -c fbsetroot -o help --description 'Prints version info and short help text.'
complete -c fbsetroot -o gradient --description '.'

