# fftwf-wisdom
# Autogenerated from man page /usr/share/man/man1/fftwf-wisdom.1.gz
complete -c fftwf-wisdom -s h -l help --description 'Display help on the command-line options and usage.'
complete -c fftwf-wisdom -s V -l version --description 'Print the version number and copyright information.'
complete -c fftwf-wisdom -s v -l verbose --description 'Verbose output.'
complete -c fftwf-wisdom -s c -l canonical --description 'Optimize/pre-plan a canonical set of sizes: all powers of two and ten up to 2…'
complete -c fftwf-wisdom -s t -l time-limit --description 'Stop after a time of  hours (hours) has elapsed, outputting accumulated wisdo…'
complete -c fftwf-wisdom -s o -l output-file --description 'Send wisdom output to  file rather than to standard output (the default).'
complete -c fftwf-wisdom -s m -l 'measure;' -s e -l 'estimate;' -s x -l exhaustive --description 'Normally,   fftwf-wisdom creates plans in FFTW_PATIENT mode, but with these o…'
complete -c fftwf-wisdom -s n -l no-system-wisdom --description 'Do not import the system wisdom from  /etc/fftw/wisdomf (which is normally re…'
complete -c fftwf-wisdom -s w -l wisdom-file --description 'Import wisdom from  file (in addition to the system wisdom, unless   -n is sp…'
complete -c fftwf-wisdom -s T -l threads --description 'Plan with N threads.'

