# filesnarf
# Autogenerated from man page /usr/share/man/man8/filesnarf.8.gz
complete -c filesnarf -s i --description 'Specify the interface to listen on.'
complete -c filesnarf -s p --description 'Process packets from the specified PCAP capture file instead of the network.'
complete -c filesnarf -s v --description '"Versus" mode.  Invert the sense of matching, to select non-matching files.'

