# finger
# Autogenerated from man page /usr/share/man/man1/finger.1.gz
complete -c finger -s s --description 'finger Finger displays the user\'s login name, real name, terminal name and wr…'
complete -c finger -s l --description 'Produces a multi-line format displaying all of the information described for …'
complete -c finger -s p --description 'Prevents the l option of finger finger from displaying the contents of the .'
complete -c finger -s m --description 'Prevent matching of user names.'

