# fixincludes
# Autogenerated from man page /usr/share/man/man1/fixincludes.1.gz
complete -c fixincludes -s v -l verbose --description 'Verbose mode.  Additional debugging output is written to standard output.'
complete -c fixincludes -s e -l experimental --description 'Experimental mode, as described above in detail.'
complete -c fixincludes -s m -l modify --description 'As well as writing messages to standard output, actually modify the original …'
complete -c fixincludes -o UQT_NO_COMPAT --description 'or.'
complete -c fixincludes -o UKDE_NO_COMPAT --description 'This utility is part of the KDE Software Development Kit.  OPTIONS.'

