# flow6
# Autogenerated from man page /usr/share/man/man1/flow6.1.gz
complete -c flow6 -s i -l interface --description 'This option specifies the network interface that the tool will use.'
complete -c flow6 -s s -l src-address --description 'This option specifies the IPv6 source address (or IPv6 prefix) to be used for…'
complete -c flow6 -s d -l dst-address --description 'This option specifies the IPv6 Destination Address of the target node.'
complete -c flow6 -s A -l hop-limit --description 'This option specifies the Hop Limit to be used for the IPv6 packets.'
complete -c flow6 -s S -l src-link-address --description 'This option specifies the link-layer Source Address of the probe packets (cur…'
complete -c flow6 -s D -l dst-link-address --description 'This option specifies the link-layer Destination Address of the probe packets…'
complete -c flow6 -s P -l protocol --description 'This option specifies the protocol type of the probe packets.'
complete -c flow6 -s p -l dst-port --description 'This option specifies the Destination Port of the probe packets.'
complete -c flow6 -s W -l flow-label-policy --description 'This option instructs the tool to determine the Flow Label generation policy.'
complete -c flow6 -o 'v\\' -l verbose --description 'This option instructs the flow6 tool to be verbose.'
complete -c flow6 -s v --description '.'
complete -c flow6 -s h -l help --description '.'

