# flowtop
# Autogenerated from man page /usr/share/man/man8/flowtop.8.gz
complete -c flowtop -s 4 -l ipv4 --description 'Display IPv4 flows.'
complete -c flowtop -s 6 -l ipv6 --description 'Display IPv6 flows.'
complete -c flowtop -s T -l tcp --description 'Display TCP flows.'
complete -c flowtop -s U -l udp --description 'Display UDP and UDP-lite flows.'
complete -c flowtop -s D -l dccp --description 'Display DCCP flows.'
complete -c flowtop -s I -l icmp --description 'Display ICMP version 4 and version 6 flows.'
complete -c flowtop -s S -l sctp --description 'Display SCTP flows.'
complete -c flowtop -s n -l no-dns --description 'Don\'t perform hostname lookup.'
complete -c flowtop -s G -l no-geoip --description 'Don\'t perform GeoIP lookup.'
complete -c flowtop -s s -l show-src --description 'Also show source information of the flow, not only destination information.'
complete -c flowtop -s b -l bits --description 'Show flow rates in bits per second instead of bytes per second.'
complete -c flowtop -s u -l update --description 'The built-in database update mechanism will be invoked to get Maxmind\'s lates…'
complete -c flowtop -s t -l interval --description 'Flow info refresh interval in seconds, default is 1s.'
complete -c flowtop -s v -l version --description 'Show version information and exit.'
complete -c flowtop -s h -l help --description 'Show user help and exit.'

