# fluxion
# Autogenerated from man page /usr/share/man/man1/fluxion.1.gz
complete -c fluxion -s v --description 'Print version number.'
complete -c fluxion -l help --description 'Print help page and exit with 0.'
complete -c fluxion -s m --description 'Run fluxion in manual mode instead of auto mode.'
complete -c fluxion -s k --description 'Kill wireless connection if it is connected.'
complete -c fluxion -s d --description 'Run fluxion in debug mode.'
complete -c fluxion -s x --description 'Try to run fluxion with xterm terminals instead of tmux.'
complete -c fluxion -s r --description 'Reload driver.'
complete -c fluxion -s l --description 'Define a certain language.'
complete -c fluxion -s e --description 'Select the target network based on the ESSID.'
complete -c fluxion -s c --description 'Indicate the channel(s) to listen to.'
complete -c fluxion -s a --description 'Define a certain attack.'
complete -c fluxion -l ratio --description 'Define the windows size.  Bigger ratio -> smaller window size.  Default is 4.'
complete -c fluxion -s b --description 'Select the target network based on the access point MAC address.'
complete -c fluxion -s j --description 'Define a certain jamming interface.'

