# foremost
# Autogenerated from man page /usr/share/man/man8/foremost.8.gz
complete -c foremost -s h --description 'Show a help screen and exit.'
complete -c foremost -s V --description 'Show copyright information and exit.'
complete -c foremost -s d --description 'Turn on indirect block detection, this works well for Unix file systems.'
complete -c foremost -s T --description 'Time stamp the output directory so you don\'t have to delete the output dir wh…'
complete -c foremost -s v --description 'Enables verbose mode.'
complete -c foremost -s q --description 'Enables quick mode.'
complete -c foremost -s Q --description 'Enables Quiet mode.  Most error messages will be suppressed. br.'
complete -c foremost -s w --description 'Enables write audit only mode.   No files will be extracted. br.'
complete -c foremost -s a --description 'Enables write all headers, perform no error detection in terms of corrupted f…'
complete -c foremost -s b --description 'Allows you to specify the block size used in foremost.'
complete -c foremost -s k --description 'Allows you to specify the chunk size used in foremost.'
complete -c foremost -s i --description 'The file is used as the input file.'
complete -c foremost -s o --description 'Recovered files are written to the directory directory.'
complete -c foremost -s c --description 'Sets the configuration file to use.'
complete -c foremost -s s --description 'Skips number blocks in the input file before beginning the search for headers.'

