# fpdns
# Autogenerated from man page /usr/share/man/man1/fpdns.1p.gz
complete -c fpdns -s d --description 'Enable debugging.  Off by default.'
complete -c fpdns -s D --description 'Check all authoritative servers of the specified domain name.'
complete -c fpdns -s f --description 'Force checking of \\s-1CH TXT\\s0 version.  Off by default.'
complete -c fpdns -s F --description 'Maximum number of forked child processes.  Defaults to 10.'
complete -c fpdns -s p --description 'Port to query remote nameserver on.  Default is 53.'
complete -c fpdns -s Q --description 'Set the source \\s-1IP\\s0 address to use.'
complete -c fpdns -s r --description 'Number of attempt to retry fingerprints.  Defaults to 1.'
complete -c fpdns -s s --description 'Short display form.  Useful for surveys.'
complete -c fpdns -s S --description 'Separator.  Defaults to \\*(L" \\*(R".'
complete -c fpdns -s t --description 'Set the query timeout in seconds.  Defaults to 5.'
complete -c fpdns -s T --description 'Use \\s-1TCP\\s0 instead of \\s-1UDP. \\s0.'
complete -c fpdns -s v --description 'Show version of fpdns.'

