# ft2nfdump
# Autogenerated from man page /usr/share/man/man1/ft2nfdump.1.gz
complete -c ft2nfdump -s r --description 'Read flow-tools formated netflow data from file flow-tools-file.'
complete -c ft2nfdump -s c --description 'Read only num flows from input file.'
complete -c ft2nfdump -s E --description 'Print raw netflow records to stdout.'
complete -c ft2nfdump -s V --description 'Print ft2nfdump version and exit.'
complete -c ft2nfdump -s h --description 'Print help text on stdout with all options and exit.'

