# fvdemount
# Autogenerated from man page /usr/share/man/man1/fvdemount.1.gz
complete -c fvdemount -s e --description 'specify the name of the EncryptedRoot. plist. wipekey file.'
complete -c fvdemount -s h --description 'shows this help.'
complete -c fvdemount -s o --description 'specify the volume offset.'
complete -c fvdemount -s p --description 'specify the password.'
complete -c fvdemount -s r --description 'specify the recovery password.'
complete -c fvdemount -s v --description 'verbose output to stderr.'
complete -c fvdemount -s V --description 'print version.'
complete -c fvdemount -s X --description 'extended options to pass to sub system El ENVIRONMENT None FILES None EXAMPLE…'

