# g-ir-generate
# Autogenerated from man page /usr/share/man/man1/g-ir-generate.1.gz
complete -c g-ir-generate -l help --description 'Show help options.'
complete -c g-ir-generate -l shlib --description 'The shared library to read the symbols from.'
complete -c g-ir-generate -l output --description 'Save the resulting output in FILENAME.'
complete -c g-ir-generate -l version --description 'Show program\\(aqs version number and exit.'

