# g-ir-compiler
# Autogenerated from man page /usr/share/man/man1/g-ir-compiler.1.gz
complete -c g-ir-compiler -l help --description 'Show help options.'
complete -c g-ir-compiler -l output --description 'Save the resulting output in FILENAME.'
complete -c g-ir-compiler -l verbose --description 'Show verbose messages.'
complete -c g-ir-compiler -l debug --description 'Show debug messages.'
complete -c g-ir-compiler -l includedir --description 'Adds a directory which will be used to find includes inside the GIR format.'
complete -c g-ir-compiler -l module --description 'FIXME.'
complete -c g-ir-compiler -l shared-library --description 'Specifies the shared library where the symbols in the typelib can be found.'
complete -c g-ir-compiler -l version --description 'Show program\\(aqs version number and exit.'

