# gh-api
# Autogenerated from man page /usr/share/man/man1/gh-api.1.gz
complete -c gh-api -s F -l field --description '	Add a parameter of inferred type.'
complete -c gh-api -s H -l header --description '	Add an additional HTTP request header.'
complete -c gh-api -l hostname --description '	The GitHub hostname for the request (default "github. com").'
complete -c gh-api -s i -l include --description '	Include HTTP response headers in the output.'
complete -c gh-api -l input --description '	The file to use as body for the HTTP request.'
complete -c gh-api -s X -l method --description '	The HTTP method for the request.'
complete -c gh-api -l paginate --description '	Make additional HTTP requests to fetch all pages of results.'
complete -c gh-api -s f -l raw-field --description '	Add a string parameter.'
complete -c gh-api -l silent --description '	Do not print the response body OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-api -l help --description '	Show help for command EXAMPLE $ gh api repos/:owner/:repo/releases.'

