# gh-alias-set
# Autogenerated from man page /usr/share/man/man1/gh-alias-set.1.gz
complete -c gh-alias-set -s s -l shell --description '	Declare an alias to be passed through a shell interpreter OPTIONS INHERITED …'
complete -c gh-alias-set -l help --description '	Show help for command EXAMPLE $ gh alias set pv \'pr view\' $ gh pv -w 123 #=>…'

