# gh-auth-logout
# Autogenerated from man page /usr/share/man/man1/gh-auth-logout.1.gz
complete -c gh-auth-logout -s h -l hostname --description '	The hostname of the GitHub instance to log out of OPTIONS INHERITED FROM PAR…'
complete -c gh-auth-logout -l help --description '	Show help for command EXAMPLE $ gh auth logout # => select what host to log …'

