# gh-completion
# Autogenerated from man page /usr/share/man/man1/gh-completion.1.gz
complete -c gh-completion -s s -l shell --description '	Shell type: {bash|zsh|fish|powershell} OPTIONS INHERITED FROM PARENT COMMAND…'
complete -c gh-completion -l help --description '	Show help for command SEE ALSO.'

