# gh-config-set
# Autogenerated from man page /usr/share/man/man1/gh-config-set.1.gz
complete -c gh-config-set -s h -l host --description '	Set per-host setting OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-config-set -l help --description '	Show help for command EXAMPLE $ gh config set editor vim $ gh config set edi…'

