# gh-gist-list
# Autogenerated from man page /usr/share/man/man1/gh-gist-list.1.gz
complete -c gh-gist-list -s L -l limit --description '	Maximum number of gists to fetch.'
complete -c gh-gist-list -l public --description '	Show only public gists.'
complete -c gh-gist-list -l secret --description '	Show only secret gists OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-gist-list -l help --description '	Show help for command SEE ALSO.'

