# gh-gist-create
# Autogenerated from man page /usr/share/man/man1/gh-gist-create.1.gz
complete -c gh-gist-create -s d -l desc --description '	A description for this gist.'
complete -c gh-gist-create -s f -l filename --description '	Provide a filename to be used when reading from STDIN.'
complete -c gh-gist-create -s p -l public --description '	List the gist publicly (default: private).'
complete -c gh-gist-create -s w -l web --description '	Open the web browser with created gist OPTIONS INHERITED FROM PARENT COMMAND…'
complete -c gh-gist-create -l help --description '	Show help for command EXAMPLE # publish file \'hello.'

