# gh-issue-view
# Autogenerated from man page /usr/share/man/man1/gh-issue-view.1.gz
complete -c gh-issue-view -s c -l comments --description '	View issue comments.'
complete -c gh-issue-view -s w -l web --description '	Open an issue in the browser OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-issue-view -l help --description '	Show help for command.'
complete -c gh-issue-view -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO.'

