# gh-issue-create
# Autogenerated from man page /usr/share/man/man1/gh-issue-create.1.gz
complete -c gh-issue-create -s a -l assignee --description '	Assign people by their login.'
complete -c gh-issue-create -s b -l body --description '	Supply a body.  Will prompt for one otherwise.'
complete -c gh-issue-create -s l -l label --description '	Add labels by name.'
complete -c gh-issue-create -s m -l milestone --description '	Add the issue to a milestone by name.'
complete -c gh-issue-create -s p -l project --description '	Add the issue to projects by name.'
complete -c gh-issue-create -l recover --description '	Recover input from a failed run of create.'
complete -c gh-issue-create -s t -l title --description '	Supply a title.  Will prompt for one otherwise.'
complete -c gh-issue-create -s w -l web --description '	Open the browser to create an issue OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-issue-create -l help --description '	Show help for command.'
complete -c gh-issue-create -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh is…'

