# gh-issue-list
# Autogenerated from man page /usr/share/man/man1/gh-issue-list.1.gz
complete -c gh-issue-list -s a -l assignee --description '	Filter by assignee.'
complete -c gh-issue-list -s A -l author --description '	Filter by author.'
complete -c gh-issue-list -s l -l label --description '	Filter by labels.'
complete -c gh-issue-list -s L -l limit --description '	Maximum number of issues to fetch.'
complete -c gh-issue-list -l mention --description '	Filter by mention.'
complete -c gh-issue-list -s m -l milestone --description '	Filter by milestone number or title.'
complete -c gh-issue-list -s s -l state --description '	Filter by state: {open|closed|all}.'
complete -c gh-issue-list -s w -l web --description '	Open the browser to list the issue(s) OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-issue-list -l help --description '	Show help for command.'
complete -c gh-issue-list -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh is…'

