# gh-issue-close
# Autogenerated from man page /usr/share/man/man1/gh-issue-close.1.gz
complete -c gh-issue-close -l help --description '	Show help for command.'
complete -c gh-issue-close -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO.'

