# gh-pr-merge
# Autogenerated from man page /usr/share/man/man1/gh-pr-merge.1.gz
complete -c gh-pr-merge -s d -l delete-branch --description '	Delete the local and remote branch after merge.'
complete -c gh-pr-merge -s m -l merge --description '	Merge the commits with the base branch.'
complete -c gh-pr-merge -s r -l rebase --description '	Rebase the commits onto the base branch.'
complete -c gh-pr-merge -s s -l squash --description '	Squash the commits into one commit and merge it into the base branch OPTIONS…'
complete -c gh-pr-merge -l help --description '	Show help for command.'
complete -c gh-pr-merge -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO.'

