# gh-pr-reopen
# Autogenerated from man page /usr/share/man/man1/gh-pr-reopen.1.gz
complete -c gh-pr-reopen -l help --description '	Show help for command.'
complete -c gh-pr-reopen -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO.'

