# gh-pr-review
# Autogenerated from man page /usr/share/man/man1/gh-pr-review.1.gz
complete -c gh-pr-review -s a -l approve --description '	Approve pull request.'
complete -c gh-pr-review -s b -l body --description '	Specify the body of a review.'
complete -c gh-pr-review -s c -l comment --description '	Comment on a pull request.'
complete -c gh-pr-review -s r -l request-changes --description '	Request changes on a pull request OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-pr-review -l help --description '	Show help for command.'
complete -c gh-pr-review -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # appro…'

