# gh-pr-checkout
# Autogenerated from man page /usr/share/man/man1/gh-pr-checkout.1.gz
complete -c gh-pr-checkout -l recurse-submodules --description '	Update all active submodules (recursively) OPTIONS INHERITED FROM PARENT COM…'
complete -c gh-pr-checkout -l help --description '	Show help for command.'
complete -c gh-pr-checkout -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO.'

