# gh-pr-create
# Autogenerated from man page /usr/share/man/man1/gh-pr-create.1.gz
complete -c gh-pr-create -s a -l assignee --description '	Assign people by their login.'
complete -c gh-pr-create -s B -l base --description '	The branch into which you want your code merged.'
complete -c gh-pr-create -s b -l body --description '	Body for the pull request.'
complete -c gh-pr-create -s d -l draft --description '	Mark pull request as a draft.'
complete -c gh-pr-create -s f -l fill --description '	Do not prompt for title/body and just use commit info.'
complete -c gh-pr-create -s H -l head --description '	The branch that contains commits for your pull request (default: current bra…'
complete -c gh-pr-create -s l -l label --description '	Add labels by name.'
complete -c gh-pr-create -s m -l milestone --description '	Add the pull request to a milestone by name.'
complete -c gh-pr-create -s p -l project --description '	Add the pull request to projects by name.'
complete -c gh-pr-create -l recover --description '	Recover input from a failed run of create.'
complete -c gh-pr-create -s r -l reviewer --description '	Request reviews from people or teams by their handle.'
complete -c gh-pr-create -s t -l title --description '	Title for the pull request.'
complete -c gh-pr-create -s w -l web --description '	Open the web browser to create a pull request OPTIONS INHERITED FROM PARENT …'
complete -c gh-pr-create -l help --description '	Show help for command.'
complete -c gh-pr-create -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh pr…'

