# gh-pr-checks
# Autogenerated from man page /usr/share/man/man1/gh-pr-checks.1.gz
complete -c gh-pr-checks -s w -l web --description '	Open the web browser to show details about checks OPTIONS INHERITED FROM PAR…'
complete -c gh-pr-checks -l help --description '	Show help for command.'
complete -c gh-pr-checks -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO.'

