# gh-release-create
# Autogenerated from man page /usr/share/man/man1/gh-release-create.1.gz
complete -c gh-release-create -s d -l draft --description '	Save the release as a draft instead of publishing it.'
complete -c gh-release-create -s n -l notes --description '	Release notes.'
complete -c gh-release-create -s F -l notes-file --description '	Read release notes from file.'
complete -c gh-release-create -s p -l prerelease --description '	Mark the release as a prerelease.'
complete -c gh-release-create -l target --description '	Target branch or commit SHA (default: main branch).'
complete -c gh-release-create -s t -l title --description '	Release title OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-release-create -l help --description '	Show help for command.'
complete -c gh-release-create -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # use r…'

