# gh-release-download
# Autogenerated from man page /usr/share/man/man1/gh-release-download.1.gz
complete -c gh-release-download -s D -l dir --description '	The directory to download files into.'
complete -c gh-release-download -s p -l pattern --description '	Download only assets that match a glob pattern OPTIONS INHERITED FROM PARENT…'
complete -c gh-release-download -l help --description '	Show help for command.'
complete -c gh-release-download -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # downl…'

