# gh-release-delete
# Autogenerated from man page /usr/share/man/man1/gh-release-delete.1.gz
complete -c gh-release-delete -s y -l yes --description '	Skip the confirmation prompt OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-release-delete -l help --description '	Show help for command.'
complete -c gh-release-delete -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO.'

