# gh-repo-create
# Autogenerated from man page /usr/share/man/man1/gh-repo-create.1.gz
complete -c gh-repo-create -s y -l confirm --description '	Confirm the submission directly.'
complete -c gh-repo-create -s d -l description --description '	Description of repository.'
complete -c gh-repo-create -l enable-issues --description '	Enable issues in the new repository.'
complete -c gh-repo-create -l enable-wiki --description '	Enable wiki in the new repository.'
complete -c gh-repo-create -s h -l homepage --description '	Repository home page URL.'
complete -c gh-repo-create -l internal --description '	Make the new repository internal.'
complete -c gh-repo-create -l private --description '	Make the new repository private.'
complete -c gh-repo-create -l public --description '	Make the new repository public.'
complete -c gh-repo-create -s t -l team --description '	The name of the organization team to be granted access.'
complete -c gh-repo-create -s p -l template --description '	Make the new repository based on a template repository OPTIONS INHERITED FRO…'
complete -c gh-repo-create -l help --description '	Show help for command EXAMPLE # create a repository under your account using…'

