# gh-secret
# Autogenerated from man page /usr/share/man/man1/gh-secret.1.gz
complete -c gh-secret -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format OPTIONS INHERIT…'
complete -c gh-secret -l help --description '	Show help for command SEE ALSO.'

