# gh-secret-set
# Autogenerated from man page /usr/share/man/man1/gh-secret-set.1.gz
complete -c gh-secret-set -s b -l body --description '	A value for the secret.  Reads from STDIN if not specified.'
complete -c gh-secret-set -s o -l org --description '	List secrets for an organization.'
complete -c gh-secret-set -s r -l repos --description '	List of repository names for selected visibility.'
complete -c gh-secret-set -s v -l visibility --description '	Set visibility for an organization secret: all, private, or selected OPTIONS…'
complete -c gh-secret-set -l help --description '	Show help for command.'
complete -c gh-secret-set -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh se…'

