# gh-secret-remove
# Autogenerated from man page /usr/share/man/man1/gh-secret-remove.1.gz
complete -c gh-secret-remove -s o -l org --description '	List secrets for an organization OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-secret-remove -l help --description '	Show help for command.'
complete -c gh-secret-remove -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO.'

