# gh
# Autogenerated from man page /usr/share/man/man1/gh.1.gz
complete -c gh -l help --description '	Show help for command.'
complete -c gh -l version --description '	Show gh version EXAMPLE $ gh issue create $ gh repo clone cli/cli $ gh pr ch…'

