# gif2swf
# Autogenerated from man page /usr/share/man/man1/gif2swf.1.gz
complete -c gif2swf -s r -l rate --description 'Set movie framerate (frames per second).'
complete -c gif2swf -s o -l output --description 'Explicitly specify output file.'
complete -c gif2swf -s z -l zlib --description 'Use Flash MX (SWF 6) Zlib encoding for the output.'
complete -c gif2swf -s l -l loop --description 'Set loop count.  (default: 0 [=infinite loop]).'
complete -c gif2swf -s X -l pixel --description 'Force movie width to width (default: autodetect).'
complete -c gif2swf -s Y --description 'Force movie height to height (default: autodetect).'
complete -c gif2swf -s v -l verbose --description 'Set verbose level (0=quiet, 1=default, 2=debug).'
complete -c gif2swf -s C -l cgi --description 'For use as CGI- prepend http header, write to stdout.'
complete -c gif2swf -s V -l version --description '    Print version information and exit.'

