# gifwedge
# Autogenerated from man page /usr/share/man/man1/gifwedge.1.gz
complete -c gifwedge -s v --description 'Verbose mode (show progress).  Enables printout of running scan lines.'
complete -c gifwedge -s l --description 'Set number of intensity levels per color.'
complete -c gifwedge -s s --description 'Force image size to be SizeX by SizeY pixels.'
complete -c gifwedge -s h --description 'Print one line command line help, similar to Usage above.'

