# gps2udp
# Autogenerated from man page /usr/share/man/man1/gps2udp.1.gz
complete -c gps2udp -s h --description 'gps2udp print a usage message and exit.'
complete -c gps2udp -s n --description '.'
complete -c gps2udp -s j --description '.'
complete -c gps2udp -s u --description '.'
complete -c gps2udp -s a --description '.'
complete -c gps2udp -s b --description 'gps2udp to run as a daemon.'
complete -c gps2udp -s c --description 'gps2udp will then exit gracefully.'
complete -c gps2udp -s d --description '.'
complete -c gps2udp -s v --description 'EXAMPLE.'

