# gpsd
# Autogenerated from man page /usr/share/man/man8/gpsd.8.gz
complete -c gpsd -s b --description '.'
complete -c gpsd -s D --description '.'
complete -c gpsd -s F --description '.'
complete -c gpsd -s f --description '.'
complete -c gpsd -s G --description '.'
complete -c gpsd -s h --description '.'
complete -c gpsd -s l --description '.'
complete -c gpsd -s n --description '.'
complete -c gpsd -s N --description '.'
complete -c gpsd -s r --description '.'
complete -c gpsd -s P --description '.'
complete -c gpsd -s S --description '.'
complete -c gpsd -s s --description '.'
complete -c gpsd -s V --description '.'

