# gpsinit
# Autogenerated from man page /usr/share/man/man8/gpsinit.8.gz
complete -c gpsinit -s h --description '.'
complete -c gpsinit -s v --description '.'
complete -c gpsinit -s n --description '.'
complete -c gpsinit -s s --description '.'

