# gpsrinex
# Autogenerated from man page /usr/share/man/man1/gpsrinex.1.gz
complete -c gpsrinex -s D --description '.'
complete -c gpsrinex -s f --description '.'
complete -c gpsrinex -s h --description 'gpsrinex print a usage message and exit.'
complete -c gpsrinex -s i --description '.'
complete -c gpsrinex -s n --description '.'
complete -c gpsrinex -s V --description 'gpsrinex print its version and exit.  EXAMPLES.'

