# greenbone-certdata-sync
# Autogenerated from man page /usr/share/man/man8/greenbone-certdata-sync.8.gz
complete -c greenbone-certdata-sync -l version --description 'Print version and exit.'
complete -c greenbone-certdata-sync -l identify --description 'Print machine readable identity information and exit.'
complete -c greenbone-certdata-sync -l describe --description 'Print human readable description.'
complete -c greenbone-certdata-sync -l feedversion --description 'Print feed version and exit.'
complete -c greenbone-certdata-sync -l help --description 'Print help message and exit.'
complete -c greenbone-certdata-sync -l refresh --description 'Only refresh the database.  Do not fetch any files.'
complete -c greenbone-certdata-sync -l migrate --description 'Only migrate the database.  Do not fetch any files.'
complete -c greenbone-certdata-sync -l selftest --description 'Perform self-test and exit.'
complete -c greenbone-certdata-sync -l feedcurrent --description 'Check whether feed is current.'
complete -c greenbone-certdata-sync -l database --description 'The name of the database.  For Posgres backend only.  Default is tasks.'

