# greenbone-scapdata-sync
# Autogenerated from man page /usr/share/man/man8/greenbone-scapdata-sync.8.gz
complete -c greenbone-scapdata-sync -l version --description 'Print version and exit.'
complete -c greenbone-scapdata-sync -l identify --description 'Print machine readable identity information and exit.'
complete -c greenbone-scapdata-sync -l describe --description 'Print human readable description.'
complete -c greenbone-scapdata-sync -l feedversion --description 'Print feed version and exit.'
complete -c greenbone-scapdata-sync -l help --description 'Print help message and exit.'
complete -c greenbone-scapdata-sync -l verbose --description 'Print exta messages about what\'s going on.'
complete -c greenbone-scapdata-sync -l refresh --description 'Only refresh the database.  Do not fetch any files.'
complete -c greenbone-scapdata-sync -l refresh-private --description 'Only refresh the database.  Do not fetch any files.'
complete -c greenbone-scapdata-sync -l migrate --description 'Only migrate the database.  Do not fetch any files.'
complete -c greenbone-scapdata-sync -l selftest --description 'Perform self-test and exit.'
complete -c greenbone-scapdata-sync -l feedcurrent --description 'Check whether feed is current.'

