# grig
# Autogenerated from man page /usr/share/man/man1/grig.1.gz
complete -c grig -s m -l model --description 'select radio model number; see --list.'
complete -c grig -s r -l rig-file --description 'set device of the radio, eg.  /dev/ttyS0.'
complete -c grig -s s -l speed --description 'set transfer rate (serial port only).'
complete -c grig -s c -l civ-addr --description 'set CI-V address (decimal, ICOM only).'
complete -c grig -s C -l set-conf --description 'set additiional configuration parameters.'
complete -c grig -s d -l debug --description 'set hamlib debug level (0. 5).'
complete -c grig -s D -l delay --description 'set delay between commands in msec (see below).'
complete -c grig -s n -l nothread --description 'use timeout calls instead of thread (see below).'
complete -c grig -s l -l list --description 'list supported radios and exit.'
complete -c grig -s p -l enable-ptt --description 'enable ptt control.'
complete -c grig -s P -l enable-pwr --description 'enable power status control.'
complete -c grig -s h -l help --description 'show a brief help message and exit.'
complete -c grig -s v -l version --description 'show version information and exit.'

