# gsf
# Autogenerated from man page /usr/share/man/man1/gsf.1.gz
complete -c gsf -s '?' -l help --description 'Show help options.'
complete -c gsf -s v -l version --description 'Display gsf\'s version  . SS "Subcommands".'

