# gssproxy
# Autogenerated from man page /usr/share/man/man8/gssproxy.8.gz
complete -c gssproxy -s D -l daemon --description 'Become a daemon after starting up.'
complete -c gssproxy -s c -l config --description 'Specify a config file to use as the main config file (read before the rest of…'
complete -c gssproxy -s C -l configdir --description 'Specify a non-default config dir.  Files named of the form "##-foo.'
complete -c gssproxy -s d -l debug --description 'Turn on debugging.  This option is identical to --debug-level=1.'
complete -c gssproxy -l debug-level --description 'Turn on debugging at the specified level.'
complete -c gssproxy -s i -l interactive --description 'Run in the foreground, don\\*(Aqt become a daemon.'
complete -c gssproxy -s s -l socket --description 'Specify a custom default socket name.'
complete -c gssproxy -l version --description 'Print version number and exit.'

