# gtfoblookup
# Autogenerated from man page /usr/share/man/man1/gtfoblookup.1.gz
complete -c gtfoblookup -s r -l repo --description 'Only update the specified repository.'
complete -c gtfoblookup -s f -l file --description 'use a file containing a list of executables (one per line) instead of a singl…'
complete -c gtfoblookup -s l -l list --description 'list all types/categories/executables featured in the local copy of GTFOBins.'
complete -c gtfoblookup -s t -l type --description 'search for a specific type of executable.'

