# guile2
# Autogenerated from man page /usr/share/man/man1/guile2.0.1.gz
complete -c guile2 -s L --description 'Add DIRECTORY to the front of Guile\'s module load path.'
complete -c guile2 -s l --description 'Load Scheme source code from FILE.'
complete -c guile2 -s e --description 'After reading SCRIPT, apply FUNCTION to command-line arguments.'
complete -c guile2 -s c --description 'Stop argument processing, and evaluate EXPR as a Scheme expression.'
complete -c guile2 -s s --description 'Load Scheme source from SCRIPT-FILE and execute as a script.'
complete -c guile2 -o ds --description 'Carry out -s SCRIPT at this point in the option sequence.'
complete -c guile2 -l debug --description 'Start  guile with the debugging VM.'
complete -c guile2 -l no-debug --description 'Start  guile without the debugging VM, even if  guile is being run interactiv…'
complete -c guile2 -l auto-compile --description 'Compile source files automatically (default behavior).'
complete -c guile2 -l no-auto-compile --description 'Disable automatic source file compilation.'
complete -c guile2 -l listen --description 'Listen on a port or socket for remote REPL connections.'
complete -c guile2 -l use-srfi --description 'Load SRFI extensions N, M, etc.  For example,  --use-srfi=8,13.'
complete -c guile2 -s x --description 'Add EXTENSION to the  guile load extension list.'
complete -c guile2 -s h -l help --description 'Describe command-line options and exit.'
complete -c guile2 -s v -l version --description 'Display guile version and exit.'
complete -c guile2 -s q --description 'In interactive mode, suppress loading the user\'s initialization file, ~/.'

