# gvedit
# Autogenerated from man page /usr/share/man/man1/gvedit.1.gz
complete -c gvedit -s s --description 'By default, the layout algorithms that use initial positions given by a node\'…'
complete -c gvedit -s v --description 'Verbose mode.'
complete -c gvedit -s '?' --description 'Prints usage information and exit.  AUTHOR Arif Bilgin <arif@research. att.'

