# gvm-migrate-to-postgres
# Autogenerated from man page /usr/share/man/man8/gvm-migrate-to-postgres.8.gz
complete -c gvm-migrate-to-postgres -l version --description 'Print version and exit.'
complete -c gvm-migrate-to-postgres -l help --description 'Print help message and exit.'
complete -c gvm-migrate-to-postgres -l selftest --description 'Perform self-test and exit.'

