# haka
# Autogenerated from man page /usr/share/man/man1/haka.1.gz
complete -c haka -s h -l help --description 'Display help.'
complete -c haka -l version --description 'Display version.'
complete -c haka -s c -l config --description 'Load a specific configuration file (default: /opt/haka/etc/haka/haka. conf).'
complete -c haka -s d -l debug --description 'Display debug output.'
complete -c haka -l dump-dissector-graph --description 'Dump dissector internals (grammar and state machine) in file <name>. dot.'
complete -c haka -s l -l loglevel --description 'Change haka logging level.'
complete -c haka -l debug-lua --description 'Attach lua debugger (and keep haka in foreground).'
complete -c haka -l no-daemon --description 'Do no run in the background.'
complete -c haka -s r -l rule --description 'Override the rule configuration file.'
complete -c haka -l opt --description 'Override configuration parameter.'
complete -c haka -l pid-file --description 'Full path to pid file.'
complete -c haka -l ctl-socket --description 'Full path to socket control file.  FILES /var/run/haka.'

