# halberd
# Autogenerated from man page /usr/man/man1/halberd.1.gz
complete -c halberd -l version --description 'show program\'s version number and exit.'
complete -c halberd -s h -l help --description 'show this help message and exit.'
complete -c halberd -s v -l verbose --description 'explain what is being done.'
complete -c halberd -s q -l quiet --description 'run quietly.'
complete -c halberd -s d -l debug --description 'enable debugging information.'
complete -c halberd -s t -l time --description 'time (in seconds) to spend scanning the target.'
complete -c halberd -s p -l parallelism --description 'specify the number of parallel threads to use.'
complete -c halberd -s u -l urlfile --description 'read URLs from FILE.'
complete -c halberd -s o -l out --description 'write report to the specified file.'
complete -c halberd -s a -l address --description 'specify address to scan.'
complete -c halberd -s r -l read --description 'load clues from the specified file.'
complete -c halberd -s w -l write --description 'save clues to the specified directory.'
complete -c halberd -l config --description 'use alternative configuration file.'

