# hearleech
# Autogenerated from man page /usr/share/man/man8/hearleech.8.gz
complete -c hearleech -l autopwn --description '.'
complete -c hearleech -l cert --description '.'
complete -c hearleech -s d --description '.'
complete -c hearleech -l dump --description '.'
complete -c hearleech -l ipver -l ipv6 -l ipv4 --description '.'
complete -c hearleech -l loop --description '.'
complete -c hearleech -l port --description '.'
complete -c hearleech -l proxy --description '.'
complete -c hearleech -l rand --description '.'
complete -c hearleech -l read --description '.'
complete -c hearleech -l raw --description '.'
complete -c hearleech -l scan --description '.'
complete -c hearleech -l scanlist -l threads --description '.'
complete -c hearleech -l timeout --description '.'

