# hivexsh
# Autogenerated from man page /usr/share/man/man1/hivexsh.1.gz
complete -c hivexsh -s d --description 'Enable lots of debug messages.'
complete -c hivexsh -s f --description 'Read commands from \\f(CW\\*(C`filename\\*(C\' instead of stdin.'
complete -c hivexsh -s u --description 'Use heuristics to tolerate certain levels of corruption within hives.'

