# hivexregedit
# Autogenerated from man page /usr/share/man/man1/hivexregedit.1.gz
complete -c hivexregedit -l help --description 'Display help.'
complete -c hivexregedit -l debug --description 'Enable debugging in the hivex library.'
complete -c hivexregedit -l merge --description 'Vb 2  hivexregedit --merge [--prefix prefix] [--encoding enc]           hivef…'
complete -c hivexregedit -l export --description 'Vb 1  hivexregedit --export [--prefix prefix] hivefile key > regfile . Ve .'
complete -c hivexregedit -l prefix --description 'Hive files and Windows Registry key names are indirectly related.'
complete -c hivexregedit -l encoding --description 'When merging (only), you may need to specify the encoding for strings to be u…'
complete -c hivexregedit -l unsafe-printable-strings --description 'When exporting (only), assume strings are \\s-1UTF-16LE\\s0 and print them as s…'
complete -c hivexregedit -l unsafe --description 'Use heuristics to tolerate certain levels of corruption within hives.'

