# honeydctl
# Autogenerated from man page /usr/share/man/man1/honeydctl.1.gz
complete -c honeydctl -s v --description 'Tells honeydctl to output all conversations.'
complete -c honeydctl -s t --description 'Specifies the timeout in seconds when connection to honeydctl Honeyd.'

