# hostapd_cli
# Autogenerated from man page /usr/share/man/man1/hostapd_cli.1.gz
complete -c hostapd_cli -o 'p<path>' --description 'Path to find control sockets.   Default: /var/run/hostapd.'
complete -c hostapd_cli -o 'i<ifname>' --description 'Interface to listen on.   Default: first interface found in socket path.'
complete -c hostapd_cli -o 'a<path>' --description 'Run in daemon mode executing the action file based on events from hostapd.'
complete -c hostapd_cli -s B --description 'Run a daemon in the background.'
complete -c hostapd_cli -s h --description 'Show usage.'
complete -c hostapd_cli -s v --description 'Show hostapd_cli version.  COMMANDS A summary of commands is included below.'

