# hts
# Autogenerated from man page /usr/share/man/man1/hts.1.gz
complete -c hts -s h -l help --description 'Show summary of options.'
complete -c hts -s c -l content-length --description 'use HTTP PUT requests of BYTES size (k, M, and G postfixes recognized).'
complete -c hts -s d -l device --description 'use DEVICE for input and output.'
complete -c hts -s F -l forward-port --description 'connect to PORT at HOST and use it for input and output.'
complete -c hts -s k -l keep-alive --description 'send keepalive bytes every SECONDS seconds (default is 5).'
complete -c hts -s M -l max-connection-age --description 'maximum time a connection will stay open is SEC seconds (default is 300).'
complete -c hts -s S -l strict-content-length --description 'always write Content-Length bytes in requests.'
complete -c hts -s V -l version --description 'output version information and exit.'
complete -c hts -s p -l pid-file --description 'write a PID file to LOCATION AUTHOR This manual page was contributed by Teemu…'

