# hub-api
# Autogenerated from man page /usr/share/man/man1/hub-api.1.gz
complete -c hub-api -s X -l method --description 'The HTTP method to use for the request (default: "GET").'
complete -c hub-api -s F -l field --description 'Data to serialize with the request.'
complete -c hub-api -s f -l raw-field --description 'Same as \\fC--field, except that it allows values starting with "@", literal s…'
complete -c hub-api -l input --description 'The filename to read the raw request body from.'
complete -c hub-api -s H -l header --description 'Set an HTTP request header.'
complete -c hub-api -s i -l include --description 'Include HTTP response headers in the output.'
complete -c hub-api -s t -l flat --description 'Parse response JSON and output the data in a line-based key-value format suit…'
complete -c hub-api -l paginate --description 'Automatically request and output the next page of results until all resources…'
complete -c hub-api -l color --description 'Enable colored output even if stdout is not a terminal.'
complete -c hub-api -l cache --description 'Cache valid responses to GET requests for TTL seconds.'
complete -c hub-api -l obey-ratelimit --description 'After exceeding the API rate limit, pause the process until the reset time of…'

