# hub-create
# Autogenerated from man page /usr/share/man/man1/hub-create.1.gz
complete -c hub-create -s p -l private --description 'Create a private repository.'
complete -c hub-create -s d -l description --description 'A short description of the GitHub repository.'
complete -c hub-create -s h -l homepage --description 'A URL with more information about the repository.'
complete -c hub-create -l remote-name --description 'Set the name for the new git remote (default: "origin").'
complete -c hub-create -s o -l browse --description 'Open the new repository in a web browser.'
complete -c hub-create -s c -l copy --description 'Put the URL of the new repository to clipboard instead of printing it.'

