# hub-release
# Autogenerated from man page /usr/share/man/man1/hub-release.1.gz
complete -c hub-release -s d -l include-drafts --description 'List drafts together with published releases.'
complete -c hub-release -s p -l exclude-prereleases --description 'Exclude prereleases from the list.'
complete -c hub-release -s L -l limit --description 'Display only the first LIMIT releases.'
complete -c hub-release -l draft --description 'Create a draft release.'
complete -c hub-release -l prerelease --description 'Create a pre-release.'
complete -c hub-release -s a -l attach --description 'Attach a file as an asset for this release.'
complete -c hub-release -s m -l message --description 'The text up to the first blank line in MESSAGE is treated as the release titl…'
complete -c hub-release -s F -l file --description 'Read the release title and description from FILE.'
complete -c hub-release -s e -l edit --description 'Open the release title and description in a text editor before submitting.'
complete -c hub-release -s o -l browse --description 'Open the new release in a web browser.'
complete -c hub-release -s c -l copy --description 'Put the URL of the new release to clipboard instead of printing it.'
complete -c hub-release -s t -l commitish --description 'A commit SHA or branch name to attach the release to, only used if TAG does n…'
complete -c hub-release -s i -l include --description 'Filter the files in the release to those that match the glob PATTERN.'
complete -c hub-release -s f -l format --description 'Pretty print releases using FORMAT (default: "%T%n").'
complete -c hub-release -l color --description 'Enable colored output even if stdout is not a terminal.'

