# hub-fork
# Autogenerated from man page /usr/share/man/man1/hub-fork.1.gz
complete -c hub-fork -l no-remote --description 'Skip adding a git remote for the fork.'
complete -c hub-fork -l remote-name --description 'Set the name for the new git remote.'
complete -c hub-fork -l org --description 'Fork the repository within this organization.'

