# hub-compare
# Autogenerated from man page /usr/share/man/man1/hub-compare.1.gz
complete -c hub-compare -s u -l url --description 'Print the URL instead of opening it.'
complete -c hub-compare -s c -l copy --description 'Put the URL to clipboard instead of opening it.'
complete -c hub-compare -s b -l base --description 'Base branch to compare against in case no explicit arguments were given.'

