# hub-ci-status
# Autogenerated from man page /usr/share/man/man1/hub-ci-status.1.gz
complete -c hub-ci-status -s v -l verbose --description 'Print detailed report of all status checks and their URLs.'
complete -c hub-ci-status -s f -l format --description 'Pretty print all status checks using FORMAT (implies \\fC--verbose).'
complete -c hub-ci-status -l color --description 'Enable colored output even if stdout is not a terminal.'

