# hub-gist
# Autogenerated from man page /usr/share/man/man1/hub-gist.1.gz
complete -c hub-gist -l public --description 'Make the new gist public (default: false).'
complete -c hub-gist -s o -l browse --description 'Open the new gist in a web browser.'
complete -c hub-gist -s c -l copy --description 'Put the URL of the new gist to clipboard instead of printing it.'

