# hub-browse
# Autogenerated from man page /usr/share/man/man1/hub-browse.1.gz
complete -c hub-browse -s u -l url --description 'Print the URL instead of opening it.'
complete -c hub-browse -s c -l copy --description 'Put the URL in clipboard instead of opening it.'

