# hwloc-gather-topology
# Autogenerated from man page /usr/share/man/man1/hwloc-gather-topology.1.gz
complete -c hwloc-gather-topology -l io --description 'Also gather I/O related files.'
complete -c hwloc-gather-topology -l dmi --description 'Also gather DMI/SMBIOS related files.'
complete -c hwloc-gather-topology -l no-cpuid --description 'Do not gather x86 CPUID dump using hwloc-gather-cpuid.'
complete -c hwloc-gather-topology -s h -l help --description 'Display help message and exit.  DESCRIPTION.'

