# hwloc-patch
# Autogenerated from man page /usr/share/man/man1/hwloc-patch.1.gz
complete -c hwloc-patch -s R -l reverse --description 'Reverse the sense the difference file.'
complete -c hwloc-patch -l version --description 'Report version and exit.'
complete -c hwloc-patch -s h -l help --description 'Display help message and exit.  DESCRIPTION.'

