# hwloc-gather-cpuid
# Autogenerated from man page /usr/share/man/man1/hwloc-gather-cpuid.1.gz
complete -c hwloc-gather-cpuid -s c --description 'Only gather cpuid values for logical processor whose OS/physical index is <id…'
complete -c hwloc-gather-cpuid -s s -l silent --description 'Do not show verbose messages.'
complete -c hwloc-gather-cpuid -s h -l help --description 'Display help message and exit.  DESCRIPTION.'

