# hwloc-compress-dir
# Autogenerated from man page /usr/share/man/man1/hwloc-compress-dir.1.gz
complete -c hwloc-compress-dir -s R -l reverse --description 'Uncompress a previously compressed directory.'
complete -c hwloc-compress-dir -s v -l verbose --description 'Display verbose messages.'
complete -c hwloc-compress-dir -s h -l help --description 'Display help message and exit.  DESCRIPTION.'

