# id3convert
# Autogenerated from man page /usr/share/man/man1/id3convert.1.gz
complete -c id3convert -s 1 -l v1tag --description 'Render only the id3v1 tag.'
complete -c id3convert -s 2 -l v2tag --description 'Render only the id3v2 tag.'
complete -c id3convert -s s -l strip --description 'Strip, rather than render, the tags.'
complete -c id3convert -s p -l padding --description 'Use padding in the tag.'
complete -c id3convert -s h -l help --description 'Display help and exit.'
complete -c id3convert -s v -l version --description 'Display version information and exit.'

