# id3cp
# Autogenerated from man page /usr/share/man/man1/id3cp.1.gz
complete -c id3cp -s 1 -l v1tag --description 'Render only the id3v1 tag.'
complete -c id3cp -s 2 -l v2tag --description 'Render only the id3v2 tag.'
complete -c id3cp -s h -l help --description 'Display help and exit.'
complete -c id3cp -s v -l version --description 'Display version information and exit SEE ALSO id3convert(1), id3info(1), id3v…'

