# id3info
# Autogenerated from man page /usr/share/man/man1/id3info.1.gz
complete -c id3info -s h -l help --description 'Display help and exit.'
complete -c id3info -s v -l version --description 'Display version information and exit SEE ALSO id3convert(1), id3tag(1), id3v2…'

