# idevicebackup
# Autogenerated from man page /usr/share/man/man1/idevicebackup.1.gz
complete -c idevicebackup -s u -l udid --description 'target specific device by UDID.'
complete -c idevicebackup -s d -l debug --description 'enable communication debugging.'
complete -c idevicebackup -s h -l help --description 'prints usage information.'

