# idlj-openjdk8
# Autogenerated from man page /usr/share/man/man1/idlj-openjdk8.1.gz
complete -c idlj-openjdk8 -s d --description 'br This is equivalent to the following line in an IDL file: . sp      .'
complete -c idlj-openjdk8 -o demitAll --description 'br Emit all types, including those found in \\f3#include files.'
complete -c idlj-openjdk8 -o fside --description 'br Defines what bindings to emit.'
complete -c idlj-openjdk8 -s i --description 'br By default, the current directory is scanned for included files.'
complete -c idlj-openjdk8 -o noWarn --description 'br Suppress warning messages.'
complete -c idlj-openjdk8 -o oldImplBase --description 'br Generates skeletons compatible with pre-1. 4 JDK ORBs.'
complete -c idlj-openjdk8 -o pkgPrefix --description 'br Wherever \\f3type is encountered at file scope, prefix the generated Java p…'
complete -c idlj-openjdk8 -o pkgTranslate --description 'br Whenever the module name type is encountered in an identifier, replace it …'
complete -c idlj-openjdk8 -o skeletonName --description 'br Use \\f3xxx%yyy as the pattern for naming the skeleton.'
complete -c idlj-openjdk8 -o td --description 'br Use dir for the output directory instead of the current directory.'
complete -c idlj-openjdk8 -o tieName --description 'br Use \\f3xxx%yyy according to the pattern.'
complete -c idlj-openjdk8 -o nowarn -o verbose --description 'br Displays release information and terminates.'
complete -c idlj-openjdk8 -o version --description '.'

