# ifpps
# Autogenerated from man page /usr/share/man/man8/ifpps.8.gz
complete -c ifpps -s d -l dev --description 'Networking device to fetch statistics from, for example eth0, wlan0.'
complete -c ifpps -s n -l num-cpus --description 'Set maximum number of top hitter CPUs (in terms of time spent in system/user …'
complete -c ifpps -s t -l interval --description 'Statistics refresh interval in milliseconds, default is 1000ms.'
complete -c ifpps -s c -l csv --description 'Output (once) the ncurses data to the terminal as  gnuplot (1)-ready data.'
complete -c ifpps -s l -l loop --description 'Continuously output the terminal data after a refresh interval.'
complete -c ifpps -s m -l median --description 'Show median values across all CPUs for CPU load, interrupts (per interval and…'
complete -c ifpps -s o -l omit-header --description 'Omit printing the CSV header.  This option is only available if -c is given.'
complete -c ifpps -s p -l promisc --description 'Turn on promiscuous mode for the given networking device.'
complete -c ifpps -s P -l percentage --description 'Show percentage of current throughput in relation to theoretical line rate.'
complete -c ifpps -s W -l no-warn --description 'Suppress possible warnings in the ncurses output, e. g.'
complete -c ifpps -s v -l version --description 'Show version information.'
complete -c ifpps -s h -l help --description 'Show user help.'

