# inotifywatch
# Autogenerated from man page /usr/share/man/man1/inotifywatch.1.gz
complete -c inotifywatch -s h -l help --description 'Output some helpful usage information.'
complete -c inotifywatch -s v -l verbose --description 'Output some extra information on standard error during execution.'
complete -c inotifywatch -l fromfile --description 'Read filenames to watch or exclude from a file, one filename per line.'
complete -c inotifywatch -s z -l zero --description 'Output table rows and columns even if all elements are zero.'
complete -c inotifywatch -l exclude --description 'Do not process any events whose filename matches the specified POSIX extended…'
complete -c inotifywatch -l excludei --description 'Do not process any events whose filename matches the specified POSIX extended…'
complete -c inotifywatch -s r -l recursive --description 'Watch all subdirectories of any directories passed as arguments.'
complete -c inotifywatch -s t -l timeout --description 'Listen only for the specified amount of seconds.'
complete -c inotifywatch -s e -l event --description 'Listen for specific event(s) only.'
complete -c inotifywatch -s a -l ascending --description 'Sort output ascending by event counts for the specified event.'
complete -c inotifywatch -s d --description 'options.'
complete -c inotifywatch -l descending --description 'Sort output descending by event counts for the specified event.'

