# intltool-extract
# Autogenerated from man page /usr/share/man/man8/intltool-extract.8.gz
complete -c intltool-extract -l local --description 'PD Creates a subdirectory under current working directory (named "tmp/") and …'
complete -c intltool-extract -l update --description 'PD Writes header file into the same directory the source file is in.'
complete -c intltool-extract -l type --description 'PD Specify the type of source file.  Currently supported types are: .'
complete -c intltool-extract -l version --description 'PD Show version information.'
complete -c intltool-extract -l help --description 'PD Show usage and basic help information.'
complete -c intltool-extract -s l --description '.'
complete -c intltool-extract -s v --description '.'
complete -c intltool-extract -s h --description '.'
complete -c intltool-extract -s q --description '.'
complete -c intltool-extract -l quiet --description '.'

