# iodbc-config
# Autogenerated from man page /usr/share/man/man1/iodbc-config.1.gz
complete -c iodbc-config -l version --description 'Print the currently installed version of iODBC on the standard output.'
complete -c iodbc-config -l cflags --description 'Print the compiler flags that are necessary to compile an iODBC program.'
complete -c iodbc-config -l libs --description 'Print the linker flags that are necessary to link an iODBC program using dyna…'
complete -c iodbc-config -l static-libs --description 'Print the linker flags that are necessary to link an iODBC program using  sta…'
complete -c iodbc-config -l libtool-libs --description 'Print the linker flags that are necessary to link an iODBC program in a libto…'
complete -c iodbc-config -l odbcini --description 'Print the path of the system wide odbc. ini file.'
complete -c iodbc-config -l odbcinstini --description 'Print the path of the system wide odbcinst. ini file.'
complete -c iodbc-config -l prefix --description 'If specified, use PREFIX instead of the installation prefix that iODBC was bu…'
complete -c iodbc-config -l exec-prefix --description 'If specified, use PREFIX instead of the installation exec prefix that iODBC w…'

