# ipdecap
# Autogenerated from man page /usr/share/man/man1/ipdecap.1.gz
complete -c ipdecap -s i -l input --description 'The pcap file to read packets from.'
complete -c ipdecap -s o -l output --description 'The pcap file to write decapsulated packets to.'
complete -c ipdecap -s c -l conf --description 'RS A file with security associations parameters used to decrypt ESP packets, …'
complete -c ipdecap -s v -l verbose --description 'Print more details for each packet processed (encapsulation protocol, sucessf…'
complete -c ipdecap -s V -l version --description 'print version.'
complete -c ipdecap -s l -l list --description 'List supported ESP encryption and authentication algorithms.'

