# ipfixDump
# Autogenerated from man page /usr/share/man/man1/ipfixDump.1.gz
complete -c ipfixDump -l in --description 'Sets the input file name to \\s-1FILE_NAME\\s0.'
complete -c ipfixDump -l out --description 'Sets the output file name to \\s-1FILE_NAME\\s0.'
complete -c ipfixDump -l rfc5610 --description 'Tells ipfixDump to scan the \\s-1IPFIX\\s0 input file for options records that …'
complete -c ipfixDump -l element-file --description 'Loads the \\s-1XML\\s0 file \\s-1FILE_NAME\\s0 and incorporates information eleme…'
complete -c ipfixDump -l yaf --description 'Searches for a file named cert_ipfix.'
complete -c ipfixDump -l templates --description 'Suppresses the printing of records, causing the output to contain only messag…'
complete -c ipfixDump -l data --description 'Suppresses the printing of templates, causing the output to contain only mess…'
complete -c ipfixDump -l stats --description 'Suppresses the printing of all message headers, templates, and records.'
complete -c ipfixDump -l hexdump --description 'For data record elements whose type is octetArray, prints each octet as a 2-d…'
complete -c ipfixDump -l version --description 'Prints version and copyright information to standard error and exits.'

