# ir-keytable
# Autogenerated from man page /usr/share/man/man1/ir-keytable.1.gz
complete -c ir-keytable -s a -l auto-load --description 'Auto-load keymaps, based on a configuration file.  Only works with --sysdev.'
complete -c ir-keytable -s c -l clear --description 'Clears the scancode to keycode mappings.'
complete -c ir-keytable -s D -l delay --description 'Sets the delay before repeating a keystroke.'
complete -c ir-keytable -s k -l set-key --description 'Set scancode to keycode mapping.'
complete -c ir-keytable -s p -l protocol --description 'Comma separated list of kernel protocols or BPF protocol to enable.'
complete -c ir-keytable -s e -l parameter --description 'Comma separated list of parameters for the BPF protocol.'
complete -c ir-keytable -s P -l 'period\\' --description 'Sets the period to repeat a keystroke.'
complete -c ir-keytable -s r -l read --description 'Read and show the current scancode to keycode mapping.'
complete -c ir-keytable -s s -l sysdev --description 'rc device to control, defaults to rc0 if not specified.'
complete -c ir-keytable -s t -l test --description 'test if the rc device is generating events.'
complete -c ir-keytable -s v -l verbose --description 'Enables debug messages.'
complete -c ir-keytable -s w -l write --description 'Reads the protocols and scancode to keycode mapping from the KEYMAP file, and…'
complete -c ir-keytable -s '?' -l help --description 'Prints the help message.'
complete -c ir-keytable -l usage --description 'Give a short usage message.'
complete -c ir-keytable -s V -l version --description 'print the v4l2-utils version .'
complete -c ir-keytable -l period --description 'Sets the period to repeat a keystroke.'

