# irobex_palm3
# Autogenerated from man page /usr/share/man/man1/irobex_palm3.1.gz
complete -c irobex_palm3 -s h --description 'Choose a creator ID, e. g.  "memo", "addr", "todo", "date" or "Inch".'

