# iscsi-inq
# Autogenerated from man page /usr/share/man/man1/iscsi-inq.1.gz
complete -c iscsi-inq -s i -l initiator-name --description 'This specifies the initiator-name that iscsi-inq will use when logging in to …'
complete -c iscsi-inq -s e -l evpd --description 'By default iscsi-inq will display the standard inquiry data.'
complete -c iscsi-inq -s c -l pagecode --description 'This argument specifies which VPD page to display when evpd is requested.'
complete -c iscsi-inq -s d -l debug --description 'Debug level.'
complete -c iscsi-inq -s '?' -l help --description 'Display basic help text.'
complete -c iscsi-inq -l usage --description 'Display basic usage text.'

