# iscsi-test-cu
# Autogenerated from man page /usr/share/man/man1/iscsi-test-cu.1.gz
complete -c iscsi-test-cu -s i -l initiator-name --description 'All tests use at least one iSCSI connection to the target and this is the ini…'
complete -c iscsi-test-cu -s I -l initiator-name-2 --description 'Some tests use a second connection to the target, such as the \\*(Aqit nexus l…'
complete -c iscsi-test-cu -s l -l list --description 'This argument lists all available tests.'
complete -c iscsi-test-cu -s t -l test --description 'This argument specifies a comma-separated list of the test expressions to run.'
complete -c iscsi-test-cu -s d -l dataloss --description 'By default the test tool will only run non-destructive tests.'
complete -c iscsi-test-cu -s s -l allow-sanitize --description 'The SBC SANITIZE opcode is expected to take significant time before it comple…'
complete -c iscsi-test-cu -s V -l Verbose-scsi --description 'The tests aims to be self-documenting.'
complete -c iscsi-test-cu -s x -l xml --description 'This option to produce test results in machine readable format for automated …'
complete -c iscsi-test-cu -s '?' -l help --description 'Display basic help text.'
complete -c iscsi-test-cu -l - --description '+++ b/cunit-to-junit. pl @@ -226,4 +226,4 @@ foreach my $s (@suites)  }.'

