# isnsdd
# Autogenerated from man page /usr/share/man/man8/isnsdd.8.gz
complete -c isnsdd -l config -s c --description 'This option overrides the default configuration file.'
complete -c isnsdd -l foreground -s f --description 'By default,  isnsd will put itself into the background.'
complete -c isnsdd -l role --description 'This tells the discovery daemon in which capacity is should register itself w…'
complete -c isnsdd -l debug -s d --description 'enables debugging.'

