# isnsadm
# Autogenerated from man page /usr/share/man/man8/isnsadm.8.gz
complete -c isnsadm -l config -s c --description 'This option overrides the default configuration file.'
complete -c isnsadm -l debug -s d --description 'enables debugging.  Valid facilities are . PP . TS tab(,),box,center; lb|lr.'
complete -c isnsadm -l local --description 'makes  isnsadm use a Local (aka Unix) socket when talking to the iSNS server.'
complete -c isnsadm -l server -s s --description 'specifies the server to use (if not specified in the configuration file).'
complete -c isnsadm -l control --description 'makes  isnsadm assume the identity of a control node.'
complete -c isnsadm -l key --description 'This option is recognized in registration mode only, and lets you specify an …'
complete -c isnsadm -l keyfile --description 'When creating a policy for a new iSNS client,   isnsadm is able to generate a…'
complete -c isnsadm -l help --description 'This will print a help message and exit. \\"--------------------------- .'
complete -c isnsadm -l edit-policy --description 'it is acceptable to use node-type as shorthand for policy-node-type .'
complete -c isnsadm -l register --description 'option, followed by a list of one or more objects to register with the iSNS s…'
complete -c isnsadm -l replace --description 'Normally, registration mode will add new objects to the network entity associ…'
complete -c isnsadm -l query --description 'option.  A query consists of a list of  attr =  value pairs.'
complete -c isnsadm -l enroll --description 'option, followed by the (source) name of the client to enroll.'

