# isnsd
# Autogenerated from man page /usr/share/man/man8/isnsd.8.gz
complete -c isnsd -l config -s c --description 'This option overrides the default configuration file.'
complete -c isnsd -l foreground -s f --description 'By default,  isnsd will put itself into the background.'
complete -c isnsd -s 4 --description 'tells  isnsd to create an IPv4 socket only.'
complete -c isnsd -s 6 --description 'tells  isnsd explicitly to create an IPv6 socket only.'
complete -c isnsd -l debug -s d --description 'enables debugging.  Valid facilities are . PP . TS tab(,),box,center; lb|lr.'
complete -c isnsd -l dump-db --description 'This is a helper function that will read the database from the file system, a…'
complete -c isnsd -l init --description 'This option will create the server\'s authentication key, and the required DSA…'

