# ivstools
# Autogenerated from man page /usr/share/man/man1/ivstools.1.gz
complete -c ivstools -l convert --description '.'
complete -c ivstools -l merge --description 'AUTHOR This manual page was written by Adam Cecile <gandalf@le-vert.'

