# jack_property
# Autogenerated from man page /usr/share/man/man1/jack_property.1.gz
complete -c jack_property -s l --description 'list all metadata currently defined.'
complete -c jack_property -s d --description 'deletes all metadata for identifier.'
complete -c jack_property -s D --description 'delete all currently defined metadata.'
complete -c jack_property -s s --description 'sets the metadata associated with key to value for identifer, with its type s…'
complete -c jack_property -s c --description 'interpret a given identifier as a client name rather than a UUID.'
complete -c jack_property -s p --description 'interpret a given identifier as a port name rather than a UUID.'

