# javap-openjdk8
# Autogenerated from man page /usr/share/man/man1/javap-openjdk8.1.gz
complete -c javap-openjdk8 -o 'help
.br
--help
.br
-?' --description 'Prints a help message for the javap command.'
complete -c javap-openjdk8 -o version --description 'Prints release information.'
complete -c javap-openjdk8 -s l --description 'Prints line and local variable tables.'
complete -c javap-openjdk8 -o public --description 'Shows only public classes and members.'
complete -c javap-openjdk8 -o protected --description 'Shows only protected and public classes and members.'
complete -c javap-openjdk8 -o 'private
.br
-p' --description 'Shows all classes and members.'
complete -c javap-openjdk8 -o Joption --description 'Passes the specified option to the JVM.  For example: . sp . if n \\{\\.'
complete -c javap-openjdk8 -s s --description 'Prints internal type signatures.'
complete -c javap-openjdk8 -o sysinfo --description 'Shows system information (path, size, date, MD5 hash) of the class being proc…'
complete -c javap-openjdk8 -o constants --description 'Shows static final constants.'
complete -c javap-openjdk8 -s c --description 'Prints disassembled code, for example, the instructions that comprise the Jav…'
complete -c javap-openjdk8 -o verbose --description 'Prints stack size, number of locals and arguments for methods.'
complete -c javap-openjdk8 -o classpath --description 'Specifies the path the javap command uses to look up classes.'
complete -c javap-openjdk8 -o bootclasspath --description 'Specifies the path from which to load bootstrap classes.'
complete -c javap-openjdk8 -o extdir --description 'Overrides the location at which installed extensions are searched for.'
complete -c javap-openjdk8 -o help --description '.'
complete -c javap-openjdk8 -l help --description '.'
complete -c javap-openjdk8 -s '?' --description '.'
complete -c javap-openjdk8 -o private --description '.'
complete -c javap-openjdk8 -s p --description '.'

