# jcmd-openjdk14
# Autogenerated from man page /usr/share/man/man1/jcmd-openjdk14.1.gz
complete -c jcmd-openjdk14 -o all --description 'Compiler. codecache Prints code cache layout and bounds.  Impact: Low.'
complete -c jcmd-openjdk14 -o csv --description 'format for spreadsheets (BOOLEAN, false) [bu] 2.'
complete -c jcmd-openjdk14 -o help --description '(BOOLEAN, false).'
complete -c jcmd-openjdk14 -s l --description '(BOOLEAN, false) VM.'
complete -c jcmd-openjdk14 -s i --description '(BOOLEAN, false) [bu] 2.'
complete -c jcmd-openjdk14 -s s --description 'subclasses.'
complete -c jcmd-openjdk14 -o verbose --description 'table (BOOLEAN, false) VM. symboltable [options] Dumps the symbol table.'
complete -c jcmd-openjdk14 -o date --description '(BOOLEAN, false) VM. version Prints JVM version information.  Impact: Low.'

