# jconsole-openjdk14
# Autogenerated from man page /usr/share/man/man1/jconsole-openjdk14.1.gz
complete -c jconsole-openjdk14 -o interval --description 'Sets the update interval to n seconds (default is 4 seconds).'
complete -c jconsole-openjdk14 -o notile --description 'Doesn[aq]t tile the windows for two or more connections.'
complete -c jconsole-openjdk14 -o pluginpath --description 'Specifies the path that jconsole uses to look up plug-ins.'
complete -c jconsole-openjdk14 -o version --description 'Prints the program version.'
complete -c jconsole-openjdk14 -o Jinput_arguments --description 'Passes input_arguments to the JVM on which the jconsole command is run.'
complete -c jconsole-openjdk14 -o help -l help --description 'Displays the help message for the command.  DESCRIPTION.'

