# jdeprscan-openjdk14
# Autogenerated from man page /usr/share/man/man1/jdeprscan-openjdk14.1.gz
complete -c jdeprscan-openjdk14 -l class-path --description 'Provides a search path for resolution of dependent classes.'
complete -c jdeprscan-openjdk14 -l for-removal --description 'Limits scanning or listing to APIs that are deprecated for removal.'
complete -c jdeprscan-openjdk14 -l full-version --description 'Prints out the full version string of the tool.'
complete -c jdeprscan-openjdk14 -l help -s h --description 'Prints out a full help message.'
complete -c jdeprscan-openjdk14 -l list -s l --description 'Prints the set of deprecated APIs.'
complete -c jdeprscan-openjdk14 -l release --description 'Specifies the Java SE release that provides the set of deprecated APIs for sc…'
complete -c jdeprscan-openjdk14 -l verbose -s v --description 'Enables additional message output during processing.'
complete -c jdeprscan-openjdk14 -l version --description 'Prints out the abbreviated version string of the tool.'

