# jdeps-openjdk8
# Autogenerated from man page /usr/share/man/man1/jdeps-openjdk8.1.gz
complete -c jdeps-openjdk8 -o dotoutput --description 'br Destination directory for DOT file output.'
complete -c jdeps-openjdk8 -s s -o summary --description 'br Prints dependency summary only.'
complete -c jdeps-openjdk8 -s v -o verbose --description 'br Prints all class-level dependencies.'
complete -c jdeps-openjdk8 -o verbose:package --description 'br Prints package-level dependencies excluding dependencies within the same a…'
complete -c jdeps-openjdk8 -o verbose:class --description 'br Prints class-level dependencies excluding dependencies within the same arc…'
complete -c jdeps-openjdk8 -o cp -o classpath --description 'br Specifies where to find class files.   See also Setting the Class Path.'
complete -c jdeps-openjdk8 -s p -o package --description 'br Finds dependencies in the specified package.'
complete -c jdeps-openjdk8 -s e -o regex --description 'br Finds dependencies in packages matching the specified regular expression p…'
complete -c jdeps-openjdk8 -o include --description 'br Restricts analysis to classes matching pattern.'
complete -c jdeps-openjdk8 -o jdkinternals --description 'br Finds class-level dependences in JDK internal APIs.'
complete -c jdeps-openjdk8 -s P -o profile --description 'br Shows profile or the file containing a package.'
complete -c jdeps-openjdk8 -o apionly --description 'br Restricts analysis to APIs, for example, dependences from the signature of…'
complete -c jdeps-openjdk8 -s R -o recursive --description 'br Recursively traverses all dependencies.'
complete -c jdeps-openjdk8 -o version --description 'br Prints version information.'
complete -c jdeps-openjdk8 -s h -s '?' -o help --description '.'

