# jmap-openjdk8
# Autogenerated from man page /usr/share/man/man1/jmap-openjdk8.1.gz
complete -c jmap-openjdk8 -o 'dump:[live' --description 'br Dumps the Java heap in \\f3hprof binary format to \\f3filename.'
complete -c jmap-openjdk8 -o finalizerinfo --description 'br Prints information about objects that are awaiting finalization.'
complete -c jmap-openjdk8 -o heap --description 'br Prints a heap summary of the garbage collection used, the head configurati…'
complete -c jmap-openjdk8 -o histo --description 'br Prints a histogram of the heap.'
complete -c jmap-openjdk8 -o clstats --description 'br Prints class loader wise statistics of Java heap.'
complete -c jmap-openjdk8 -s F --description 'br Force.'
complete -c jmap-openjdk8 -s h --description 'br Prints a help message.'
complete -c jmap-openjdk8 -o help --description 'br Prints a help message.'
complete -c jmap-openjdk8 -o Jflag --description '.'

