# jpeg2swf
# Autogenerated from man page /usr/share/man/man1/jpeg2swf.1.gz
complete -c jpeg2swf -s o -l output --description 'Explicitly specify output file.'
complete -c jpeg2swf -s q -l quality --description 'Set compression quality (1-100, 1=worst, 100=best).'
complete -c jpeg2swf -s r -l rate --description 'Set movie framerate (frames per second).'
complete -c jpeg2swf -s z -l zlib --description 'Use Flash MX (SWF 6) Zlib encoding for the output.'
complete -c jpeg2swf -s M -l mx --description 'Use Flash MX H. 263 compression (use for correlated images).'
complete -c jpeg2swf -s x -l xoffset --description 'horizontally offset images by offset.'
complete -c jpeg2swf -s y -l yoffset --description 'vertically offset images by offset.'
complete -c jpeg2swf -s X -l width --description 'Force movie width to width (default: autodetect).'
complete -c jpeg2swf -s Y -l height --description 'Force movie height to height (default: autodetect).'
complete -c jpeg2swf -s T -l flashversion --description 'Set flash file version to version.'
complete -c jpeg2swf -s v -l verbose --description 'Set verbose level to level (0=quiet, 1=default, 2=debug).'
complete -c jpeg2swf -s V -l version --description 'Print version information and exit.'
complete -c jpeg2swf -s f -l fit-to-movie --description 'Fit images to movie size.'
complete -c jpeg2swf -s e -l export --description '    Make importable as asset with assetname AUTHORS.'

