# jps-openjdk14
# Autogenerated from man page /usr/share/man/man1/jps-openjdk14.1.gz
complete -c jps-openjdk14 -s q --description 'Suppresses the output of the class name, JAR file name, and arguments passed …'
complete -c jps-openjdk14 -o mlvV --description 'You can specify any combination of these options.'
complete -c jps-openjdk14 -s m --description 'The output may be null for embedded JVMs.  [bu] 2.'
complete -c jps-openjdk14 -s l --description 'main class or the full path name to the application[aq]s JAR file.  [bu] 2.'
complete -c jps-openjdk14 -s v --description '[bu] 2.'
complete -c jps-openjdk14 -s V --description 'arguments passed to the main method, producing a list of only local JVM ident…'
complete -c jps-openjdk14 -o help --description 'Displays the help message for the jps command.  DESCRIPTION.'

