# jstack-openjdk14
# Autogenerated from man page /usr/share/man/man1/jstack-openjdk14.1.gz
complete -c jstack-openjdk14 -s l --description 'The long listing option prints additional information about locks.'
complete -c jstack-openjdk14 -s h -o help --description 'Prints a help message.'

