# kamene
# Autogenerated from man page /usr/share/man/man1/kamene.1.gz
complete -c kamene -s h --description 'display usage.'
complete -c kamene -s d --description 'increase log verbosity.  Can be used many times.'
complete -c kamene -s s --description 'use FILE to save/load session values (variables, functions, instances, . ).'
complete -c kamene -s p --description 'use PRESTART_FILE instead of $HOME/. kamene_prestart. py as pre-startup file.'
complete -c kamene -s P --description 'do not run prestart file.'
complete -c kamene -s c --description 'use STARTUP_FILE instead of $HOME/. kamene_startup. py as startup file.'
complete -c kamene -s C --description 'do not run startup file.'

