# katedec
# Autogenerated from man page /usr/share/man/man1/katedec.1.gz
complete -c katedec -s h --description 'Show command line help.'
complete -c katedec -s V --description 'Show version information.'
complete -c katedec -s v --description 'Increase verbosity.'
complete -c katedec -s o --description 'Write the output description file to the given file name (writes to stdout if…'
complete -c katedec -s t --description 'Set the output format type:     kate: Kate description format     srt: SubRip…'

