# kbackup
# Autogenerated from man page /usr/share/man/man1/kbackup.1.gz
complete -c kbackup -s v -l version --description 'Displays version information.'
complete -c kbackup -s h -l help --description 'Displays help on commandline options.'
complete -c kbackup -l help-all --description 'Displays help including Qt specific options.'
complete -c kbackup -l qmljsdebugger --description 'Activates the QML/JS debugger with a specified port.'
complete -c kbackup -l script --description 'Script to run after finishing one archive slice.'
complete -c kbackup -l auto --description 'Automatically run the backup with the given profile and terminate when done.'
complete -c kbackup -l autobg --description 'Automatically run the backup with the given profile in the background (withou…'
complete -c kbackup -l verbose --description 'In autobg mode be verbose and print every single filename during backup.'
complete -c kbackup -l forceFull --description 'In auto/autobg mode force the backup to be a full backup instead of acting on…'
complete -c kbackup -l author --description 'Show author information.'
complete -c kbackup -l license --description 'Show license information.'
complete -c kbackup -l desktopfile --description 'The base file name of the desktop entry for this application.'

