# kig
# Autogenerated from man page /usr/share/man/man1/kig.1.gz
complete -c kig -s c -l convert-to-native --description 'Do not show a GUI.  Instead convert the specified file to native Kig format.'
complete -c kig -s o -l outfile --description 'Used with --convert-to-native to specify where to save the newly created Kig …'

