# kjs5
# Autogenerated from man page /usr/share/man/man1/kjs5.1.gz
complete -c kjs5 -l help -o help -s h --description 'Show kjs5 usage.'
complete -c kjs5 -l version -o version -s v --description 'Show kjs5 version.'
complete -c kjs5 -s e --description 'Executes the statement and exits.'

