# kpat
# Autogenerated from man page /usr/share/man/man6/kpat.6.gz
complete -c kpat -s h -l help --description 'This lists the options available at the command line.'
complete -c kpat -s v -l version --description 'Lists version information for KPatience.'
complete -c kpat -l solvegame --description 'Try to find a solution to the given savegame.'
complete -c kpat -l solve --description 'Dealer to solve (debug).'
complete -c kpat -l start --description 'Game range start (default 0:INT_MAX).'
complete -c kpat -l end --description 'Game range end (default start:start if start given).'
complete -c kpat -l gametype --description 'Skip the selection screen and load a particular game type.'
complete -c kpat -l testdir --description 'Directory with test cases.'
complete -c kpat -l generate --description 'Generate random test cases.'
complete -c kpat -l author --description 'Lists KPatience\\*(Aqs authors in the terminal window.'
complete -c kpat -l license --description 'Shows license information.'
complete -c kpat -l desktopfile --description 'The base file name of the desktop entry for this application.'

