# latd
# Autogenerated from man page /usr/share/man/man8/latd.8.gz
complete -c latd -s i --description 'Set the interface to be used for LAT communication.'
complete -c latd -s g --description 'Sets the greeting for this node.'
complete -c latd -s s --description 'Set the default service name for this node.  The default is the node name.'
complete -c latd -s c --description 'Sets the circuit timer.  The default is 80 (ms);.'
complete -c latd -s r --description 'Sets the rating for the default service.'
complete -c latd -s t --description 'Makes the rating static.  It will not change as the system load changes.'
complete -c latd -s d --description 'Don\'t fork and run the background.  Use this for debugging.'
complete -c latd -s v --description 'Verbose.  The more of these there are the more verbose latd will be.'
complete -c latd -s h -s '?' --description 'Displays help for using the command.'
complete -c latd -s V --description 'Show the version of latd.  SEE ALSO latcp (8),  latd. conf (5),  llogin (1).'

