# ldbadd
# Autogenerated from man page /usr/share/man/man1/ldbadd.1.gz
complete -c ldbadd -s h --description 'Show list of available options.'
complete -c ldbadd -s H --description 'LDB URL to connect to.  See ldb(3) for details.'

