# ldns-testns
# Autogenerated from man page /usr/share/man/man1/ldns-testns.1.gz
complete -c ldns-testns -s r --description 'Listens to a random port.  The port number is printed to stdout.'
complete -c ldns-testns -s p --description 'Listens to the specified port.'
complete -c ldns-testns -s f --description 'Forks this number of additional instances that serve the same ports and same …'
complete -c ldns-testns -s v --description 'Outputs more debug information.'
complete -c ldns-testns -s 6 --description 'Bind to IP6 address instead of IP4.  Use together with -p.'

