# ldns-walk
# Autogenerated from man page /usr/share/man/man1/ldns-walk.1.gz
complete -c ldns-walk -s 4 --description 'Use only IPv4.'
complete -c ldns-walk -s 6 --description 'Use only IPv6.'
complete -c ldns-walk -s f --description 'Do a \'full\' zone walk; by default, ldns-walk will only show the names, and ty…'
complete -c ldns-walk -s s --description 'Start the walk with this owner name.'
complete -c ldns-walk -s v --description 'Verbosity level [1-5].'

