# ldns-key2ds
# Autogenerated from man page /usr/share/man/man1/ldns-key2ds.1.gz
complete -c ldns-key2ds -s f --description 'Ignore SEP flag (i. e.  make DS records for any key).'
complete -c ldns-key2ds -s n --description 'Write the result DS Resource Record to stdout instead of a file.'
complete -c ldns-key2ds -s 1 --description 'Use SHA1 as the hash function.'
complete -c ldns-key2ds -s 2 --description 'Use SHA256 as the hash function.'
complete -c ldns-key2ds -s g --description 'Use GOST as the hash function.'
complete -c ldns-key2ds -s 4 --description 'Use SHA384 as the hash function.'

