# ldrdf
# Autogenerated from man page /usr/share/man/man1/ldrdf.1.gz
complete -c ldrdf -s o --description 'Specify an output file.   The default output filename is . RI \' aout. rdx \'.'
complete -c ldrdf -s v --description 'Increase verbosity level.'
complete -c ldrdf -s p --description 'Change alignment value to which multiple segments combigned into a single seg…'

