# lecs
# Autogenerated from man page /usr/share/man/man8/lecs.8.gz
complete -c lecs -s d --description 'Reads the configuration file, dumps its contents and exits.'
complete -c lecs -o llisten_address --description 'Use the listen_address to where wait connections.'
complete -c lecs -s l --description 'Use the listen_address to where wait connections.'
complete -c lecs -s f --description 'Use the specified configuration file instead of . lecs_conf.  FILES .'

