# les
# Autogenerated from man page /usr/share/man/man8/les.8.gz
complete -c les -o dmodule --description 'Set debugging messages on for a module.'
complete -c les -o mmodule --description 'Set memory debugging messages on for a module.'
complete -c les -s d --description 'Set debugging messages on for a module.'
complete -c les -s m --description 'Set memory debugging messages on for a module.'
complete -c les -s f --description 'Use the specified configuration file instead of . lanevars.  FILES .'

