# libmikmod-config
# Autogenerated from man page /usr/share/man/man1/libmikmod-config.1.gz
complete -c libmikmod-config -l version --description 'Print the currently installed version of libmikmod on the standard output.'
complete -c libmikmod-config -l libs --description 'Print the linker flags that are necessary to link a libmikmod program.'
complete -c libmikmod-config -l ldadd --description 'Print the extra linker flags that are necessary to link a libmikmod program i…'
complete -c libmikmod-config -l cflags --description 'Print the compiler flags that are necessary to compile a libmikmod program.'
complete -c libmikmod-config -l prefix --description 'If specified, use PREFIX instead of the installation prefix that libmikmod wa…'
complete -c libmikmod-config -l exec-prefix --description 'If specified, use PREFIX instead of the installation exec prefix that libmikm…'

