# lighttpd
# Autogenerated from man page /usr/share/man/man8/lighttpd.8.gz
complete -c lighttpd -s f --description 'Load configuration file configfile.'
complete -c lighttpd -s m --description 'Use moduledir as the directory that contains modules, instead of the default.'
complete -c lighttpd -s p --description 'Print the parsed configuration file in its internal form and exit.'
complete -c lighttpd -s t --description 'Test the configuration file for syntax errors and exit.'
complete -c lighttpd -o tt --description 'Test the configuration file for syntax errors, load and initialize modules, a…'
complete -c lighttpd -s D --description 'Do not daemonize (go into background).  The default is to daemonize.'
complete -c lighttpd -s i --description 'Trigger daemon graceful shutdown after secs of inactivity.'
complete -c lighttpd -s 1 --description 'Process single (one) request on stdin socket, then exit.'
complete -c lighttpd -s v --description 'Show version and exit.'
complete -c lighttpd -s V --description 'Show compile-time features and exit.'
complete -c lighttpd -s h --description 'Show a brief help message and exit.'

