# llogin
# Autogenerated from man page /usr/share/man/man1/llogin.1.gz
complete -c llogin -s d --description 'Shows learned services.  This is the same as latcp -d -l.'
complete -c llogin -s v --description 'Verbose form of -d.  -v without -d is ignored.'
complete -c llogin -s H --description 'Remote nodename.'
complete -c llogin -s R --description 'Connect to a specific port on (usually) a terminal server.'
complete -c llogin -s c --description 'Do not convert typed LF to CR.'
complete -c llogin -s b --description 'Convert typed DEL to BS.'
complete -c llogin -s l --description 'Convert output LF to VT.'
complete -c llogin -s q --description 'Change the quit character.  By default CTRL-] will quit the terminal session.'
complete -c llogin -s Q --description 'Tells latd that the service you are connecting to is queued service and not a…'
complete -c llogin -s n --description 'Sets the local connection name.  By default this will be your local TTY name.'
complete -c llogin -s w --description 'Sends the password for the service.'
complete -c llogin -s W --description 'Prompts for the service password.  This is the same as -w- (see above).'
complete -c llogin -s p --description 'Tells llogin to connect to the device named instead of a LAT service.'
complete -c llogin -s h --description 'Displays a brief usage description.'

