# lndir
# Autogenerated from man page /usr/share/man/man1/lndir.1.gz
complete -c lndir -o silent --description 'Normally lndir outputs the name of each subdirectory as it descends into it.'
complete -c lndir -o ignorelinks --description 'Causes the program to not treat symbolic links in fromdir specially.'
complete -c lndir -o withrevinfo --description 'Causes any source control manager subdirectories (those named BitKeeper, CVS,…'

