# logkeys
# Autogenerated from man page /usr/share/man/man8/logkeys.8.gz
complete -c logkeys -s s -l start --description 'Starts the keylogging daemon process.'
complete -c logkeys -s k -l kill --description 'Terminates the running logkeys process.'
complete -c logkeys -s o -l output --description 'Set ouput log file to logfile.'
complete -c logkeys -s m -l keymap --description 'Use file keymap as input keymap for processing pressed keys.'
complete -c logkeys -s d -l device --description 'Use device as keyboard input event device instead of /dev/input/eventX defaul…'
complete -c logkeys -s u -l us-keymap --description 'This option makes logkeys interpret keys as on standard US keyboard.'
complete -c logkeys -l export-keymap --description 'This option makes logkeys export dynamic keymap as obtained from dumpkeys(1) …'
complete -c logkeys -l no-func-keys --description 'This option makes logkeys log all and only character key presses  (1, 2, .'
complete -c logkeys -l no-timestamps --description 'When this option is set, logkeys doesn\'t prepend timestamp to each line of lo…'
complete -c logkeys -l post-size --description 'When log size reaches SIZE, the current log filename is appended .'
complete -c logkeys -l post-http --description 'This option tells logkeys to POST the log file to URL, where it is preferrabl…'
complete -c logkeys -l no-daemon --description 'When this option is set, logkeys runs in the foreground.'

