# lou_tableinfo
# Autogenerated from man page /usr/share/man/man1/lou_tableinfo.1.gz
complete -c lou_tableinfo -s h -l help --description 'display this help and exit.'
complete -c lou_tableinfo -s v -l version --description 'display version information and exi AUTHOR Written by Bert Frees.'

