# lou_trace
# Autogenerated from man page /usr/share/man/man1/lou_trace.1.gz
complete -c lou_trace -s h -l help --description 'display this help and exit.'
complete -c lou_trace -s v -l version --description 'display version information and exit.'
complete -c lou_trace -s f -l forward --description 'forward translation using the given table.'
complete -c lou_trace -s b -l backward --description 'backward translation using the given table.'
complete -c lou_trace -l noContractions --description 'Use no contractions.'
complete -c lou_trace -l dotsIO --description 'Display dot patterns.'
complete -c lou_trace -l ucBrl --description 'Use Unicode Braille patterns.'
complete -c lou_trace -l noUndefined --description 'Disable output of undefined dot numbers during back-translation.'
complete -c lou_trace -l partialTrans --description 'Use partial back-translation If neither -f nor -b are specified forward trans…'

