# lspst
# Autogenerated from man page /usr/share/man/man1/lspst.1.gz
complete -c lspst -s V --description 'Show program version and exit.'
complete -c lspst -s d --description 'Specify name of debug log file.'
complete -c lspst -s f --description 'Select the date format for long format listing.  Defaults to "%F %T".'
complete -c lspst -s l --description 'Use long format listing to show the Date, CC and BCC headers.'
complete -c lspst -s h --description 'Show summary of options and exit.'

