# lsrtunnel
# Autogenerated from man page /usr/share/man/man1/lsrtunnel.1.gz
complete -c lsrtunnel -s i --description 'Set the silentIP.'
complete -c lsrtunnel -s t --description 'Set the target IP.  This is the remote machine that you will be  targeting.'
complete -c lsrtunnel -s f --description 'The IP address that lsrtunnel will pretend to be.'

