# ltdbtool
# Autogenerated from man page /usr/share/man/man1/ltdbtool.1.gz
complete -c ltdbtool -s e --description 'Dump empty records.  These are normally excluded.'
complete -c ltdbtool -s p --description 'Dump with header information, similar to "ctdb catdb".'
complete -c ltdbtool -s o --description 'Specify how to determine the CTDB record header size for the output database,…'
complete -c ltdbtool -s S --description 'Explicitly specify the CTDB record header SIZE of the input database in bytes.'
complete -c ltdbtool -s O --description 'Explicitly specify the CTDB record header SIZE for the output database in byt…'
complete -c ltdbtool -s h --description 'Print help text.'
complete -c ltdbtool -s s --description '.'

