# lv2ls
# Autogenerated from man page /usr/share/man/man1/lv2ls.1.gz
complete -c lv2ls -s n -l names --description 'Show names instead of URIs.'
complete -c lv2ls -l help --description 'Display help and exit.'
complete -c lv2ls -l version --description 'Display version information and exit.'

