# macchanger
# Autogenerated from man page /usr/share/man/man1/macchanger.1.gz
complete -c macchanger -s h -l help --description 'Show summary of options.'
complete -c macchanger -s V -l version --description 'Show version of program.'
complete -c macchanger -s s -l show --description 'Prints the current MAC.'
complete -c macchanger -s e -l ending --description 'Don\'t change the vendor bytes.'
complete -c macchanger -s a -l another --description 'Set random vendor MAC of the same kind.'
complete -c macchanger -s A --description 'Set random vendor MAC of any kind.'
complete -c macchanger -s r -l random --description 'Set fully random MAC.'
complete -c macchanger -s p -l permanent --description 'Reset MAC address to its original, permanent hardware value.'
complete -c macchanger -s l -l list --description 'Print known vendors (with keyword in the vendor\'s description string).'
complete -c macchanger -s b -l bia --description 'When setting fully random MAC pretend to be a burned-in-address.'
complete -c macchanger -s m -l mac -l mac --description 'Set the MAC XX:XX:XX:XX:XX:XX.'

