# mailx
# Autogenerated from man page /usr/share/man/man1/mailx.1p.gz
complete -c mailx -s f --description 'option is used to read mail messages from secondary files, messages shall be …'
complete -c mailx -s s --description 'subject option shall be required on all systems.'
complete -c mailx -s e --description 'Test for the presence of mail in the system mailbox.'
complete -c mailx -s F --description 'Record the message in a file named after the first recipient.'
complete -c mailx -s H --description 'Write a header summary only.'
complete -c mailx -s i --description 'Ignore interrupts.  (See also ignore . ).'
complete -c mailx -s n --description 'Do not initialize from the system default start-up file.'
complete -c mailx -s N --description 'Do not write an initial header summary.'
complete -c mailx -s u --description 'Read the system mailbox of the login name user .'
complete -c mailx -s c --description 'command shall be valid.'

