# make_method
# Autogenerated from man page /usr/share/man/man1/make_method.1p.gz
complete -c make_method -l help --description 'Prints a short summary of the options.'
complete -c make_method -l name --description 'Specifies the published name of the method being encoded.'
complete -c make_method -l namespace --description 'Specifies a namespace that the code of the method will be evaluated in, when …'
complete -c make_method -l type --description 'Specify the type for the resulting file.'
complete -c make_method -l version --description 'Specify a version stamp for the code routine.'
complete -c make_method -l hidden --description 'If this is passe, the resulting file will include a tag that tells the server…'
complete -c make_method -l signature -l signature --description 'Specify one or more signatures for the method.'
complete -c make_method -l helptext --description 'Specify the help text for the method as a simple string on the command line.'
complete -c make_method -l helpfile --description 'Read the help text for the method from the file specified.'
complete -c make_method -l code --description 'Read the actual code for the routine from the file specified.'
complete -c make_method -l output --description 'Write the resulting \\s-1XML\\s0 representation to the specified file.'
complete -c make_method -l base --description 'This is a special, \\*(L"all-in-one\\*(R" option.'

