# mapsid
# Autogenerated from man page /usr/share/man/man1/mapsid.1.gz
complete -c mapsid -l print-classes --description 'For each sensor, print the classes for which the sensor collects data.'
complete -c mapsid -l print-descriptions --description 'For each sensor, print the description of the sensor as defined in the silk.'
complete -c mapsid -l site-config-file --description 'Read the SiLK site configuration from the named file \\s-1FILENAME\\s0.'
complete -c mapsid -l help --description 'Print the available options and exit.'

