# mat
# Autogenerated from man page /usr/share/man/man1/mat.1.gz
complete -c mat -s h -l help --description 'show this help message and exit.'
complete -c mat -s a -l add2archive --description 'Add to outputed archive non-supported filetypes.'
complete -c mat -s b -l backup --description 'Keep a backup copy.'
complete -c mat -s c -l check --description 'Check if a file is free of harmful metadatas.'
complete -c mat -s d -l display --description 'List all the harmful meta of a file without removing them.'
complete -c mat -s l -l list --description 'List all supported fileformat.'
complete -c mat -s L -l low-pdf-quality --description 'Reduced the produced PDF size and quality.'
complete -c mat -s v -l version --description 'Display version and exit EXAMPLES.'

