# mat2
# Autogenerated from man page /usr/share/man/man1/mat2.1.gz
complete -c mat2 -s h -l help --description 'show this help message and exit.'
complete -c mat2 -s v -l version --description 'show program\'s version number and exit.'
complete -c mat2 -s l -l list --description 'list all supported fileformats.'
complete -c mat2 -l check-dependencies --description 'check if mat2 has all the dependencies it needs.'
complete -c mat2 -s V -l verbose --description 'show more verbose status information.'
complete -c mat2 -l unknown-members --description 'how to handle unknown members of archive-style files (policy should be one of…'
complete -c mat2 -s s -l show --description 'list harmful metadata detectable by mat2 without removing them.'
complete -c mat2 -s L -l lightweight --description 'remove SOME metadata.'
complete -c mat2 -l no-sandbox --description 'disable bubblewrap\'s sandboxing.'
complete -c mat2 -l inplace --description 'clean in place, without backup.'

