# mate-default-applications-properties
# Autogenerated from man page /usr/share/man/man1/mate-default-applications-properties.1.gz
complete -c mate-default-applications-properties -s p -l show-page --description 'Specify the name of the page to show (internet|multimedia|system|a11y).'

