# mate-appearance-properties
# Autogenerated from man page /usr/share/man/man1/mate-appearance-properties.1.gz
complete -c mate-appearance-properties -s i -l install-theme --description 'Specify the filename of a theme to install . PP.'

