# mate-keyboard-properties
# Autogenerated from man page /usr/share/man/man1/mate-keyboard-properties.1.gz
complete -c mate-keyboard-properties -l apply --description 'Just apply settings and quit (compatibility only; now handled by daemon).'
complete -c mate-keyboard-properties -l init-session-settings --description 'Just apply settings and quit (compatibility only; now handled by daemon).'
complete -c mate-keyboard-properties -l get-legacy --description 'Retrieve and store legacy settings.'
complete -c mate-keyboard-properties -l typing-break --description 'Start the page with the typing break settings showing.'

