# mate-mouse-properties
# Autogenerated from man page /usr/share/man/man1/mate-mouse-properties.1.gz
complete -c mate-mouse-properties -l get-legacy --description 'Retrieve and store legacy settings.'

