# mdassembler
# Autogenerated from man page /usr/share/man/man1/mdassembler.1.gz
complete -c mdassembler -l ecma --description 'The documentation found within   DIRS is in the Mono ECMA documentation forma…'
complete -c mdassembler -l ecmaspec --description 'The documentation found within   DIRS is in the ECMA Specification documentat…'
complete -c mdassembler -l error --description 'The documentation found within  DIRS is in "error" format.'
complete -c mdassembler -l help --description 'Show program argument information.'
complete -c mdassembler -l man --description 'The documentation found within  DIRS is in man page format.'
complete -c mdassembler -s o -l out --description 'Specify the output file prefix.   mdassembler creates the files  PREFIX.'
complete -c mdassembler -l simple --description 'The documentation found within  DIRS is in "simple" format.'
complete -c mdassembler -l xhtml -l hb --description 'The documentation found within DIRS is in XHTML format.'

