# mdb_stat
# Autogenerated from man page /usr/share/man/man1/mdb_stat.1.gz
complete -c mdb_stat -s V --description 'Write the library version number to the standard output, and exit.'
complete -c mdb_stat -s e --description 'Display information about the database environment.'
complete -c mdb_stat -s f --description 'Display information about the environment freelist.'
complete -c mdb_stat -s n --description 'Display the status of an LMDB database which does not use subdirectories.'
complete -c mdb_stat -s r --description 'Display information about the environment reader table.'
complete -c mdb_stat -s a --description 'Display the status of all of the subdatabases in the environment.'
complete -c mdb_stat -s s --description 'Display the status of a specific subdatabase.'

