# memdump
# Autogenerated from man page /usr/share/man/man1/memdump.1.gz
complete -c memdump -s k --description 'Attempt to dump kernel memory (/dev/kmem) rather than physical memory.'
complete -c memdump -s b --description 'Number of bytes per memory read operation.'
complete -c memdump -s d --description 'Number of memory bytes to dump.'
complete -c memdump -s m --description 'Write the memory map to map_file, one entry per line.'
complete -c memdump -s p --description 'Use page_size as the memory page size.'
complete -c memdump -s v --description 'Enable verbose logging for debugging purposes.'

