# memhog
# Autogenerated from man page /usr/share/man/man8/memhog.8.gz
complete -c memhog -o 'r<num>	Repeat' --description '.'
complete -c memhog -o 'f<file>	Open' --description '.'
complete -c memhog -o 'H	Disable' --description '.'
complete -c memhog -o 'size	Allocation' --description '	suffix (G=gigabyte, M=megabyte, K=kilobyte) Supported numa-policies:.'

