# mergecap
# Autogenerated from man page /usr/share/man/man1/mergecap.1.gz
complete -c mergecap -s a --description 'Causes the frame timestamps to be ignored, writing all packets from the first…'
complete -c mergecap -s F --description 'Sets the file format of the output capture file.'
complete -c mergecap -s h --description 'Prints the version and options and exits.'
complete -c mergecap -s I --description 'Sets the Interface Description Block (\\s-1IDB\\s0) merge mode to use during me…'
complete -c mergecap -s s --description 'Sets the snapshot length to use when writing the data.'
complete -c mergecap -s v --description 'Causes mergecap to print a number of messages while it\'s working.'
complete -c mergecap -s V --description 'Print the version and exit.'

