# mfoc
# Autogenerated from man page /usr/share/man/man1/mfoc.1.gz
complete -c mfoc -s h --description 'Show summary of options.'
complete -c mfoc -s k --description 'Initially try KEY in addition to the default keys.'
complete -c mfoc -s O --description 'Dump card contents to FILE.'
complete -c mfoc -s P --description 'Probe each sector up to NUM times.   Default is 20.'
complete -c mfoc -s T --description 'Set half the range for a possible distance tolerance to NUM.'

