# minewt
# Autogenerated from man page /usr/share/man/man1/minewt.1.gz
complete -c minewt -s i --description 'The Internal IP address, which will be the gateway your internal hosts will s…'
complete -c minewt -s I --description 'The External IP address, which will be the IP address that the external world…'
complete -c minewt -s r --description 'The Default Gateway, which is the upstream router that will route your packet…'
complete -c minewt -s d -s D --description 'Use this Layer 2 Device for internal / External traffic.'
complete -c minewt -s m -s M --description 'Force MAC address for internal pseudodevice / External pseudodevice.'
complete -c minewt -s g -s G --description 'Disable internal / External gratuitous ARP, i. e.'
complete -c minewt -s R --description 'Force MAC address for default gateway.'
complete -c minewt -s t --description 'Set timeout period for stateful connections.   Defaults to six minutes.'
complete -c minewt -s v --description 'Increase verbosity.'
complete -c minewt -s l --description 'Designate one IP address on your internal network to receive all incoming pac…'
complete -c minewt -s s -s S --description 'Embed NAT state in IP Timestamps.'
complete -c minewt -s F --description 'Enable fragment-spread IP Timestamps.'
complete -c minewt -s a -s A --description 'Force MAC address when *ARPing* a given MAC/IP association.'

