# moc-qt3
# Autogenerated from man page /usr/share/man/man1/moc-qt3.1.gz
complete -c moc-qt3 -s o --description 'Write output to  file rather than to stdout.'
complete -c moc-qt3 -s f --description 'Force the generation of an #include statement in the output.'
complete -c moc-qt3 -s i --description 'Do not generate an #include statement in the output.'
complete -c moc-qt3 -o nw --description 'Do not generate any warnings.  Not recommended.'
complete -c moc-qt3 -o ldbg --description 'Write a flood of lex debug information to stdout.'
complete -c moc-qt3 -s p --description 'Makes  moc prepend R path / to the file name in the generated #include statem…'
complete -c moc-qt3 -s q --description 'Makes  moc prepend R path / to the file name of qt #include files in the gene…'
complete -c moc-qt3 -s v --description 'Displays the version of moc and Qt.'

