# mperfmon
# Autogenerated from man page /usr/share/man/man1/mperfmon.1.gz
complete -c mperfmon -l config --description 'Specifies the configuration file to load instead of the default one installed…'
complete -c mperfmon -l report --description 'Instead of showing the GUI, run in console mode and print a report of the set…'
complete -c mperfmon -l count --description 'Sets the number of times a report is printed in console mode.'

