# mprof-report
# Autogenerated from man page /usr/share/man/man1/mprof-report.1.gz
complete -c mprof-report -l help --description 'Displays usage instructions.'
complete -c mprof-report -l out --description 'Write the report output to file instead of standard output.'
complete -c mprof-report -l traces --description 'Show backtraces in reports when available.'
complete -c mprof-report -l maxframes --description 'Limit backtraces to num frames.'
complete -c mprof-report -l reports --description 'Generate only the specified reports.'
complete -c mprof-report -l method-sort --description 'Sort methods according to mode, which can be one of: . RS.'
complete -c mprof-report -l alloc-sort --description 'Sort allocations according to mode, which can be one of: . RS.'
complete -c mprof-report -l counters-sort --description 'Sort counters according to mode.'
complete -c mprof-report -l track --description 'Track what happens to the specified objects.'
complete -c mprof-report -l find --description 'Find and track what happens to objects matching spec, which can have one of t…'
complete -c mprof-report -l thread --description 'Consider only events from the thread with ID tid.'
complete -c mprof-report -l time --description 'Consider only events occurring in the specified time span.'
complete -c mprof-report -l verbose --description 'Print verbose output.'
complete -c mprof-report -l debug --description 'Print extremely detailed debug output.  Most users should not use this option.'

