# mutt_pgpring
# Autogenerated from man page /usr/share/man/man1/mutt_pgpring.1.gz
complete -c mutt_pgpring -s k --description 'Dump the contents of the specified keyring.'
complete -c mutt_pgpring -s 2 --description 'Use the default keyring for PGP 2. x.'
complete -c mutt_pgpring -s 5 --description 'Use the default keyring for PGP 5.'
complete -c mutt_pgpring -s s --description 'Dump the secret keyring.'
complete -c mutt_pgpring -s S --description 'Dump signatures.'
complete -c mutt_pgpring -s f --description 'Dump fingerprints.'

