# mysql
# Autogenerated from man page /usr/share/man/man1/mysql.server.1.gz
complete -c mysql -l basedir --description '.'
complete -c mysql -l datadir --description '.'
complete -c mysql -l pid-file --description '.'
complete -c mysql -l service-startup-timeout --description '.'
complete -c mysql -l use-mysqld_safe --description '.'
complete -c mysql -l use-manager --description '.'

