# n3map-nsec3-lookup
# Autogenerated from man page /usr/share/man/man1/n3map-nsec3-lookup.1.gz
complete -c n3map-nsec3-lookup -s o --description 'Write the found records to outfile instead of standard output.'
complete -c n3map-nsec3-lookup -s z --description 'If this option is used, every domain name read from standard input is interpr…'
complete -c n3map-nsec3-lookup -s v --description 'Be more verbose.'

