# named-rrchecker
# Autogenerated from man page /usr/share/man/man1/named-rrchecker.1.gz
complete -c named-rrchecker -s h --description 'prints out the help menu.'
complete -c named-rrchecker -s o --description 'option specifies a origin to be used when interpreting the record.'
complete -c named-rrchecker -s p --description 'prints out the resulting record in canonical form.'
complete -c named-rrchecker -s u --description 'prints out the resulting record in unknown record form.'
complete -c named-rrchecker -s C --description '.'
complete -c named-rrchecker -s T --description 'and.'
complete -c named-rrchecker -s P --description 'print out the known class, standard type and private type mnemonics respectiv…'

