# nbtscan
# Autogenerated from man page /usr/share/man/man1/nbtscan.1.gz
complete -c nbtscan -s v --description 'Verbose output.  Print all names received from each host.'
complete -c nbtscan -s d --description 'Dump packets.  Print whole packet contents.'
complete -c nbtscan -s e --description 'Format output in /etc/hosts format.'
complete -c nbtscan -s l --description 'Format output in lmhosts format.  Cannot be used with -v, -s or  -h options.'
complete -c nbtscan -s t --description 'Wait timeout seconds for response.  Default 1.'
complete -c nbtscan -s b --description 'Output throttling.'
complete -c nbtscan -s r --description 'Use local port 137 for scans.  Win95 boxes respond to this only.'
complete -c nbtscan -s q --description 'Suppress banners and error messages.'
complete -c nbtscan -s s --description 'Script-friendly output.'
complete -c nbtscan -s h --description 'Print human-readble names for services.   Can only be used with -v option.'
complete -c nbtscan -s m --description 'Number of retransmits.  Default 0.'
complete -c nbtscan -s f --description 'Take IP addresses to scan from file "filename".'

