# ncftpbatch
# Autogenerated from man page /usr/share/man/man1/ncftpbatch.1.gz
complete -c ncftpbatch -s d --description 'Begin background processing of FTP jobs in the current user\'s $HOME/.'
complete -c ncftpbatch -s l --description 'Lists the contents of the user\'s job queue.'

