# ncftpspooler
# Autogenerated from man page /usr/share/man/man1/ncftpspooler.1.gz
complete -c ncftpspooler -s d --description 'Begin background processing of FTP jobs in the designated FTP job queue direc…'
complete -c ncftpspooler -s q --description 'Use this option to specify a directory to use as the FTP job queue instead of…'
complete -c ncftpspooler -s o --description 'Use this option to specify a filename to use as the log file.'
complete -c ncftpspooler -s l --description 'Lists the contents of the job queue directory.'

