# ndctl-init-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-init-labels.1.gz
complete -c ndctl-init-labels -s s -l size --description '.'
complete -c ndctl-init-labels -s O -l offset --description '.'
complete -c ndctl-init-labels -s b -l bus --description '.'
complete -c ndctl-init-labels -s v --description '.'
complete -c ndctl-init-labels -s f -l force --description '.'
complete -c ndctl-init-labels -s V -l label-version --description '.'

