# ndctl-disable-namespace
# Autogenerated from man page /usr/share/man/man1/ndctl-disable-namespace.1.gz
complete -c ndctl-disable-namespace -s r -l region --description '.'
complete -c ndctl-disable-namespace -s b -l bus --description '.'
complete -c ndctl-disable-namespace -s v -l verbose --description '.'

