# ndctl-inject-error
# Autogenerated from man page /usr/share/man/man1/ndctl-inject-error.1.gz
complete -c ndctl-inject-error -s B -l block --description '.'
complete -c ndctl-inject-error -s n -l count --description '.'
complete -c ndctl-inject-error -s d -l uninject --description '.'
complete -c ndctl-inject-error -s t -l status --description '.'
complete -c ndctl-inject-error -s N -l no-notify --description '.'
complete -c ndctl-inject-error -s S -l saturate --description '.'
complete -c ndctl-inject-error -s v -l verbose --description '.'
complete -c ndctl-inject-error -s u -l human --description '.'
complete -c ndctl-inject-error -s r -l region --description '.'
complete -c ndctl-inject-error -s b -l bus --description '.'

