# ndctl-freeze-security
# Autogenerated from man page /usr/share/man/man1/ndctl-freeze-security.1.gz
complete -c ndctl-freeze-security -s b -l bus --description '.'
complete -c ndctl-freeze-security -s v -l verbose --description '.'

