# ndctl-zero-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-zero-labels.1.gz
complete -c ndctl-zero-labels -s s -l size --description '.'
complete -c ndctl-zero-labels -s O -l offset --description '.'
complete -c ndctl-zero-labels -s b -l bus --description '.'
complete -c ndctl-zero-labels -s v --description '.'

