# ndctl-write-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-write-labels.1.gz
complete -c ndctl-write-labels -s s -l size --description '.'
complete -c ndctl-write-labels -s O -l offset --description '.'
complete -c ndctl-write-labels -s b -l bus --description '.'
complete -c ndctl-write-labels -s v --description '.'
complete -c ndctl-write-labels -s i -l input --description '.'

