# ndctl-create-namespace
# Autogenerated from man page /usr/share/man/man1/ndctl-create-namespace.1.gz
complete -c ndctl-create-namespace -s t -l type --description '.'
complete -c ndctl-create-namespace -s m -l mode --description 'oc "raw": expose the namespace capacity directly with limitations.'
complete -c ndctl-create-namespace -s s -l size --description '.'
complete -c ndctl-create-namespace -s a -l align --description '.'
complete -c ndctl-create-namespace -s e -l reconfig --description '.'
complete -c ndctl-create-namespace -s u -l uuid --description '.'
complete -c ndctl-create-namespace -s n -l name --description '.'
complete -c ndctl-create-namespace -s l -l sector-size --description '.'
complete -c ndctl-create-namespace -s M -l map --description '.'
complete -c ndctl-create-namespace -s c -l continue --description '.'
complete -c ndctl-create-namespace -s f -l force --description '.'
complete -c ndctl-create-namespace -s L -l autolabel -l no-autolabel --description '.'
complete -c ndctl-create-namespace -s R -l autorecover -l no-autorecover --description '.'
complete -c ndctl-create-namespace -s v -l verbose --description '.'
complete -c ndctl-create-namespace -s r -l region --description '.'
complete -c ndctl-create-namespace -s b -l bus --description '.'

