# ndctl-sanitize-dimm
# Autogenerated from man page /usr/share/man/man1/ndctl-sanitize-dimm.1.gz
complete -c ndctl-sanitize-dimm -s b -l bus --description '.'
complete -c ndctl-sanitize-dimm -s c -l crypto-erase --description '.'
complete -c ndctl-sanitize-dimm -s o -l ovewrite --description '.'
complete -c ndctl-sanitize-dimm -s m -l master-passphrase --description '.'
complete -c ndctl-sanitize-dimm -s z -l zero-key --description '.'
complete -c ndctl-sanitize-dimm -l verbose --description '.'

