# ndctl-write-infoblock
# Autogenerated from man page /usr/share/man/man1/ndctl-write-infoblock.1.gz
complete -c ndctl-write-infoblock -l bus -l region --description '.'
complete -c ndctl-write-infoblock -s c -l stdout --description '.'
complete -c ndctl-write-infoblock -s o -l output --description '.'
complete -c ndctl-write-infoblock -s m -l mode --description '.'
complete -c ndctl-write-infoblock -s s -l size --description '.'
complete -c ndctl-write-infoblock -s a -l align --description '.'
complete -c ndctl-write-infoblock -s u -l uuid --description '.'
complete -c ndctl-write-infoblock -s M -l map --description '.'
complete -c ndctl-write-infoblock -s p -l parent-uuid --description '.'
complete -c ndctl-write-infoblock -s O -l offset --description '.'
complete -c ndctl-write-infoblock -s r --description '.'

