# ndctl-monitor
# Autogenerated from man page /usr/share/man/man1/ndctl-monitor.1.gz
complete -c ndctl-monitor -s b -l bus --description '.'
complete -c ndctl-monitor -s d -l dimm --description '.'
complete -c ndctl-monitor -s r -l region --description '.'
complete -c ndctl-monitor -s n -l namespace --description '.'
complete -c ndctl-monitor -s l -l log --description '.'
complete -c ndctl-monitor -s c -l config-file --description '.'
complete -c ndctl-monitor -l daemon --description '.'
complete -c ndctl-monitor -s D -l dimm-event --description '.'
complete -c ndctl-monitor -s p -l poll --description '.'
complete -c ndctl-monitor -s u -l human --description '.'
complete -c ndctl-monitor -s v -l verbose --description '.'

