# ndctl-read-infoblock
# Autogenerated from man page /usr/share/man/man1/ndctl-read-infoblock.1.gz
complete -c ndctl-read-infoblock -l bus -l region --description '.'
complete -c ndctl-read-infoblock -s V -l verify --description '.'
complete -c ndctl-read-infoblock -s o -l output --description '.'
complete -c ndctl-read-infoblock -s j -l json --description '.'
complete -c ndctl-read-infoblock -s u -l human --description '.'
complete -c ndctl-read-infoblock -s r --description '.'

