# nemesis-ethernet
# Autogenerated from man page /usr/share/man/man1/nemesis-ethernet.1.gz
complete -c nemesis-ethernet -s d --description 'Specify the name (for UNIX-like systems) or the number (for Windows systems) …'
complete -c nemesis-ethernet -s H --description 'Specify the source-MAC-address (XX:XX:XX:XX:XX:XX).'
complete -c nemesis-ethernet -s M --description 'Specify the destintion-MAC-address (XX:XX:XX:XX:XX:XX).'
complete -c nemesis-ethernet -s P --description 'This will cause nemesis-ethernet to use the specified payload-file as the pay…'
complete -c nemesis-ethernet -s T --description 'Specify the Ethernet-type as an integer.'
complete -c nemesis-ethernet -s v --description 'Display the injected packet in human readable form.'
complete -c nemesis-ethernet -s Z --description 'Lists the available network interfaces by number for use in link-layer  injec…'

