# netdiscover
# Autogenerated from man page /usr/share/man/man8/netdiscover.8.gz
complete -c netdiscover -s i --description 'The network interface to sniff and inject packets.'
complete -c netdiscover -s r --description 'Scan a given range instead of auto scan.'
complete -c netdiscover -s l --description 'Scan ranges contained on the given file.'
complete -c netdiscover -s p --description 'Enable passive mode.'
complete -c netdiscover -s m --description 'Scan a list of known MACs and host names.'
complete -c netdiscover -s F --description 'Customize pcap filter expression (default: "arp").'
complete -c netdiscover -s s --description 'Sleep given time in milliseconds between each ARP request injection.'
complete -c netdiscover -s c --description 'Number of times to send each ARP request.'
complete -c netdiscover -s n --description 'Last IP octet of the source IP used for scanning.'
complete -c netdiscover -s d --description 'Ignore configuration files at home dir (for autoscan and fast mode only).'
complete -c netdiscover -s f --description 'Enable fast mode scan.  This will only scan for . 1, . 100 and .'
complete -c netdiscover -s P --description 'Produces an output suitable to be redirected into a file or to be parsed by a…'
complete -c netdiscover -s L --description 'Similar to -P but continue program execution to capture ARP packets passively…'
complete -c netdiscover -s N --description 'Do not print header.  Only valid when -P or -L is enabled.'
complete -c netdiscover -s S --description '(DEPRECATED) Enable sleep time suppression between each request.'

