# nfanon
# Autogenerated from man page /usr/share/man/man1/nfanon.1.gz
complete -c nfanon -s r --description 'Read input data from inputfile.  Default is read from stdin.'
complete -c nfanon -s R --description 'Read input from a sequence of files in the same directory.'
complete -c nfanon -s M --description 'Read input from multiple directories.'
complete -c nfanon -s w --description 'If specified writes anonymised netflow records to outputfile.'
complete -c nfanon -s K --description 'The key is used to initialize the Rijndael cipher.'

