# nfc-barcode
# Autogenerated from man page /usr/share/man/man1/nfc-barcode.1.gz
complete -c nfc-barcode -s d --description 'Decode content, if possible.'
complete -c nfc-barcode -s v --description 'Verbose.'

