# nfc-relay-picc
# Autogenerated from man page /usr/share/man/man1/nfc-relay-picc.1.gz
complete -c nfc-relay-picc -s h --description '    Help     List options.'
complete -c nfc-relay-picc -s q --description '    Quiet mode     Suppress printing of relayed data (improves timing).'
complete -c nfc-relay-picc -s t --description '    Target mode only (to be used on reader side)     Commands are sent to fil…'
complete -c nfc-relay-picc -s i --description '    Initiator mode only (to be used on tag side)     Commands are read from f…'
complete -c nfc-relay-picc -s n --description '    Adds a waiting time of N seconds (integer) in the loop.'

