# nfc-list
# Autogenerated from man page /usr/share/man/man1/nfc-list.1.gz
complete -c nfc-list -s v --description 'Tells  nfc-list to be verbose and display detailed information about the targ…'
complete -c nfc-list -s t --description 'Polls only for types according to bitfield value of X:    1: ISO14443A    2: …'

