# nfc-read-forum-tag3
# Autogenerated from man page /usr/share/man/man1/nfc-read-forum-tag3.1.gz
complete -c nfc-read-forum-tag3 -s o --description 'FILE : output extracted NDEF Message to FILE (use.'
complete -c nfc-read-forum-tag3 -s q --description ': be quiet, don\'t display Attribute Block parsing info.'

