# nfc-mfsetuid
# Autogenerated from man page /usr/share/man/man1/nfc-mfsetuid.1.gz
complete -c nfc-mfsetuid -s f --description 'Format.  Wipe all data (set to 0xFF) and reset ACLs to defaults.'
complete -c nfc-mfsetuid -s q --description 'Quiet.  Suppress output of commands and responses.'

