# nfexpire
# Autogenerated from man page /usr/share/man/man1/nfexpire.1.gz
complete -c nfexpire -s l --description 'List current data statistics in directory datadir.'
complete -c nfexpire -s r --description 'Rescan the specified directory to update the statfile.'
complete -c nfexpire -s e --description 'Expire files in the specified directory.'
complete -c nfexpire -s s --description 'Set size limit for the directory.'
complete -c nfexpire -s t --description 'Sets the max life time for files in the directory.'
complete -c nfexpire -s u --description 'Updates the max size and lifetime limits, specified by -s -t and -w and store…'
complete -c nfexpire -s w --description 'Set the water mark in % for expiring data.'
complete -c nfexpire -s h --description 'Print help text on stdout with all options and exit.'
complete -c nfexpire -s p --description 'Directories specified by -e, -l and -r are interpreted as profile directories.'
complete -c nfexpire -s Y --description 'Print result in parseable format.  Only NfSen will need this option.'

