# nfreplay
# Autogenerated from man page /usr/share/man/man1/nfreplay.1.gz
complete -c nfreplay -s H --description 'Send all flows to this remote host.'
complete -c nfreplay -s j --description 'Join this multicast group and send all flows to this group host.'
complete -c nfreplay -s p --description 'Send all flows to this port on the remote side.  Default is 9995.'
complete -c nfreplay -s 4 --description 'Forces nfreplay to send flows to a IPv4 address only.'
complete -c nfreplay -s 6 --description 'Forces nfreplay to send flows to a IPv6 address only.'
complete -c nfreplay -s v --description 'Send flows as netflow version num.  5 and 9 are supported.'
complete -c nfreplay -s d --description 'Delay each record by usec mirco seconds, to avoid overrun on the remote side.'
complete -c nfreplay -s b --description 'Set send buffer size in bytes.  Useful for large data to transfer.'
complete -c nfreplay -s r --description 'Read input data from inputfile.  Default is read from stdin.'
complete -c nfreplay -s t --description 'Send only flows, which fall in the time window timewin, where timewin is YYYY…'
complete -c nfreplay -s c --description 'Limit number of records to send to the first num flows.'
complete -c nfreplay -s V --description 'Print nfreplay version and exit.'
complete -c nfreplay -s h --description 'Print help text on stdout with all options and exit.'

