# nfsconf
# Autogenerated from man page /usr/share/man/man8/nfsconf.8.gz
complete -c nfsconf -s v -l verbose --description 'Increase verbosity and print debugging information.'
complete -c nfsconf -s f -l file --description 'Select a different config file to operate upon, default is  /etc/nfs. conf .'
complete -c nfsconf -s d -l dump --description 'Output an alphabetically sorted dump of the current configuration in conf fil…'
complete -c nfsconf -s i -l isset --description 'Test if a specific tag has a value set.'
complete -c nfsconf -s g -l get --description 'Output the current value of the specified tag.'
complete -c nfsconf -s s -l set --description 'Update or Add a tag and value to the config file in a specified section, crea…'
complete -c nfsconf -s u -l unset --description 'Remove the specified tag and its value from the config file.'
complete -c nfsconf -s a -l arg --description 'Select a specific sub-section Options only valid in --set mode.'
complete -c nfsconf -s m -l modified --description 'Set the text on the Modified date comment in the file.'

