# nfsd
# Autogenerated from man page /usr/share/man/man8/nfsd.8.gz
complete -c nfsd -s d -l debug --description 'enable logging of debugging messages.'
complete -c nfsd -s H -l host --description 'specify a particular hostname (or address) that NFS requests will be accepted…'
complete -c nfsd -s p -l port --description 'specify a different port to listen on for NFS requests.  By default,  rpc.'
complete -c nfsd -s r -l rdma --description 'specify that NFS requests on the standard RDMA port ("nfsrdma", port 20049) s…'
complete -c nfsd -s N -l no-nfs-version --description 'This option can be used to request that   rpc.'
complete -c nfsd -s s -l syslog --description 'By default,  rpc.'
complete -c nfsd -s t -l tcp --description 'Instruct the kernel nfs server to open and listen on a TCP socket.'
complete -c nfsd -s T -l no-tcp --description 'Instruct the kernel nfs server not to open and listen on a TCP socket.'
complete -c nfsd -s u -l udp --description 'Instruct the kernel nfs server to open and listen on a UDP socket.'
complete -c nfsd -s U -l no-udp --description 'Instruct the kernel nfs server not to open and listen on a UDP socket.'
complete -c nfsd -s V -l nfs-version --description 'This option can be used to request that   rpc.'
complete -c nfsd -s L -l lease-time --description 'Set the lease-time used for NFSv4.'
complete -c nfsd -s G -l grace-time --description 'Set the grace-time used for NFSv4 and NLM (for NFSv2 and NFSv3).'

