# ninfod
# Autogenerated from man page /usr/share/man/man8/ninfod.8.gz
complete -c ninfod -s d --description 'Debug mode.  Do not go background.'
complete -c ninfod -s h --description 'Show help.'
complete -c ninfod -s v --description 'Verbose mode.'
complete -c ninfod -s u --description 'Run as another user.  user can either be username or user ID.'
complete -c ninfod -s p --description 'File for process-id storage.  user is required to be able to create the file.'
complete -c ninfod -s V --description 'Print version and exit.'

