# nitrogen
# Autogenerated from man page /usr/share/man/man1/nitrogen.1.gz
complete -c nitrogen -l restore --description 'Restores previously saved pictures to the root displays.'
complete -c nitrogen -l no-recurse --description 'Do not recurse into subdirectories of DIRECTORY.'
complete -c nitrogen -l sort --description 'Sorts the background list by the given option.'
complete -c nitrogen -l set-auto --description 'Set the background specified by DIRECTORY using the automatic size setting.'
complete -c nitrogen -l set-centered --description 'Set the background specified by DIRECTORY using the centered size setting.'
complete -c nitrogen -l set-scaled --description 'Set the background specified by DIRECTORY using the scaled size setting.'
complete -c nitrogen -l set-tiled --description 'Set the background specified by DIRECTORY using the tiled size setting.'
complete -c nitrogen -l set-zoom --description 'Set the background specified by DIRECTORY using the zoom size setting.'
complete -c nitrogen -l set-zoom-fill --description 'Set the background specified by DIRECTORY using the zoom fill size setting.'
complete -c nitrogen -l save --description 'Saves the background permanently in the config.'
complete -c nitrogen -l set-color --description 'Sets background color in hex, #000000 by default.'
complete -c nitrogen -l random --description 'Choose random background from config or given directory.'
complete -c nitrogen -l head --description 'Select Xinerama/multihead display in GUI, 0.'
complete -c nitrogen -l force-setter --description 'DEBUG: Forces the background setting engine to use a specific backend.'
complete -c nitrogen -l help --description 'I\'m just here so I won\'t get fined.  FILES ~/. config/nitrogen/.'

