# nsntrace
# Autogenerated from man page /usr/share/man/man1/nsntrace.1.gz
complete -c nsntrace -l device -s d --description 'The network device to use in trace.'
complete -c nsntrace -l outfile -s o --description 'Write the trace output to the file file.  Default is nsntrace. pcap.'
complete -c nsntrace -l user -s u --description 'Run program with the user ID, group ID and supplementary groups of user.'
complete -c nsntrace -l filter -s f --description 'The capture filter to use while capturing.'

