# nss-mymachines
# Autogenerated from man page /usr/share/man/man8/nss-mymachines.8.gz
complete -c nss-mymachines -l private-network --description 'in systemd-nspawn(1)).'
complete -c nss-mymachines -l private-users --description 'in systemd-nspawn(1)).'

