# oathtool
# Autogenerated from man page /usr/share/man/man1/oathtool.1.gz
complete -c oathtool -s h -l help --description 'Print help and exit.'
complete -c oathtool -s V -l version --description 'Print version and exit.'
complete -c oathtool -l hotp --description 'use event-based HOTP mode  (default=on).'
complete -c oathtool -l totp --description 'use time-variant TOTP mode  (possible values="sha1", "sha256", "sha512" defau…'
complete -c oathtool -s b -l base32 --description 'use base32 encoding of KEY instead of hex (default=off).'
complete -c oathtool -s c -l counter --description 'HOTP counter value.'
complete -c oathtool -s s -l time-step-size --description '(default=`30s\').'
complete -c oathtool -s S -l start-time --description 'when to start counting time steps for TOTP (default=`1970-01-01 00:00:00 UTC\'…'
complete -c oathtool -s N -l now --description 'use this time as current time for TOTP (default=`now\').'
complete -c oathtool -s d -l digits --description 'number of digits in one-time password.'
complete -c oathtool -s w -l window --description 'window of counter values to test when validating OTPs.'
complete -c oathtool -s v -l verbose --description 'explain what is being done  (default=off) EXAMPLES To generate the first even…'

