# obenergy
# Autogenerated from man page /usr/share/man/man1/obenergy.1.gz
complete -c obenergy -s v --description 'Verbose: print out all individual energy interactions.'
complete -c obenergy -o ff --description 'Select the forcefield El EXAMPLES Pp View the possible options, including ava…'

