# obexftpd
# Autogenerated from man page /usr/share/man/man1/obexftpd.1.gz
complete -c obexftpd -s i -l irda --description 'Acceopt connections using the IrDA protocol.'
complete -c obexftpd -s b -l bluetooth --description 'Accept connections via bluetooth.'
complete -c obexftpd -s t -l tty --description 'Accept connections from this tty device.  NOT WORKING!.'
complete -c obexftpd -s n -l network --description 'Accept connections from the network to this port.'
complete -c obexftpd -s c -l chdir --description 'Set the base directory for the server.'
complete -c obexftpd -s v -l verbose --description 'Be verbose and give some additional infos.'
complete -c obexftpd -s V -l version --description 'Print version string and exit.'
complete -c obexftpd -s h -l help -l usage --description 'Print short usage instructions.'

