# obgrep
# Autogenerated from man page /usr/share/man/man1/obgrep.1.gz
complete -c obgrep -s c --description 'Print the number of matches.'
complete -c obgrep -s f --description 'Full match, print matching-molecules only when the number of heavy atoms is a…'
complete -c obgrep -s i --description 'Specifies input and output format, see obabel 1 for available formats.'
complete -c obgrep -s n --description 'Only print the name of the molecules.'
complete -c obgrep -s t --description 'Print a molecule only if the pattern occurs # times inside the molecule.'
complete -c obgrep -s v --description 'Invert the matching, print non-matching molecules El EXAMPLES Note that in al…'

