# objres
# Autogenerated from man page /usr/share/man/man1/objres.1.gz
complete -c objres -s o -l output --description 'Set the name of the target object file to R FILENAME .'
complete -c objres -s h -l header --description 'Set the name of the header file to R FILENAME .'
complete -c objres -s m -l machine --description 'Set the target object file to be either a 32-bit ELF object or a 64-bit ELF o…'
complete -c objres -s R -l reference --description 'Examine the object file R OBJFILE , and copy the fields from its ELF header t…'
complete -c objres -s r -l read-only --description 'Place the binary objects in read-only memory.'
complete -c objres -l help --description 'Display help and exit.'
complete -c objres -l version --description 'Display version information and exit.'

