# obprobe
# Autogenerated from man page /usr/share/man/man1/obprobe.1.gz
complete -c obprobe -s s --description 'Set the resolution of the grid (stepsize).'
complete -c obprobe -s p --description 'Set the padding -- extra distance on each side of the box formed by the molec…'

