# obspectrophore
# Autogenerated from man page /usr/share/man/man1/obspectrophore.1.gz
complete -c obspectrophore -s i --description 'Specifies the molecular input file from which Spectrophores are to be calcula…'
complete -c obspectrophore -s n --description 'Specifies the kind of normalization that should be performed.'
complete -c obspectrophore -s a --description 'Specifies the required accuracy expressed as the angular stepsize.'
complete -c obspectrophore -s s --description 'Specifies the kind of cages that should be used in terms of the underlying po…'
complete -c obspectrophore -s r --description 'Specifies the required resolution expressed as a real positive number.'
complete -c obspectrophore -s u --description 'Display implementation details.'
complete -c obspectrophore -s h --description 'Display help message.  El SEE ALSO obabel 1.'

