# obthermo
# Autogenerated from man page /usr/share/man/man1/obthermo.1.gz
complete -c obthermo -l symm --description 'override symmetry number used in input file.'
complete -c obthermo -l nrot --description 'number of rotatable bonds for conformational entropy.'
complete -c obthermo -l dbdt --description 'temperature derivative of second virial coefficient for cp calculation.'
complete -c obthermo -l kj --description 'output kJ/mol related units (default kcal/mol) El SEE ALSO obabel 1.'

