# ofs2rva
# Autogenerated from man page /usr/share/man/man1/ofs2rva.1.gz
complete -c ofs2rva -s v -l version --description 'show program version and exit.'
complete -c ofs2rva -l help --description 'show help.'

