# onnode
# Autogenerated from man page /usr/share/man/man1/onnode.1.gz
complete -c onnode -s c --description 'Execute COMMAND in the current working directory on the specified nodes.'
complete -c onnode -s f --description 'Specify an alternative nodes FILENAME to use instead of the default.'
complete -c onnode -s i --description 'Keep standard input open, allowing data to be piped to onnode.'
complete -c onnode -s n --description 'Allow nodes to be specified by name rather than node numbers.'
complete -c onnode -s p --description 'Run COMMAND in parallel on the specified nodes.'
complete -c onnode -s P --description 'Push files to nodes.'
complete -c onnode -s q --description 'Do not print node addresses.'
complete -c onnode -s v --description 'Print node addresses even if only one node is specified.'
complete -c onnode -s h -l help --description 'Show a short usage guide.'

