# openvas-nasl
# Autogenerated from man page /usr/share/man/man1/openvas-nasl.1.gz
complete -c openvas-nasl -s T --description 'Makes nasl write verbosely what the script does in the file  tracefile , ala …'
complete -c openvas-nasl -s t --description 'Apply the NASL script to  target which may be a single host (127. 0. 0.'
complete -c openvas-nasl -s e --description 'Specifies the network interface to be used as the source for established conn…'
complete -c openvas-nasl -s s --description 'Sets the return value of safe_checks() to 1.'
complete -c openvas-nasl -s D --description 'Only run the description part of the script.'
complete -c openvas-nasl -s B --description 'Runs in description mode before running the script.'
complete -c openvas-nasl -s L --description 'Lint  the script  (run extended checks).'
complete -c openvas-nasl -s X --description 'Run the script with disabled signature verification.'
complete -c openvas-nasl -s h --description 'Show help.'
complete -c openvas-nasl -s v --description 'Show the version of NASL.'
complete -c openvas-nasl -s d --description 'Output debug information to stderr.'
complete -c openvas-nasl -s k --description 'Set KB key to value.  Can be used multiple times.'

