# openbox
# Autogenerated from man page /usr/share/man/man1/openbox.1.gz
complete -c openbox -l help --description 'Show a summary of the command line options available  and exit.'
complete -c openbox -l version --description 'Show the version of the program and exit.'
complete -c openbox -l replace --description 'Replace the currently running window manager.'
complete -c openbox -l config-file --description 'Specify the path to the config file to use.'
complete -c openbox -l reconfigure --description 'If Openbox is already running on the display, tell it to  reload its configur…'
complete -c openbox -l restart --description 'If Openbox is already running on the display, tell it to  restart.'
complete -c openbox -l exit --description 'Exit Openbox.'
complete -c openbox -l sm-disable --description 'Do not connect to the session manager.'
complete -c openbox -l sync --description 'Run in synchronous mode (for debugging).'
complete -c openbox -l startup --description 'Run CMD after starting.'
complete -c openbox -l debug --description 'Display debugging output.'
complete -c openbox -l debug-focus --description 'Display debugging output for focus handling.'
complete -c openbox -l debug-session --description 'Display debugging output for session management.'

