# oscap-vm
# Autogenerated from man page /usr/share/man/man8/oscap-vm.8.gz
complete -c oscap-vm -l report -l results --description '.'
complete -c oscap-vm -l profile --description '/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.'

