# osql
# Autogenerated from man page /usr/share/man/man1/osql.1.gz
complete -c osql -s S --description 'the Data Source Name to which to connect, as known to odbc. ini Ns.'
complete -c osql -s U --description 'database login name.'
complete -c osql -s P --description 'database password.'
complete -c osql -s I --description 'override odbc. ini file location.  El EXAMPLE If you have an odbc.'

