# outguess
# Autogenerated from man page /usr/man/man1/outguess.1.gz
complete -c outguess -s F --description 'Specifies that OutGuess should preserve statistics based on frequency counts.'
complete -c outguess -o kK --description 'Specify the secret key used to encrypt and hide the message in the provided d…'
complete -c outguess -o dD --description 'Specify the filename containing a message to be hidden in the data.'
complete -c outguess -o sS --description 'Specify the initial seed the iterator object uses for selecting bits in the r…'
complete -c outguess -o iI --description 'Specify the upper limit for finding an optimal iterator seed.'
complete -c outguess -o eE --description 'Use error correction for data encoding and decoding.'
complete -c outguess -s r --description 'Retrieve a message from a data object.'
complete -c outguess -s x --description 'If the second key does not create an iterator object that is successful in em…'
complete -c outguess -s p --description 'Passes a string as parameter to the destination data handler.'
complete -c outguess -s m --description 'Mark pixels that have been modified.'
complete -c outguess -s t --description 'Collect statistics about redundant bit usage.'
complete -c outguess -s d --description 'hidden. txt monkey. jpg out. jpg.'
complete -c outguess -s E -s K --description '"secret2".'
complete -c outguess -s D --description 'hide2. txt monkey. jpg out. jpg.'
complete -c outguess -s e --description 'out. jpg message. txt.'

