# pa-applet
# Autogenerated from man page /usr/share/man/man1/pa-applet.1.gz
complete -c pa-applet -o h/--help --description 'Display usage information and exit.'
complete -c pa-applet -l disable-key-grabbing --description 'Don\'t attempt to grab volume keys.'
complete -c pa-applet -l disable-notifications --description 'Don\'t attempt to display notifications SEE ALSO pacmd(1), padevchooser(1), pa…'

