# pacfile
# Autogenerated from man page /usr/share/man/man1/pacfile.1.gz
complete -c pacfile -l config --description 'Set an alternate configuration file path.'
complete -c pacfile -l dbpath --description 'Set an alternate database path.'
complete -c pacfile -l root --description 'Set an alternate installation root.'
complete -c pacfile -l sysroot --description 'Set an alternate system root.   See pacutils-sysroot\\|(7).'
complete -c pacfile -l package --description 'Limit information to the specified package.   May be specified multiple times.'
complete -c pacfile -l check --description 'Compare database values to the file system.'
complete -c pacfile -l help --description 'Display usage information and exit.'

