# pacini
# Autogenerated from man page /usr/share/man/man1/pacini.1.gz
complete -c pacini -l section --description 'Only display directives listed in section name.'
complete -c pacini -l section-list --description 'List configured sections.'
complete -c pacini -l verbose --description 'Always show directive names even if only one directive is provided.'
complete -c pacini -l help --description 'Display usage information and exit.'

