# paclog
# Autogenerated from man page /usr/share/man/man1/paclog.1.gz
complete -c paclog -l config --description 'Set an alternate configuration file path.'
complete -c paclog -l logfile --description 'Set an alternate log file path.'
complete -c paclog -l root --description 'Set an alternate installation root.'
complete -c paclog -l sysroot --description 'Set an alternate system root.   See pacutils-sysroot\\|(7).'
complete -c paclog -l color --description 'Colorize output.'
complete -c paclog -l pkglist --description 'Print the list of installed packages according to the log.'
complete -c paclog -l help --description 'Display usage information and exit.'
complete -c paclog -l version --description 'Display version information and exit. SS "Filters".'
complete -c paclog -l action --description 'Display package operations.'
complete -c paclog -l after -l before --description 'Display entries after/before date.'
complete -c paclog -l caller --description 'Display log entries from name.   May be specified multiple times.'
complete -c paclog -l commandline --description 'Display pacman-style logged commandline entries.'
complete -c paclog -l grep --description 'Display log entries whose message matches regex.'
complete -c paclog -l package --description 'Display logged actions affecting pkgname.   May be specified multiple times.'

