# pacrepairdb
# Autogenerated from man page /usr/share/man/man1/pacrepairdb.1.gz
complete -c pacrepairdb -l cachedir --description 'Set an alternate cache directory path.'
complete -c pacrepairdb -l config --description 'Set an alternate configuration file path.'
complete -c pacrepairdb -l dbonly --description 'Make the changes to the database without actually extracting or removing any …'
complete -c pacrepairdb -l dbpath --description 'Set an alternate database path.'
complete -c pacrepairdb -l debug --description 'Display additional debugging information.'
complete -c pacrepairdb -l hookdir --description 'Add additional user hook directories.'
complete -c pacrepairdb -l logfile --description 'Set an alternate log file path.'
complete -c pacrepairdb -l no-confirm --description 'Assume default responses to all prompts.'
complete -c pacrepairdb -l no-scriptlet --description 'Do not run package install scripts.'
complete -c pacrepairdb -l no-hooks --description 'Do not run transaction hooks.'
complete -c pacrepairdb -l no-timeout --description 'Disable low-speed timeouts for downloads.'
complete -c pacrepairdb -l print-only --description 'Display the packages to be repaired and the cache packages to be used and exi…'
complete -c pacrepairdb -l root --description 'Set an alternate installation root.'
complete -c pacrepairdb -l sysroot --description 'Set an alternate system root.   See pacutils-sysroot\\|(7).'
complete -c pacrepairdb -l verbose --description 'Display additional progress information.'
complete -c pacrepairdb -l help --description 'Display usage information and exit.'

