# pacreport
# Autogenerated from man page /usr/share/man/man1/pacreport.1.gz
complete -c pacreport -l config --description 'Set an alternate pacman configuration file path.'
complete -c pacreport -l dbext --description 'Set an alternate sync database extension.'
complete -c pacreport -l dbpath --description 'Set an alternate database path.'
complete -c pacreport -l root --description 'Set an alternate installation root.'
complete -c pacreport -l sysroot --description 'Set an alternate system root.   See pacutils-sysroot\\|(7).'
complete -c pacreport -l cache-dir --description 'Set an alternate cache directory path.'
complete -c pacreport -l backups --description 'Search for . pac{save,orig,new} files.'
complete -c pacreport -l group --description 'Display any packages in group name that are not currently installed.'
complete -c pacreport -l missing-files --description 'Check for missing package files.'
complete -c pacreport -l unowned-files --description 'Check for unowned files.   See /etc/pacreport.'
complete -c pacreport -l optional-deps --description 'Take optional dependencies into account when listing unneeded packages and de…'
complete -c pacreport -l help --description 'Display usage information and exit.'

