# pacsync
# Autogenerated from man page /usr/share/man/man1/pacsync.1.gz
complete -c pacsync -l config --description 'Set an alternate configuration file path.'
complete -c pacsync -l dbext --description 'Set an alternate sync database extension.'
complete -c pacsync -l dbpath --description 'Set an alternate database path.'
complete -c pacsync -l logfile --description 'Set an alternate log file path.'
complete -c pacsync -l no-timeout --description 'Disable low-speed timeouts for downloads.'
complete -c pacsync -l root --description 'Set an alternate installation root.'
complete -c pacsync -l sysroot --description 'Set an alternate system root.   See pacutils-sysroot\\|(7).'
complete -c pacsync -l debug --description 'Display additional debugging information.'
complete -c pacsync -l updated --description 'Return true only if a database was actually updated.'
complete -c pacsync -l force --description 'Update databases even if already up-to-date.'
complete -c pacsync -l help --description 'Display usage information and exit.'

