# pacstrap
# Autogenerated from man page /usr/share/man/man8/pacstrap.8.gz
complete -c pacstrap -s C --description 'Use an alternate config file for pacman.'
complete -c pacstrap -s c --description 'Use the package cache on the host, rather than the target.'
complete -c pacstrap -s G --description 'Avoid copying the host\\(cqs pacman keyring to the target.'
complete -c pacstrap -s i --description 'Prompt for package confirmation when needed (run interactively).'
complete -c pacstrap -s M --description 'Avoid copying the host\\(cqs mirrorlist to the target.'
complete -c pacstrap -s U --description 'Use pacman -U to install packages.'
complete -c pacstrap -s h --description 'Output syntax and command line options.'

