# pam_systemd_home
# Autogenerated from man page /usr/share/man/man8/pam_systemd_home.8.gz
complete -c pam_systemd_home -o auth --description 'auth      required   pam_deny. so.'
complete -c pam_systemd_home -o account --description 'account   sufficient pam_unix. so account   required   pam_permit. so.'
complete -c pam_systemd_home -o password --description 'password  sufficient pam_unix.'
complete -c pam_systemd_home -o session --description '.'

