# paratrace
# Autogenerated from man page /usr/share/man/man1/paratrace.1.gz
complete -c paratrace -s s --description '"Overshoot" target host by a number of hops equal to the hopfuzz.'
complete -c paratrace -s t --description 'Set maximum number of seconds that may pass before listening process gives up…'
complete -c paratrace -s b --description 'Limit the amount of bandwidth that scanrand may use for its outgoing requests.'
complete -c paratrace -s n --description 'Specify network, instead of host, to attach a parasitic trace to.'
complete -c paratrace -s N --description 'Use Reverse-DNS to determine a DNS host name that matches the source of a det…'
complete -c paratrace -o NN --description 'Use Reverse-DNS to determine a DNS host name that matches the intended destin…'
complete -c paratrace -s v --description 'Verbosity Level 1:  Mark the sending of packets.'
complete -c paratrace -o vv --description 'Verbosity Level 2:  Output all interpreted TCP and IP headers. Sp .'
complete -c paratrace -s d --description 'Use this Layer 2 Device for all traffic.'
complete -c paratrace -s i --description 'Use this Layer 3 Source IP for all traffic.'

