# paris-traceroute
# Autogenerated from man page /usr/share/man/man1/paris-traceroute.1.gz
complete -c paris-traceroute -s h -l 'help							Displays' --description '.'
complete -c paris-traceroute -o 'a<ALGORITHM>' -l algorithm --description '.'

