# pbmtoescp2
# Autogenerated from man page /usr/share/man/man1/pbmtoescp2.1.gz
complete -c pbmtoescp2 -o compress --description 'This determines the compression mode that pbmtoescp2 uses in its output.'
complete -c pbmtoescp2 -o resolution --description 'This determines the horizontal and the vertical print resolution set in the p…'

