# pdfcrack
# Autogenerated from man page /usr/share/man/man1/pdfcrack.1.gz
complete -c pdfcrack -s b -l bench --description 'perform benchmark and exit.'
complete -c pdfcrack -s c -l charset --description 'Use the characters in STRING as charset.'
complete -c pdfcrack -s w -l wordlist --description 'Use FILE as source of passwords to try.'
complete -c pdfcrack -s n -l minpw --description 'Skip trying passwords shorter than INTEGER.'
complete -c pdfcrack -s m -l maxpw --description 'Stop when reaching this INTEGER passwordlength.'
complete -c pdfcrack -s l -l loadstate --description 'Continue from the state saved in FILE.'
complete -c pdfcrack -s o -l owner --description 'Work with the ownerpassword.'
complete -c pdfcrack -s u -l user --description 'Work with the userpassword (default).'
complete -c pdfcrack -s p -l password --description 'Give userpassword to speed up breaking ownerpassword (implies -o).'
complete -c pdfcrack -s q -l quiet --description 'Run quietly.'
complete -c pdfcrack -s s -l permutate --description 'Try permutating the passwords (currently only supports switching first charac…'
complete -c pdfcrack -s v -l version --description 'Print version and exit REPORTING BUGS Via e-mail to Henning Noren <confusion4…'

