# pdfresurrect
# Autogenerated from man page /usr/share/man/man1/pdfresurrect.1.gz
complete -c pdfresurrect -s w --description 'Write the PDF versions and summary to disk.'
complete -c pdfresurrect -s q --description 'Display only the number of versions contained in the PDF.'
complete -c pdfresurrect -s s --description 'Scrub the previous history data from the specified PDF.'
complete -c pdfresurrect -s i --description 'Display the creator information from the specified PDF.'

