# peres
# Autogenerated from man page /usr/share/man/man1/peres.1.gz
complete -c peres -s a -l all --description 'show all information, statistics and extract resources.'
complete -c peres -s x -l extract --description 'extract resources.'
complete -c peres -s i -l info --description 'show resources information.'
complete -c peres -s s -l statistics --description 'show resource section statistics.'
complete -c peres -s v -l version --description 'show program version and exit.'
complete -c peres -l help --description 'show help.'

