# permview
# Autogenerated from man page /usr/share/man/man1/permview.1.gz
complete -c permview -o output --description 'Output all declarative security attributes related informations into the spec…'
complete -c permview -o xml -l xml --description 'Output all declarative security attributes in an XML format.'
complete -c permview -o decl -l decl --description 'Show declarative security attributes on classes and methods.'
complete -c permview -s '?' -s h --description 'Display help informations about the permview tool.'

