# pescan
# Autogenerated from man page /usr/share/man/man1/pescan.1.gz
complete -c pescan -s f -l 'format<text' --description 'change output format (default is text).'
complete -c pescan -s v -l version --description 'show program version and exit.'
complete -c pescan -l format --description 'change output format (default is text).'
complete -c pescan -l help --description 'show help.'

