# pestr
# Autogenerated from man page /usr/share/man/man1/pestr.1.gz
complete -c pestr -s n -l min-length --description 'set the minimun number of characteres to be read as string.'
complete -c pestr -s o -l offset --description 'display the raw file offset where string starts.'
complete -c pestr -l net --description 'filter network-related strings (IP addresses, domains etc).'
complete -c pestr -s v -l version --description 'show program version and exit.'
complete -c pestr -l help --description 'show help.'

