# phrasendrescher
# Autogenerated from man page /usr/share/man/man1/phrasendrescher.1.gz
complete -c phrasendrescher -s h --description 'print help message.'
complete -c phrasendrescher -s v --description 'verbose mode.'
complete -c phrasendrescher -s i --description 'incremental mode beginning with word length `from\' and going to `to\'.'
complete -c phrasendrescher -s d --description 'run dictionary based with words from `file\'.'
complete -c phrasendrescher -s w --description 'number of worker threads (default is one).'
complete -c phrasendrescher -s r --description 'use rules to rewrite dictionary words Rewriting rules:.'

