# ping_pong
# Autogenerated from man page /usr/share/man/man1/ping_pong.1.gz
complete -c ping_pong -s r --description 'test read performance.'
complete -c ping_pong -s w --description 'test write performance.'
complete -c ping_pong -s m --description 'use mmap.'
complete -c ping_pong -s c --description 'validate the locks.'

