# pip-debug
# Autogenerated from man page /usr/share/man/man1/pip-debug.1.gz
complete -c pip-debug -l platform --description 'Only use wheels compatible with <platform>.'
complete -c pip-debug -l python-version --description 'The Python interpreter version to use for wheel and "Requires-Python" compati…'
complete -c pip-debug -l implementation --description 'Only use wheels compatible with Python implementation <implementation>, e. g.'
complete -c pip-debug -l abi --description 'Only use wheels compatible with Python abi <abi>, e. g.  \\(aqpypy_41\\(aq.'

