# pip2-list
# Autogenerated from man page /usr/share/man/man1/pip2-list.1.gz
complete -c pip2-list -s o -l outdated --description 'List outdated packages.'
complete -c pip2-list -s u -l uptodate --description 'List uptodate packages.'
complete -c pip2-list -s e -l editable --description 'List editable projects.'
complete -c pip2-list -s l -l local --description 'If in a virtualenv that has global access, do not list globally-installed pac…'
complete -c pip2-list -l user --description 'Only output packages installed in user-site.'
complete -c pip2-list -l path --description 'Restrict to the specified installation path for listing packages (can be used…'
complete -c pip2-list -l pre --description 'Include pre-release and development versions.'
complete -c pip2-list -l format --description 'Select the output format among: columns (default), freeze, or json.'
complete -c pip2-list -l not-required --description 'List packages that are not dependencies of installed packages.'
complete -c pip2-list -l exclude-editable --description 'Exclude editable package from output.'
complete -c pip2-list -l include-editable --description 'Include editable package from output.'

