# pip2-freeze
# Autogenerated from man page /usr/share/man/man1/pip2-freeze.1.gz
complete -c pip2-freeze -s r -l requirement --description 'Use the order in the given requirements file and its comments when generating…'
complete -c pip2-freeze -s f -l find-links --description 'URL for finding packages, which will be added to the output.'
complete -c pip2-freeze -s l -l local --description 'If in a virtualenv that has global access, do not output globally-installed p…'
complete -c pip2-freeze -l user --description 'Only output packages installed in user-site.'
complete -c pip2-freeze -l path --description 'Restrict to the specified installation path for listing packages (can be used…'
complete -c pip2-freeze -l all --description 'Do not skip these packages in the output: wheel, setuptools, pip2, distribute.'
complete -c pip2-freeze -l exclude-editable --description 'Exclude editable package from output.'

