# pip2-search
# Autogenerated from man page /usr/share/man/man1/pip2-search.1.gz
complete -c pip2-search -s i -l index --description 'Base URL of Python Package Index (default \\%https://pypi. org/pypi).'

