# pip2-config
# Autogenerated from man page /usr/share/man/man1/pip2-config.1.gz
complete -c pip2-config -l editor --description 'Editor to use to edit the file.'
complete -c pip2-config -l global --description 'Use the system-wide configuration file only.'
complete -c pip2-config -l user --description 'Use the user configuration file only.'
complete -c pip2-config -l site --description 'Use the current environment configuration file only.'

