# pixd
# Autogenerated from man page /usr/share/man/man1/pixd.gz
complete -c pixd -s r --description 'Range of octets to print from each file.'
complete -c pixd -s w --description 'Number of octets per line, separated into groups (see g ).'

