# png2swf
# Autogenerated from man page /usr/share/man/man1/png2swf.1.gz
complete -c png2swf -s r -l rate --description 'Set movie framerate (frames per second).'
complete -c png2swf -s o -l output --description 'Explicitly specify output file.'
complete -c png2swf -s j -l jpeg --description 'Generate a lossy jpeg bitmap inside the SWF, with a given quality (1-100).'
complete -c png2swf -s z -l zlib --description 'Use Flash MX (SWF 6) Zlib encoding for the output.'
complete -c png2swf -s T -l flashversion --description 'Set the flash version to generate.'
complete -c png2swf -s X -l pixel --description 'Force movie width to width (default: autodetect).'
complete -c png2swf -s Y --description 'Force movie height to height (default: autodetect).'
complete -c png2swf -s v -l verbose --description 'Set verbose level (0=quiet, 1=default, 2=debug).'
complete -c png2swf -s q -l quiet --description 'Omit normal log messages, only log errors.'
complete -c png2swf -s C -l cgi --description 'For use as CGI- prepend http header, write to stdout.'
complete -c png2swf -s V -l version --description 'Print version information and exit.'
complete -c png2swf -s s -l scale --description '    Scale image to percent% size.  AUTHOR.'

