# ponymix
# Autogenerated from man page /usr/share/man/man1/ponymix.1.gz
complete -c ponymix -s c -l card --description 'Specify a card.'
complete -c ponymix -s d -l device --description 'Specify a device other than the default.'
complete -c ponymix -l max-volume --description 'Override the maximum volume ponymix will allow.'
complete -c ponymix -s N -l notify --description 'Create a libnotify notification for volume change events instead of printing …'
complete -c ponymix -s t -l devtype --description 'Specify a device type to examine, usually in conjunction with the --device fl…'
complete -c ponymix -l sink -l output --description 'Aliases to --devtype sink.'
complete -c ponymix -l source -l input --description 'Aliases to --devtype source.'
complete -c ponymix -l source-output --description 'Alias to --devtype source-output.'
complete -c ponymix -l sink-input --description 'Alias to --devtype sink-input.'
complete -c ponymix -l short --description 'Generate output for list commands in a parseable format.'

