# proxy
# Autogenerated from man page /usr/share/man/man8/proxy.8.gz
complete -c proxy -s I --description 'Inetd mode.  Standalone service only.'
complete -c proxy -s d --description 'Daemonise.  Detach service from console and run in the background.'
complete -c proxy -s t --description 'Be silenT.  Do not log start/stop/accept error records.'
complete -c proxy -s u --description 'Never ask for username authentication.'
complete -c proxy -s e --description 'External address.'
complete -c proxy -s i --description 'Internal address.  IP address proxy accepts connections to.'
complete -c proxy -s a --description 'Anonymous.  Hide information about client.'
complete -c proxy -o a1 --description 'Anonymous.  Show fake information about client.'
complete -c proxy -s p --description 'Port.  Port proxy listens for incoming connections.  Default is 3128.'
complete -c proxy -s l --description 'Log.  By default logging is to stdout.'
complete -c proxy -s S --description 'Increase or decrease stack size.'

