# pruneemptydirs
# Autogenerated from man page /usr/share/man/man1/pruneemptydirs.1.gz
complete -c pruneemptydirs -s f --description 'Actually perform the deletions instead of just printing them out.'

