# psk-crack
# Autogenerated from man page /usr/share/man/man1/psk-crack.1.gz
complete -c psk-crack -l help -s h --description 'Display this usage message and exit.'
complete -c psk-crack -l version -s V --description 'Display program version and exit.'
complete -c psk-crack -l verbose -s v --description 'Display verbose progress messages.'
complete -c psk-crack -l dictionary -s d --description 'Set dictionary file to <f>.'
complete -c psk-crack -l norteluser -s u --description 'Specify the username for Nortel Contivity cracking.'
complete -c psk-crack -l bruteforce -s B --description 'Select bruteforce cracking up to <n> characters.'
complete -c psk-crack -l pskcrack --description 'option.'
complete -c psk-crack -l charset -s c --description 'Set bruteforce character set to <s> Default is "0123456789abcdefghijklmnopqrs…'

