# pst2dii
# Autogenerated from man page /usr/share/man/man1/pst2dii.1.gz
complete -c pst2dii -s B --description 'Sets the bates prefix string.'
complete -c pst2dii -s O --description 'Name of the output DII load file.'
complete -c pst2dii -s V --description 'Show program version.  Subsequent options are then ignored.'
complete -c pst2dii -s b --description 'Starting bates sequence number.  The default is zero.'
complete -c pst2dii -s c --description 'Font color for the bates stamp on each page, specified as 6 hex digits as rrg…'
complete -c pst2dii -s d --description 'Specify name of debug log file.'
complete -c pst2dii -s f --description 'Specify name of a true type font file.  This should be a fixed pitch font.'
complete -c pst2dii -s h --description 'Show summary of options.  Subsequent options are then ignored.'
complete -c pst2dii -s o --description 'Specifies the output directory.  The directory must already exist.'

