# pst2ldif
# Autogenerated from man page /usr/share/man/man1/pst2ldif.1.gz
complete -c pst2ldif -s V --description 'Show program version.  Subsequent options are then ignored.'
complete -c pst2ldif -s b --description 'Sets the ldap base value used in the dn records.'
complete -c pst2ldif -s c --description 'Sets the objectClass values for the contact items.'
complete -c pst2ldif -s d --description 'Specify name of debug log file.'
complete -c pst2ldif -s l --description 'Specify an extra line to be added to each ldap entry.'
complete -c pst2ldif -s o --description 'Use the old ldap schema, rather than the default new ldap schema.'
complete -c pst2ldif -s h --description 'Show summary of options.  Subsequent options are then ignored.'

