# pw-inspector
# Autogenerated from man page /usr/share/man/man1/pw-inspector.1.gz
complete -c pw-inspector -s i --description 'file to read passwords from (default: stdin).'
complete -c pw-inspector -s o --description 'file to write valid passwords to (default: stdout).'
complete -c pw-inspector -s m --description 'minimum length of a valid password.'
complete -c pw-inspector -s M --description 'maximum length of a valid password.'
complete -c pw-inspector -s c --description 'the minimum number of sets required (default: all given).'
complete -c pw-inspector -s h -l help --description 'Show summary of options.  SETS.'
complete -c pw-inspector -s l --description 'lowcase characters (a,b,c,d, etc. ).'
complete -c pw-inspector -s u --description 'upcase characters (A,B,C,D, etc. ).'
complete -c pw-inspector -s n --description 'numbers (1,2,3,4, etc. ).'
complete -c pw-inspector -s p --description 'printable characters (which are not -l/-n/-p, e. g.  $,!,/,(,*, etc. ).'

