# r2-docker
# Autogenerated from man page /usr/share/man/man1/r2-docker.1.gz
complete -c r2-docker -s s --description 'open shell inside the docker image (user r2, pass r2).'
complete -c r2-docker -s d --description 'debug program (only for linux-x86-32/64).'
complete -c r2-docker -s u --description 'update or create the docker image with r2 inside.'
complete -c r2-docker -s l --description 'List all docker images with radare2.'
complete -c r2-docker -s r --description 'Remove the radare2 docker image SEE ALSO Pp radare2(1) AUTHORS Pp pancake <pa…'

