# r2agent
# Autogenerated from man page /usr/share/man/man1/r2agent.1.gz
complete -c r2agent -s a --description 'Listen for everyone (localhost by default).'
complete -c r2agent -s d --description 'Run in daemon mode.'
complete -c r2agent -s h --description 'Show help prompt.'
complete -c r2agent -s s --description 'Run in sandbox mode.'
complete -c r2agent -s u --description 'Enable HTTP Authentification support.'
complete -c r2agent -s t --description 'user:password authentification file.'
complete -c r2agent -s p --description 'Specify listening port for the agent.'
complete -c r2agent -s v --description 'Show version information El EXAMPLES Pp TODO SEE ALSO Pp radare2(1).'

