# r2pm
# Autogenerated from man page /usr/share/man/man1/r2pm.1.gz
complete -c r2pm -s a --description 'Adds an external r2pm repository, no arguments to -a will list all the regist…'
complete -c r2pm -s I --description 'Show information about repository and installed packages.'
complete -c r2pm -s i --description 'Install a package.'
complete -c r2pm -o gi --description 'Install a package in the system directory.'
complete -c r2pm -s t --description 'Show last build + testsuite run from travis, greps for errors.'
complete -c r2pm -s u --description 'Uninstall a package.'
complete -c r2pm -o gu --description 'Uninstall a package from the system directory.'
complete -c r2pm -s l --description 'List installed packages.'
complete -c r2pm -s s --description 'Search in database for packages matching keyword.'
complete -c r2pm -s r --description 'Run command with R2PM_BINDIR in PATH.'
complete -c r2pm -s v --description 'Show version information.'
complete -c r2pm -s h --description 'Show usage help message.'
complete -c r2pm -s c --description 'Clean the source cache.'
complete -c r2pm -s w --description 'Show when a package was installed or exit 1 if pkg does not exist El EXAMPLES…'

