# rabbitmq-queues
# Autogenerated from man page /usr/share/man/man8/rabbitmq-queues.8.gz
complete -c rabbitmq-queues -s n --description 'Default node is rabbit@ Ar target-hostname, where target-hostname is the loca…'
complete -c rabbitmq-queues -s q --description 'Quiet output mode is selected.'
complete -c rabbitmq-queues -s s --description 'Silent output mode is selected.'
complete -c rabbitmq-queues -s t --description 'Operation timeout in seconds.  Not all commands support timeouts.'
complete -c rabbitmq-queues -s l --description 'Must be specified when the cluster is configured to use long (FQDN) node name…'
complete -c rabbitmq-queues -l erlang-cookie --description 'Shared secret to use to authenticate to the target node.'

