# rabbitmq-plugins
# Autogenerated from man page /usr/share/man/man8/rabbitmq-plugins.8.gz
complete -c rabbitmq-plugins -s n --description 'Default node is rabbit@target-hostname, where target-hostname is the local ho…'
complete -c rabbitmq-plugins -s q --description 'Quiet output mode is selected.'
complete -c rabbitmq-plugins -s s --description 'Silent output mode is selected.'
complete -c rabbitmq-plugins -s t --description 'Operation timeout in seconds.  Not all commands support timeouts.'
complete -c rabbitmq-plugins -s l --description 'Must be specified when the cluster is configured to use long (FQDN) node name…'
complete -c rabbitmq-plugins -l erlang-cookie --description 'Shared secret to use to authenticate to the target node.'
complete -c rabbitmq-plugins -s E --description 'Show only explicitly enabled plugins.'
complete -c rabbitmq-plugins -s e --description 'Show only explicitly or implicitly enabled plugins.'
complete -c rabbitmq-plugins -s m --description 'Show only plugin names (minimal).'
complete -c rabbitmq-plugins -s v --description 'Show all plugin details (verbose).'
complete -c rabbitmq-plugins -l offline --description 'Modify node\'s enabled plugin state directly without contacting the node.'
complete -c rabbitmq-plugins -l online --description 'Treat a failure to connect to the running broker as fatal.'

