# racluster
# Autogenerated from man page /usr/share/man/man1/racluster.1.gz
complete -c racluster -s m --description 'Supported aggregation objects are: none use a null flow key.'
complete -c racluster -s M --description 'Supported modes are: correct Attempt to correct the direction of flows by als…'
complete -c racluster -s V --description 'Verbose operation, printing a line of output for each input file processed.'

