# rad_counter
# Autogenerated from man page /usr/share/man/man1/rad_counter.1.gz
complete -c rad_counter -l file --description 'Counter DB filename.'
complete -c rad_counter -l user --description 'Information for specific user.'
complete -c rad_counter -l match --description 'Information for matching users.'
complete -c rad_counter -l reset --description 'Reset counter to <number>.'
complete -c rad_counter -l help --description 'Show the help screen.'

