# radamsa
# Autogenerated from man page /usr/share/man/man1/radamsa.1.gz
complete -c radamsa -s h -l help --description 'Show a shorter summary of options.'
complete -c radamsa -s V -l version --description 'Show program version.'
complete -c radamsa -s o -l output --description 'Specify where to write the modified data.'
complete -c radamsa -s n -l count --description 'How many outputs to generate based on the sample(s).'
complete -c radamsa -s s -l seed --description 'Start from random state n, which is a decimal number.'
complete -c radamsa -s M -l meta --description 'Write metadata about generated data to given path.'
complete -c radamsa -s l -l list --description 'Show all available mutations, patterns and generators along with their descri…'
complete -c radamsa -s r -l recursive --description 'Include samples from directories recursively.'
complete -c radamsa -s v -l verbose --description 'Print what is being done.'
complete -c radamsa -s m -l mutations --description 'Request the initial mutation probabilities manually.'
complete -c radamsa -s p -l patterns --description 'Request the mutation patterns manually.'
complete -c radamsa -s g -l generators --description 'Request the data stream generator probabilities manually.'

