# raddebug
# Autogenerated from man page /usr/share/man/man8/raddebug.8.gz
complete -c raddebug -o ccondition --description 'Set a specific debug condition.'
complete -c raddebug -o fsocket_file --description 'The path to the control socket.'
complete -c raddebug -o iipv4-address --description 'Show debug output for the client having the given IPv4 address.'
complete -c raddebug -s d --description 'The radius configuration directory, usually /etc/raddb.'
complete -c raddebug -s D --description 'Set main dictionary directory.  Defaults to /usr/share/freeradius.'
complete -c raddebug -s n --description 'Read raddb/name. conf instead of raddb/radiusd. conf.'
complete -c raddebug -o Iipv6-address --description 'Show debug output for the client having the given IPv6 address.'
complete -c raddebug -o ttimeout --description 'Stop printing debug output after "timeout" seconds.'
complete -c raddebug -s c --description 'Set a specific debug condition.'
complete -c raddebug -s f --description 'The path to the control socket.'
complete -c raddebug -s i --description 'Show debug output for the client having the given IPv4 address.'
complete -c raddebug -s I --description 'Show debug output for the client having the given IPv6 address.'
complete -c raddebug -s t --description 'Stop printing debug output after "timeout" seconds.'
complete -c raddebug -s u --description 'Show debug output for users having the given name.'

