# radiusd
# Autogenerated from man page /usr/share/man/man8/radiusd.8.gz
complete -c radiusd -s C --description 'Check the configuration and exit immediately.'
complete -c radiusd -s d --description 'Defaults to /etc/raddb.'
complete -c radiusd -s D --description 'Set main dictionary directory.  Defaults to /usr/share/freeradius.'
complete -c radiusd -s f --description 'Do not fork, stay running as a foreground process.'
complete -c radiusd -s h --description 'Print usage help information.'
complete -c radiusd -s i --description 'Defines which IP address that the server uses for sending and receiving packe…'
complete -c radiusd -s l --description 'Defaults to ${logdir}/radius. log.'
complete -c radiusd -s m --description 'On SIGINT or SIGQUIT exit cleanly instead of immediately.'
complete -c radiusd -s n --description 'Read raddb/name. conf instead of raddb/radiusd. conf.'
complete -c radiusd -s p --description 'Defines which port is used for receiving authentication packets.'
complete -c radiusd -s P --description 'Always write out PID, even with -f.'
complete -c radiusd -s s --description 'Run in "single server" mode.'
complete -c radiusd -s t --description 'Do not spawn threads.'
complete -c radiusd -s v --description 'Print server version information and exit.'
complete -c radiusd -s X --description 'Debugging mode.   Equivalent to "-sfxx -l stdout".'
complete -c radiusd -s x --description 'Finer-grained debug mode.'

