# radium
# Autogenerated from man page /usr/share/man/man8/radium.8.gz
complete -c radium -s B --description 'Specify the bind interface address for remote access.'
complete -c radium -s d --description 'Run radium as a daemon.'
complete -c radium -s e --description 'Specify the source identifier for this radium.'
complete -c radium -s f --description 'Use radium. conf as a source of configuration information.'
complete -c radium -s O --description 'Turn off Berkeley Packet Filter optimizer.'
complete -c radium -s p --description 'Override the persistent connection facility.'
complete -c radium -s P --description 'Specifies the <portnum> for remote client connection.'
complete -c radium -s S --description '<host[:port][//full/path/to/argus. data.'
complete -c radium -s T --description 'Indicate that radium should correct the timestamps of received argus records,…'
complete -c radium -s X --description 'Clear existing radium configuration.'

