# rafilteraddr
# Autogenerated from man page /usr/share/man/man1/rafilteraddr.1.gz
complete -c rafilteraddr -s f --description 'Specify the list of addresses used for the address filter.'
complete -c rafilteraddr -s v --description 'Invert the logic and print flows that don\'t match any of the addresses.'

