# rahisto
# Autogenerated from man page /usr/share/man/man1/rahisto.1.gz
complete -c rahisto -s M --description 'Don\'t print bins that have zero frequencies.'
complete -c rahisto -s H --description 'Supported metrics are: dur record total duration.'

