# rapath
# Autogenerated from man page /usr/share/man/man1/rapath.1.gz
complete -c rapath -s A --description 'Draw a description of the path with a legend.'
complete -c rapath -s M --description 'Supported pathmodes are:.'
complete -c rapath -s m --description 'Specify modifications to the default flow identifiers.  Supported fields are:.'
complete -c rapath -s f --description '.'

