# rarpd
# Autogenerated from man page /usr/share/man/man8/rarpd.8.gz
complete -c rarpd -s a --description 'Listen on all available interfaces.'
complete -c rarpd -s A --description 'Listen not only to RARP but also ARP messages.'
complete -c rarpd -s v --description 'Be verbose.'
complete -c rarpd -s d --description 'Debug mode.  Do not go to background.'
complete -c rarpd -s e --description 'Do not check for the presence of a boot image.'
complete -c rarpd -s b --description 'TFTP boot directory.  Default is /etc/tftpboot.'
complete -c rarpd -s V --description 'Print version and exit.'

