# rasort
# Autogenerated from man page /usr/share/man/man1/rasort.1.gz
complete -c rasort -s M --description 'Replace the existing file(s) with the sorted output(s).'
complete -c rasort -s m --description 'Supported sort fields are: . PP . RS.'

