# rasplit
# Autogenerated from man page /usr/share/man/man1/rasplit.1.gz
complete -c rasplit -s a --description 'default is 2 characters.'
complete -c rasplit -s d --description 'Toggle running as a deamon.'
complete -c rasplit -s M --description 'Supported spliting modes are:.'
complete -c rasplit -s w --description 'Rasplit supports an extended -w option that allows for output record contents…'

