# ratop
# Autogenerated from man page /usr/share/man/man1/ratop.1.gz
complete -c ratop -s m --description 'Supported aggregation objects are: none use a null flow key.'
complete -c ratop -s M --description 'Supported modes are: correct Attempt to correct the direction of flows by als…'

