# rax2
# Autogenerated from man page /usr/share/man/man1/rax2.1.gz
complete -c rax2 -s b --description 'Convert from binary string to character (rax2 \\-b 01000101).'
complete -c rax2 -s k --description 'Keep the same base as the input data.'
complete -c rax2 -s e --description 'Swap endian.'
complete -c rax2 -s F --description 'Read C strings from stdin and output in hexpairs.  Useful to load shellcodes.'
complete -c rax2 -s l --description 'Append newline to the decoded output for human friendly-ness.'
complete -c rax2 -s K --description 'Show randomart key asciiart for values or hexpairs.'
complete -c rax2 -s s --description 'Convert from hex string to character (rax2 \\-s 43 4a 50).'
complete -c rax2 -s S --description 'Convert from character to hex string (rax2 \\-S C J P).'
complete -c rax2 -s n --description 'Show hexpairs from integer value.'
complete -c rax2 -s N --description 'Show hexadecimal C string from integer value.'
complete -c rax2 -s u --description 'Convert given value to human readable units format.'
complete -c rax2 -s v --description 'Show program version.'
complete -c rax2 -s x --description 'Convert a string into a hash.'
complete -c rax2 -s h --description 'Show usage help message.'
complete -c rax2 -s o --description 'Convert from octal string to char (rax2 -o 162 62) El USAGE Pp Force output m…'

