# readpe
# Autogenerated from man page /usr/share/man/man1/readpe.1.gz
complete -c readpe -s A -l all --description 'full output (default).'
complete -c readpe -s H -l all-headers --description 'display all PE headers.'
complete -c readpe -s S -l all-sections --description 'display all PE sections headers.'
complete -c readpe -s f -l 'format<text' --description 'change output format (default is text).'
complete -c readpe -s d -l dirs --description 'display data directories.'
complete -c readpe -s h -l 'header<dos' --description 'display sepecific header.'
complete -c readpe -s i -l imports --description 'display imported functions names.'
complete -c readpe -s e -l exports --description 'display exported functions names.'
complete -c readpe -s v -l version --description 'show program version and exit.'
complete -c readpe -l format --description 'change output format (default is text).'
complete -c readpe -l header --description 'display sepecific header.'
complete -c readpe -l help --description 'show help.'

