# recovermov
# Autogenerated from man page /usr/share/man/man1/recovermov.1.gz
complete -c recovermov -s h --description 'Display an help message. RS . RE.'
complete -c recovermov -s b --description 'Set the size of blocks in bytes.'
complete -c recovermov -s i --description 'Set the initial index value for image numbering (default: 0). RS . RE.'
complete -c recovermov -s n --description 'Basename to use to create the salvaged files.  Default is \\f[C]video_\\f[].'
complete -c recovermov -s o --description 'Change the working directory before restoring files.'
complete -c recovermov -s V --description 'Display program version and exit.'

