# remove-duplicates
# Autogenerated from man page /usr/share/man/man1/remove-duplicates.1.gz
complete -c remove-duplicates -s f --description 'If -f is not given, duplicate will be identified twice (once in every directi…'

