# rifiuti-vista
# Autogenerated from man page /usr/share/man/man1/rifiuti-vista.1.gz
complete -c rifiuti-vista -s o -l output --description 'Write output to FILE.'
complete -c rifiuti-vista -s x -l xml --description 'Output in XML format instead of tab-delimited values.'
complete -c rifiuti-vista -s l -l legacy-filename --description 'Show legacy filename if available (like \\(lq\\fCD:\\\\Progra~1\\\\\\(rq), and speci…'
complete -c rifiuti-vista -s z -l localtime --description 'Present deletion time in numeric time zone of local system running the progra…'
complete -c rifiuti-vista -s t -l delimiter --description 'String to use as delimiter (TAB by default).'
complete -c rifiuti-vista -s n -l no-heading --description 'Don\'t show recycle bin path name, metadata and field headers.'
complete -c rifiuti-vista -s 8 -l always-utf8 --description '(Option deprecated since 0. 7. 0 version) . PP  . SS MISCELLANEOUS OPTIONS.'
complete -c rifiuti-vista -s v -l version --description 'Print version information and exit.'
complete -c rifiuti-vista -s h -l help --description 'Show help options and exit.'
complete -c rifiuti-vista -l help-all --description 'Show all help options and exit.'
complete -c rifiuti-vista -l help-text --description 'Show plain text output options and exit.  EXAMPLES.'

