# rlm_ippool_tool
# Autogenerated from man page /usr/share/man/man8/rlm_ippool_tool.8.gz
complete -c rlm_ippool_tool -s a --description 'Print all active entries.'
complete -c rlm_ippool_tool -s c --description 'Report number of active entries.'
complete -c rlm_ippool_tool -s r --description 'Remove active entries.'
complete -c rlm_ippool_tool -s v --description 'Verbose report of all entries.'
complete -c rlm_ippool_tool -s o --description 'Assume old database format (nas/port pair, not md5 output).'
complete -c rlm_ippool_tool -s n --description 'Mark the entry nasIP/nasPort as having ipaddress.'
complete -c rlm_ippool_tool -s u --description 'Update old format database to new.'

