# rmcpping
# Autogenerated from man page /usr/share/man/man8/rmcpping.8.gz
complete -c rmcpping -s h --description 'Output help menu.'
complete -c rmcpping -s V --description 'Output version.'
complete -c rmcpping -s c --description 'Stop after sending  count packets.'
complete -c rmcpping -s i --description 'Wait  interval seconds between sending each packet.'
complete -c rmcpping -s I --description 'Set source address to specified interface address.'
complete -c rmcpping -s t --description 'Time to wait for a response, in seconds.  Default is five seconds.'
complete -c rmcpping -s v --description 'Verbose output.'
complete -c rmcpping -s s --description 'Specify an initial starting sequence number.'

