# rmic-openjdk14
# Autogenerated from man page /usr/share/man/man1/rmic-openjdk14.1.gz
complete -c rmic-openjdk14 -o iiop --description 'tie classes.'
complete -c rmic-openjdk14 -o bootclasspath --description 'Overrides the location of bootstrap class files.'
complete -c rmic-openjdk14 -o classpath --description 'Specifies the path the rmic command uses to look up classes.'
complete -c rmic-openjdk14 -s d --description 'Specifies the root destination directory for the generated class hierarchy.'
complete -c rmic-openjdk14 -s g --description 'Enables the generation of all debugging information, including local variable…'
complete -c rmic-openjdk14 -o Jargument --description 'Used with any Java command, the -J option passes the argument that follows it…'
complete -c rmic-openjdk14 -o keep -o keepgenerated --description 'Retains the generated .'
complete -c rmic-openjdk14 -o nowarn --description 'Turns off warnings.'
complete -c rmic-openjdk14 -o nowrite --description 'Doesn[aq]t write compiled classes to the file system.'
complete -c rmic-openjdk14 -o vcompat --description 'Generates stub and skeleton classes that are compatible with both the 1.'
complete -c rmic-openjdk14 -o verbose --description 'Causes the compiler and linker to print messages about what classes are being…'
complete -c rmic-openjdk14 -o 'v1.1' --description 'Generates stub and skeleton classes for the 1.'
complete -c rmic-openjdk14 -o 'v1.2' --description '(Default) Generates stub classes for the 1. 2 JRMP stub protocol version only.'

