# rmid
# Autogenerated from man page /usr/share/man/man1/rmid.1.gz
complete -c rmid -o 'C<someCommandLineOption>' --description 'Specifies an option that is passed as a command-line argument to each child p…'
complete -c rmid -o 'J<someCommandLineOption>' --description 'Specifies an option that is passed to the \\f2java interpreter running \\f2rmid.'
complete -c rmid -o 'J-Dsun.rmi.activation.execPolicy' --description 'Specifies the policy that \\f2rmid employs to check commands and command-line …'
complete -c rmid -o log --description 'Specifies the name of the directory the activation system daemon uses to writ…'
complete -c rmid -o port --description 'Specifies the port \\f2rmid\'s registry uses.'

