# rmiregistry
# Autogenerated from man page /usr/share/man/man1/rmiregistry.1.gz
complete -c rmiregistry -s J --description 'Used in conjunction with any java option, it passes the option following the …'

