# rmiregistry-openjdk14
# Autogenerated from man page /usr/share/man/man1/rmiregistry-openjdk14.1.gz
complete -c rmiregistry-openjdk14 -o Joption --description 'Used with any Java option to pass the option following the.'
complete -c rmiregistry-openjdk14 -s J -s J --description 'Java interpreter.'

