# ruptime
# Autogenerated from man page /usr/share/man/man1/ruptime.1.gz
complete -c ruptime -s a --description 'Users idle an hour or more are not counted unless the a flag is given.'
complete -c ruptime -s l --description 'Sort by load average.'
complete -c ruptime -s r --description 'Reverses the sort order.'
complete -c ruptime -s t --description 'Sort by uptime.'
complete -c ruptime -s u --description 'Sort by number of users.  El Pp The default listing is sorted by host name.'

