# rva2ofs
# Autogenerated from man page /usr/share/man/man1/rva2ofs.1.gz
complete -c rva2ofs -s v -l version --description 'show program version and exit.'
complete -c rva2ofs -l help --description 'show help.'

