# rwcompare
# Autogenerated from man page /usr/share/man/man1/rwcompare.1.gz
complete -c rwcompare -l quiet --description 'Do not print a message if the files differ, and do not an print error message…'
complete -c rwcompare -l site-config-file --description 'Read the SiLK site configuration from the named file \\s-1FILENAME\\s0.'
complete -c rwcompare -l help --description 'Print the available options and exit.'

