# rwgeoip2ccmap
# Autogenerated from man page /usr/share/man/man1/rwgeoip2ccmap.1.gz
complete -c rwgeoip2ccmap -l mode --description 'Specify the type of the input and whether rwgeoip2ccmap creates a prefix map …'
complete -c rwgeoip2ccmap -l input-path --description 'Read the comma-separated value (\\s-1CSV\\s0) or binary forms of the GeoIP2, Ge…'
complete -c rwgeoip2ccmap -l output-path --description 'Write the binary country code prefix map to \\s-1PATH\\s0.'
complete -c rwgeoip2ccmap -l dry-run --description 'Check the syntax of the input file and do not write the output file.'
complete -c rwgeoip2ccmap -l fields --description 'Select which of the GeoName fields are used when processing a GeoIP2 or GeoLi…'
complete -c rwgeoip2ccmap -l note-add --description 'Add the specified \\s-1TEXT\\s0 to the header of the output file as an annotati…'
complete -c rwgeoip2ccmap -l note-file-add --description 'Open \\s-1FILENAME\\s0 and add the contents of that file to the header of the o…'
complete -c rwgeoip2ccmap -l invocation-strip --description 'Do not record the command used to create the prefix map in the output.'
complete -c rwgeoip2ccmap -l help --description 'Print the available options and exit.'
complete -c rwgeoip2ccmap -l version --description 'Print the version number and exit the application.'
complete -c rwgeoip2ccmap -l csv-input --description 'Assume the input is the \\s-1CSV\\s0 GeoIP Legacy country code data for IPv4.'
complete -c rwgeoip2ccmap -l v6-csv-input --description 'Assume the input is the \\s-1CSV\\s0 GeoIP Legacy country code data for IPv6.'
complete -c rwgeoip2ccmap -l encoded-input --description 'Assume the input is the specially-encoded binary form of the GeoIP Legacy cou…'
complete -c rwgeoip2ccmap -l input-file --description 'Read the input from \\s-1PATH\\s0.   An alias for --input-path.'

