# rwguess
# Autogenerated from man page /usr/share/man/man8/rwguess.8.gz
complete -c rwguess -l top --description 'Print the top \\s-1NUM\\s0 interfaces for each of input and output.'
complete -c rwguess -l print-all --description 'Print all \\s-1SNMP\\s0 interfaces that saw records, sorted by the \\s-1SNMP\\s0 …'
complete -c rwguess -l help --description 'Print the available options and exit.'

