# rwpcut
# Autogenerated from man page /usr/share/man/man1/rwpcut.1.gz
complete -c rwpcut -l columnar --description 'Pad each field with whitespace so that it always takes up the same number of …'
complete -c rwpcut -l delimiter --description '\\s-1DELIMITER\\s0 is used as the delimiter between columns instead of the defa…'
complete -c rwpcut -l epoch-time --description 'Display the timestamp as epoch time seconds instead of a formatted timestamp.'
complete -c rwpcut -l fields --description '\\s-1PRINT_FIELDS\\s0 is a comma-separated list of fields to include in the out…'
complete -c rwpcut -l integer-ips --description 'Display \\s-1IP\\s0 addresses as integers instead of in dotted quad notation.'

