# rwpmapbuild
# Autogenerated from man page /usr/share/man/man1/rwpmapbuild.1.gz
complete -c rwpmapbuild -l input-path --description 'Read the textual input from \\s-1PATH\\s0.'
complete -c rwpmapbuild -l output-path --description 'Write the binary prefix map to \\s-1PATH\\s0.'
complete -c rwpmapbuild -l mode --description 'Specify the type of the input, as if a mode statement appeared in the input s…'
complete -c rwpmapbuild -l dry-run --description 'Do not write the output file.   Simply check the syntax of the input file.'
complete -c rwpmapbuild -l ignore-errors --description 'Write the output file regardless of any errors encountered while parsing the …'
complete -c rwpmapbuild -l note-add --description 'Add the specified \\s-1TEXT\\s0 to the header of the output file as an annotati…'
complete -c rwpmapbuild -l note-file-add --description 'Open \\s-1FILENAME\\s0 and add the contents of that file to the header of the o…'
complete -c rwpmapbuild -l invocation-strip --description 'Do not record the command used to create the prefix map in the output.'
complete -c rwpmapbuild -l input-file --description 'Read the textual input from \\s-1PATH\\s0.   An alias for --input-path.'
complete -c rwpmapbuild -l output-file --description 'Write the binary prefix map to \\s-1PATH\\s0.   An alias for --output-path.'
complete -c rwpmapbuild -l help --description 'Print the available options and exit.'

