# rwrandomizeip
# Autogenerated from man page /usr/share/man/man1/rwrandomizeip.1.gz
complete -c rwrandomizeip -l seed --description 'Use \\s-1NUMBER\\s0 to seed the pseudo-random number generator.'
complete -c rwrandomizeip -l only-change-set --description 'Only modify the source or destination \\s-1IP\\s0 address if it appears in the …'
complete -c rwrandomizeip -l dont-change-set --description 'Do not modify the source or destination \\s-1IP\\s0 address if the address appe…'
complete -c rwrandomizeip -l consistent --description 'Randomize the \\s-1IP\\s0 addresses consistently, so that an input \\s-1IP\\s0 ad…'
complete -c rwrandomizeip -l save-table --description 'Randomize the \\s-1IP\\s0 addresses consistently and save this run\'s randomizat…'
complete -c rwrandomizeip -l load-table --description 'Randomize the \\s-1IP\\s0 addresses consistently using the randomization table …'
complete -c rwrandomizeip -l site-config-file --description 'Read the SiLK site configuration from the named file \\s-1FILENAME\\s0.'
complete -c rwrandomizeip -l help --description 'Print the available options and exit.'

