# rwswapbytes
# Autogenerated from man page /usr/share/man/man1/rwswapbytes.1.gz
complete -c rwswapbytes -l big-endian --description 'Write the output file in big-endian (network byte-order) format.'
complete -c rwswapbytes -l little-endian --description 'Write the output file in little-endian (Intel) format.'
complete -c rwswapbytes -l native-endian --description 'Write the output file in this machine\'s native format.'
complete -c rwswapbytes -l swap-endian --description 'Unconditionally swap the byte-order of the input file.'
complete -c rwswapbytes -l help --description 'Print the available options and exit.'
complete -c rwswapbytes -l version --description 'Print the version number and information about how SiLK was configured, then …'
complete -c rwswapbytes -l note-add --description 'Add the specified \\s-1TEXT\\s0 to the header of the output file as an annotati…'

