# sagan
# Autogenerated from man page /usr/share/man/man8/sagan.8.gz
complete -c sagan -s h -l help --description 'Show summary of options.'
complete -c sagan -s d -l debug --description 'Enable debugging.'
complete -c sagan -s D -l daemon --description 'Make process a daemon (fork to the background).'
complete -c sagan -s u -l user --description 'Run as user (defaults to \'sagan\').'
complete -c sagan -s c -l chroot --description 'Chroots the Sagan process to the specified directory.'
complete -c sagan -s f -l config --description 'Sagan configuration file to load.'
complete -c sagan -s F -l file --description 'Sagan FIFO over ride.'
complete -c sagan -s l -l log --description 'Set log file locaton and name.'

