# samba
# Autogenerated from man page /usr/share/man/man8/samba.8.gz
complete -c samba -s D -l daemon --description 'If specified, this parameter causes the server to operate as a daemon.'
complete -c samba -s i -l interactive --description 'If this parameter is specified it causes the server to run "interactively", n…'
complete -c samba -s M -l model --description 'This parameter can be used to specify the "process model" samba should use.'
complete -c samba -l maximum-runtime --description 'Set maximum runtime of the server process till autotermination in seconds.'
complete -c samba -s b -l show-build --description 'Print information about how Samba was built.'
complete -c samba -l usage --description 'Display brief usage message.'
complete -c samba -l debug-stderr --description 'Send debug output to STDERR.'
complete -c samba -l leak-report --description 'Enable talloc leak reporting on exit.'
complete -c samba -l leak-report-full --description 'Enable full talloc leak reporting on exit.'
complete -c samba -s d -l debuglevel --description 'level is an integer from 0 to 10.'
complete -c samba -s V -l version --description 'Prints the program version number.'
complete -c samba -s s -l configfile --description 'The file specified contains the configuration details required by the server.'
complete -c samba -s l -l log-basename --description 'Base directory name for log/debug files.  The extension ".'
complete -c samba -l option --description 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line.'
complete -c samba -s '?' -l help --description 'Print a summary of command line options.'
complete -c samba -s S --description 'parameter had been given.'

