# sandmap
# Autogenerated from man page /usr/share/man/man8/sandmap.8.gz
complete -c sandmap -l help --description '        show this message.'
complete -c sandmap -l debug --description '        displays information on the screen (debug mode).'
complete -c sandmap -l verbose --description '        displays \'info\' messages on the screen (verbose mode).'
complete -c sandmap -l time --description '        displays execution time, occurs only with --verbose.'
complete -c sandmap -s c -l config --description '        attach an external config file to the script SEE ALSO https://github.'

