# sc_attach
# Autogenerated from man page /usr/share/man/man1/sc_attach.1.gz
complete -c sc_attach -s '?' --description 'prints a list of command line options and a synopsis of each.'
complete -c sc_attach -s d --description 'prints each command sent to scamper 1 on stderr.'
complete -c sc_attach -s D --description 'causes sc_attach to operate as a daemon.'
complete -c sc_attach -s v --description 'prints the current revision of sc_attach and exits.'
complete -c sc_attach -s c --description 'specifies the scamper 1 command to prepend to each address in the input file.'
complete -c sc_attach -s i --description 'specifies the name of the input file which consists of a sequence of scamper …'
complete -c sc_attach -s o --description 'specifies the name of the output file to be written.'
complete -c sc_attach -s O --description 'allows the behavior of sc_attach to be further tailored.'
complete -c sc_attach -s p --description 'specifies the IP address and port where a scamper 1 is accepting control sock…'
complete -c sc_attach -s P --description 'specifies the mixing priority scamper 1 should assign to the source.'
complete -c sc_attach -s R --description 'specifies the unix domain socket on the local host where a remote scamper 1 i…'
complete -c sc_attach -s U --description 'specifies the unix domain socket on the local host where a local scamper 1 is…'

