# sc_erosprober
# Autogenerated from man page /usr/share/man/man1/sc_erosprober.1.gz
complete -c sc_erosprober -s a --description 'specifies the name of the input file which consists of a sequence of IP addre…'
complete -c sc_erosprober -s c --description 'specifies the command to use with each address.'
complete -c sc_erosprober -s I --description 'specifies the probe interval, in seconds, between probing each address.'
complete -c sc_erosprober -s l --description 'specifies the name of a file to log progress output from sc_erosprober genera…'
complete -c sc_erosprober -s o --description 'specifies the prefix of the name of the output file to be written.'
complete -c sc_erosprober -s O --description 'allows the behavior of sc_erosprober to be further tailored.'
complete -c sc_erosprober -s p --description 'specifies the port on the local host where scamper 1 is accepting control soc…'
complete -c sc_erosprober -s R --description 'specifies the rotation interval, in seconds, between rotating output files.'
complete -c sc_erosprober -s U --description 'specifies the name of a unix domain socket where scamper 1 is accepting contr…'

