# sc_filterpolicy
# Autogenerated from man page /usr/share/man/man1/sc_filterpolicy.1.gz
complete -c sc_filterpolicy -s '?' --description 'prints a list of command line options and a synopsis of each.'
complete -c sc_filterpolicy -s a --description 'specifies the name of the input file which consists of a sequence of systems …'
complete -c sc_filterpolicy -s D --description 'with this option set, sc_filterpolicy will detach and become a daemon.'
complete -c sc_filterpolicy -s l --description 'specifies the name of a file to log progress output from sc_filterpolicy gene…'
complete -c sc_filterpolicy -s o --description 'specifies the name of the file to be written.'
complete -c sc_filterpolicy -s O --description 'allows the behavior of sc_filterpolicy to be further tailored.'
complete -c sc_filterpolicy -s p --description 'specifies the port on the local host where scamper 1 is accepting control soc…'
complete -c sc_filterpolicy -s r --description 'specifies the name of a previously collected filter policy data file, in wart…'
complete -c sc_filterpolicy -s t --description 'specifies the class of probes to send for each IP address in the input file.'
complete -c sc_filterpolicy -s T --description 'specifies adjustments to the test schedule from the supported application typ…'
complete -c sc_filterpolicy -s U --description 'specifies the unix domain socket on the local host where scamper 1 is accepti…'

