# sc_remoted
# Autogenerated from man page /usr/share/man/man1/sc_remoted.1.gz
complete -c sc_remoted -s '?' --description 'prints a list of command line options and a synopsis of each.'
complete -c sc_remoted -s D --description 'causes sc_remoted to operate as a daemon.'
complete -c sc_remoted -s 4 --description 'causes sc_remoted to only listen for IPv4-based connections.'
complete -c sc_remoted -s 6 --description 'causes sc_remoted to only listen for IPv6-based connections.'
complete -c sc_remoted -s O --description 'allows the behavior of sc_remoted to be further tailored.'
complete -c sc_remoted -s P --description 'specifies the port on the local host where sc_remoted should listen for incom…'
complete -c sc_remoted -s U --description 'specifies the directory on the local host where unix domain sockets correspon…'
complete -c sc_remoted -s c --description 'specifies the server certificate file in PEM format to advertise to remote sc…'
complete -c sc_remoted -s p --description 'specifies the private key file in PEM format that corresponds to the certific…'

