# sc_radargun
# Autogenerated from man page /usr/share/man/man1/sc_radargun.1.gz
complete -c sc_radargun -s '?' --description 'prints a list of command line options and a synopsis of each.'
complete -c sc_radargun -s D --description 'causes sc_radargun to detach and become a daemon.'
complete -c sc_radargun -s a --description 'specifies the name of the input file which consists of a list of IPv4 address…'
complete -c sc_radargun -s d --description 'specifies the dump ID to use to analyze the collected data.'
complete -c sc_radargun -s f --description 'specifies the fudge to use when inferring if a device is deriving IP-ID value…'
complete -c sc_radargun -s o --description 'specifies the name of the output file to be written.'
complete -c sc_radargun -s O --description 'allows the behavior of sc_radargun to be further tailored.'
complete -c sc_radargun -s p --description 'specifies the port on the local host where scamper 1 is accepting control soc…'
complete -c sc_radargun -s P --description 'specifies the packets-per-second rate that scamper is running at.'
complete -c sc_radargun -s q --description 'specifies the number of probe packets to use to when inferring if an IP addre…'
complete -c sc_radargun -s r --description 'specifies the length of time, in seconds, each round should aim to complete i…'
complete -c sc_radargun -s R --description 'specifies the number of rounds to pursue in radargun.   By default, 30 rounds.'
complete -c sc_radargun -s t --description 'specifies the name of a file to log progress output from sc_radargun generate…'
complete -c sc_radargun -s U --description 'specifies the name of a unix domain socket where a local scamper 1 instance i…'

