# sc_tbitblind
# Autogenerated from man page /usr/share/man/man1/sc_tbitblind.1.gz
complete -c sc_tbitblind -s '?' --description 'prints a list of command line options and a synopsis of each.'
complete -c sc_tbitblind -s a --description 'specifies the name of the input file which constists of a sequence of systems…'
complete -c sc_tbitblind -s A --description 'specifies the type of application to simulate while testing the system.'
complete -c sc_tbitblind -s c --description 'specifies the name of a file to record IP addresses that have been tested.'
complete -c sc_tbitblind -s l --description 'specifies the number of tbit objects to record per warts file, before opening…'
complete -c sc_tbitblind -s o --description 'specifies the name of the file to be written.'
complete -c sc_tbitblind -s O --description 'allows the behavior of sc_tbitblind to be further tailored.'
complete -c sc_tbitblind -s p --description 'specifies the port on the local host where scamper 1 is accepting control soc…'
complete -c sc_tbitblind -s r --description 'causes the random number generator used to shuffle tests be seeded.'
complete -c sc_tbitblind -s t --description 'specifies the name of a file to log progress output from sc_tbitblind generat…'
complete -c sc_tbitblind -s T --description 'specifies the IP-TTL to use with the blind TCP tests.'
complete -c sc_tbitblind -s w --description 'specifies the length of time to wait between any two TCP tests to one system.'

