# sc_ttlexp
# Autogenerated from man page /usr/share/man/man1/sc_ttlexp.1.gz
complete -c sc_ttlexp -s '?' --description 'prints a list of command line options and a synopsis of each.'
complete -c sc_ttlexp -s O --description 'allows the behavior of sc_ttlexp to be further tailored.'

