# sc_tracediff
# Autogenerated from man page /usr/share/man/man1/sc_tracediff.1.gz
complete -c sc_tracediff -s a --description 'dump all traceroute pairs regardless of whether they have changed.'
complete -c sc_tracediff -s m --description 'specifies the method used to match pairs of traceroutes together.'
complete -c sc_tracediff -s n --description 'names should be reported instead of IP addresses, where possible.'

