# sc_warts2text
# Autogenerated from man page /usr/share/man/man1/sc_warts2text.1.gz
complete -c sc_warts2text -s d --description 'specifies the name of a file with IP-address, description mappings, one mappi…'

