# scalpel
# Autogenerated from man page /usr/share/man/man1/scalpel.1.gz
complete -c scalpel -s b --description 'Carve files even if defined footers aren\'t discovered within maximum carve si…'
complete -c scalpel -s c --description 'Chooses which configuration file to use.'
complete -c scalpel -s d --description 'Generate header/footer database.'
complete -c scalpel -s e --description 'Do nested header/footer matching, to deal with structured files that may cont…'
complete -c scalpel -s h --description 'Show a help screen and exit.'
complete -c scalpel -s i --description 'file is used as a list of input files to examine.'
complete -c scalpel -s o --description 'Recovered files are written to the directory directory.'
complete -c scalpel -s n --description 'Don\'t add extensions to extracted files.'
complete -c scalpel -s O --description 'Don\'t organize carved files by type.'
complete -c scalpel -s p --description 'Perform an image file preview.'
complete -c scalpel -s q --description 'Carve files only when the header is cluster-aligned.'
complete -c scalpel -s r --description 'Find only first of overlapping headers/footers [foremost 0. 69 compat mode].'
complete -c scalpel -s V --description 'Show copyright information and exit.'
complete -c scalpel -s v --description 'Enables verbose mode.'

