# scanssh
# Autogenerated from man page /usr/man/man1/scanssh.1.gz
complete -c scanssh -s V --description 'Causes scanssh to print its version number.'
complete -c scanssh -s I --description 'Does not send a SSH identification string.'
complete -c scanssh -s E --description 'Exit the program, if the file containing the addresses for exclusion can not …'
complete -c scanssh -s R --description 'If addresses are generated at random, this flag causes the program to ignore …'
complete -c scanssh -s p --description 'Specifies that scanssh ScanSSH should operate as a proxy detector.'
complete -c scanssh -s h --description 'Displays the usage of the program.'
complete -c scanssh -s n --description 'Specifies the port numbers to scan.  Ports are separated by commas.'
complete -c scanssh -s u --description 'A list of comma separated host:port pairs of SOCKS proxies that scanssh shoul…'
complete -c scanssh -s s --description 'Specifies a number of scanners should be executed for each open port.'
complete -c scanssh -s e --description 'Specifies the file that contains the addresses to be excluded from the scan.'

