# scanmem
# Autogenerated from man page /usr/share/man/man1/scanmem.1.gz
complete -c scanmem -s p -l pid --description 'Set the target-program-pid.'
complete -c scanmem -s c -l command --description 'Run given commands (separated by ";") before starting the interactive shell.'
complete -c scanmem -s v -l version --description 'Print version and exit.'
complete -c scanmem -s h -l help --description 'Print a short description of command line options then exit.'
complete -c scanmem -s d -l debug --description 'Run in debug mode, more information will be outputted.'
complete -c scanmem -s e -l errexit --description 'Exit on initial commands error, ignored during interactive mode.'

