# scap-as-rpm
# Autogenerated from man page /usr/share/man/man8/scap-as-rpm.8.gz
complete -c scap-as-rpm -s h -l help --description 'show this help message and exit.'
complete -c scap-as-rpm -l pkg-name --description 'Name of the RPM package, if none is provided the basename of the first SCAP i…'
complete -c scap-as-rpm -l pkg-summary --description 'Optional short description of the package.'
complete -c scap-as-rpm -l pkg-license --description 'Short name of the license that you want to publish the package under.  Ex.'
complete -c scap-as-rpm -l pkg-scap-location --description 'Folder where SCAP files are supposed to be installed.'
complete -c scap-as-rpm -l rpm-destination --description 'The folder (absolute or relative to CWD) where the result RPM shall be saved.'
complete -c scap-as-rpm -l pkg-version --description '.'
complete -c scap-as-rpm -l pkg-release --description '.'
complete -c scap-as-rpm -l srpm-destination --description 'The folder (absolute or relative to CWD) where the result SRPM shall be saved.'

