# scriptor
# Autogenerated from man page /usr/share/man/man1/scriptor.1p.gz
complete -c scriptor -s h --description 'Show summary of options.'
complete -c scriptor -s r --description 'Use the indicated reader.  By default the first PC/SC reader is used.'
complete -c scriptor -s p --description 'Use the indicated protocol.  Accepted values are T=0 and T=1.'
complete -c scriptor -s u --description 'Use unbuffered stdout.'

