# scrounge-ntfs
# Autogenerated from man page /usr/share/man/man8/scrounge-ntfs.8.gz
complete -c scrounge-ntfs -s c --description 'The cluster size (in sectors).  When not specified a default of 8 is used.'
complete -c scrounge-ntfs -s l --description 'List partition information for a drive.'
complete -c scrounge-ntfs -s m --description 'When recovering data this specifies the location of the MFT from the beginnin…'
complete -c scrounge-ntfs -s o --description 'Directory to put rescued files in.'
complete -c scrounge-ntfs -s s --description 'Search disk for partition information.  (Not implemented yet).'

