# sdjournal
# Autogenerated from man page /usr/share/man/man1/sdjournal.1.gz
complete -c sdjournal -l help --description 'PD Print program arguments.'
complete -c sdjournal -l version --description 'Print program version.'
complete -c sdjournal -l extcap-interfaces --description 'List available interfaces.'
complete -c sdjournal -l extcap-interface --description 'Use specified interfaces.'
complete -c sdjournal -l extcap-dlts --description 'List DLTs of specified interface.'
complete -c sdjournal -l extcap-config --description 'List configuration options of specified interface.'
complete -c sdjournal -l capture --description 'Start capturing from specified interface and write raw packet data to the loc…'
complete -c sdjournal -l fifo --description 'Save captured packet to file or send it through pipe.'

