# servertool
# Autogenerated from man page /usr/share/man/man1/servertool.1.gz
complete -c servertool -o ORBInitialHost --description 'Specifies the host machine on which the name server is running and listening …'

