# sfill
# Autogenerated from man page /usr/share/man/man1/sfill.1.gz
complete -c sfill -s f --description 'fast (and insecure mode): no /dev/urandom, no synchronize mode.'
complete -c sfill -s i --description 'wipe only free inode space, not free disk space.'
complete -c sfill -s I --description 'wipe only free disk space, not free inode space.'
complete -c sfill -s l --description 'lessens the security.'
complete -c sfill -s v --description 'verbose mode.'
complete -c sfill -s z --description 'wipes the last write with zeros instead of random data directory/mountpoint t…'

