# shapeclustering
# Autogenerated from man page /usr/share/man/man1/shapeclustering.1.gz
complete -c shapeclustering -s U --description 'The unicharset generated by unicharset_extractor(1).'
complete -c shapeclustering -s D --description 'Directory to write output files to.'
complete -c shapeclustering -s F --description '(Input) font properties file, where each line is of the following form, where…'
complete -c shapeclustering -s X --description '(Input) x heights file, each line is of the following form, where xheight is …'
complete -c shapeclustering -s O --description 'The output unicharset that will be given to combine_tessdata(1).'

