# shiboken
# Autogenerated from man page /usr/share/man/man1/shiboken.1.gz
complete -c shiboken -l debug-level --description 'Set the debug level.'
complete -c shiboken -l documentation-only --description 'Do not generates any code, just the documentation.'
complete -c shiboken -l generatorSet --description 'generatorSet to be used.  e. g.  qtdoc.'
complete -c shiboken -l help --description 'Display this help and exit.'
complete -c shiboken -l include-paths --description 'Include paths used by the C++ parser.'
complete -c shiboken -l license-file --description 'File used for copyright headers of generated files.'
complete -c shiboken -l no-suppress-warnings --description 'Show all warnings.'
complete -c shiboken -l output-directory --description 'The directory where the generated files will be written.'
complete -c shiboken -l silent --description 'Avoid printing any message.'
complete -c shiboken -l typesystem-paths --description 'Paths used when searching for typesystems.'
complete -c shiboken -l version --description 'Output version information and exit . SS "Shiboken options:".'
complete -c shiboken -l disable-verbose-error-messages --description 'Disable verbose error messages.'
complete -c shiboken -l enable-parent-ctor-heuristic --description 'Enable heuristics to detect parent relationship on constructors.'
complete -c shiboken -l enable-pyside-extensions --description 'Enable PySide extensions, such as support for signal/slots, use this if you a…'
complete -c shiboken -l enable-return-value-heuristic --description 'Enable heuristics to detect parent relationship on return values (USE WITH CA…'

