# sigfind
# Autogenerated from man page /usr/share/man/man1/sigfind.1.gz
complete -c sigfind -s b --description 'Specify the block size in which to search.'
complete -c sigfind -s o --description 'Specify the offset in a block in which the signature must exist.'
complete -c sigfind -s t --description 'Specify a template name that defines the signature value and offset.'
complete -c sigfind -s l --description 'The signature is stored in little-endian ordering and must therefore be rever…'
complete -c sigfind -s V --description 'Display version [hex_signature] The binary signature that you are searching f…'

