# silk_config
# Autogenerated from man page /usr/share/man/man1/silk_config.1.gz
complete -c silk_config -l silk-version --description 'Print the version of SiLK as a simple string.'
complete -c silk_config -l compiler --description 'Print the compiler used to build SiLK.'
complete -c silk_config -l cflags --description 'Print the include paths (that is, the -I switches) and any additional compile…'
complete -c silk_config -l include --description 'Print the include paths to use when compiling a file against the SiLK header …'
complete -c silk_config -l libs --description 'This switch is an alias for --libsilk-libs.'
complete -c silk_config -l libsilk-libs --description 'Print the linker flags (that is, the -L and -l switches) to use when linking …'
complete -c silk_config -l libsilk-thrd-libs --description 'Print the linker flags to use when linking a program against libsilk-thrd. so.'
complete -c silk_config -l libflowsource-libs --description 'Print the linker flags to use when linking a program against libflowsource.'
complete -c silk_config -l data-rootdir --description 'Print the compiled-in value of the default location of the SiLK data reposito…'
complete -c silk_config -l python-site-dir --description 'Print the name of the directory containing the silk subdirectory where the Py…'
complete -c silk_config -l help --description 'Print the available options and exit.'

