# sniffjoke-autotest
# Autogenerated from man page /usr/share/man/man1/sniffjoke-autotest.1.gz
complete -c sniffjoke-autotest -s h --description 'show a command line options resume.'
complete -c sniffjoke-autotest -s l --description 'accept a name for the currently profiling environment [required].'
complete -c sniffjoke-autotest -s n --description 'set the number of test replicas [default: 1] ERRORS, BUGS, ISSUE Sometime sni…'

