# sniffglue
# Autogenerated from man page /usr/share/man/man1/sniffglue.1.gz
complete -c sniffglue -s v -l verbose --description 'Increase filter sensitivity to show more (possibly less useful) packets.'
complete -c sniffglue -s h -l help --description 'Prints help information.'
complete -c sniffglue -s p -l promisc --description 'Set device to promiscuous mode.'
complete -c sniffglue -s r -l read --description 'Open device as pcap file.'
complete -c sniffglue -s n -l threads --description 'Specify the number of threads.'
complete -c sniffglue -s V -l version --description 'Prints version information.  If -r was specified, open as pcap file instead.'

