# sniffjoke
# Autogenerated from man page /usr/share/man/man1/sniffjoke.1.gz
complete -c sniffjoke -l location --description 'specify the network environment (suggested) [default: generic].'
complete -c sniffjoke -l dir --description 'specify the base directory where the location resides [default: /usr/local/va…'
complete -c sniffjoke -l user --description 'downgrade priviledge to the specified user [default: nobody].'
complete -c sniffjoke -l gw-mac-addr --description 'specify the default gateway mac address.'
complete -c sniffjoke -l group --description 'downgrade priviledge to the specified group [default: nogroup].'
complete -c sniffjoke -l whitelist --description 'inject evasion packets only in the specified ip addresses.'
complete -c sniffjoke -l blacklist --description 'inject evasion packet in all session excluding the blacklisted ip address.'
complete -c sniffjoke -l start --description 'if present, evasion is activated immediatly [default: not present], for start…'
complete -c sniffjoke -l debug --description 'set up verbosity level [default: 2] 1: suppress log, 2: common, 3: verbose, 4…'
complete -c sniffjoke -l foreground --description 'execute sniffjoke with foreground logging [default:background].'
complete -c sniffjoke -l admin --description 'specify administration IP address [default: 127. 0. 0. 1:8844].'
complete -c sniffjoke -l force --description 'force restart (usable when another sniffjoke service is running).'
complete -c sniffjoke -l version --description 'show sniffjoke version.'
complete -c sniffjoke -l help --description 'show a command line options resume When sniffjoke is running, it keeps on mem…'
complete -c sniffjoke -l only-plugin --description 'plugin_name.'

