# snmpps
# Autogenerated from man page /usr/share/man/man1/snmpps.1.gz
complete -c snmpps -o Cp --description 'Show hrSWRunPath in addition to hrSWRunName.'
complete -c snmpps -o Ca --description 'Show hrSWRunParameters in addition to hrSWRunName.'
complete -c snmpps -o Ct --description 'Sort display by total CPU usage.'
complete -c snmpps -o Cm --description 'Sort display by memory usage.'

