# snow
# Autogenerated from man page /usr/share/man/man1/snow.1.gz
complete -c snow -s C --description 'Compress the data if concealing, or uncompress it if extracting.'
complete -c snow -s f --description 'The contents of this file will be concealed in the input text file.'
complete -c snow -s l --description 'When appending whitespace, snow will always produce lines shorter than this v…'
complete -c snow -s m --description 'The contents of this string will be concealed in the input text file.'
complete -c snow -s p --description 'If this is set, the data will be encrypted with this password during concealm…'
complete -c snow -s Q --description 'Quiet mode.'
complete -c snow -s S --description 'Report on the approximate amount of space available for hidden message in the…'
complete -c snow -s V -l version --description 'Display usage information and exit.'
complete -c snow -s h -l help --description 'Display usage information and exit.'

