# SoapySDRUtil
# Autogenerated from man page /usr/share/man/man1/SoapySDRUtil.1.gz
complete -c SoapySDRUtil -l info --description 'Print general information on the library, list all found hardware support mod…'
complete -c SoapySDRUtil -l find --description 'Discover available devices, restricted to those matching the SPEC if given.'
complete -c SoapySDRUtil -l make --description 'Open and close device matching SPEC if possible.'
complete -c SoapySDRUtil -l probe --description 'Show detailed information on all devices or the devices matching SPEC if give…'
complete -c SoapySDRUtil -l check --description 'Check and print if driver module named NAME is present.'

