# socks
# Autogenerated from man page /usr/share/man/man8/socks.8.gz
complete -c socks -s I --description 'Inetd mode.  Standalone service only.'
complete -c socks -s d --description 'Daemonise.  Detach service from console and run in the background.'
complete -c socks -s t --description 'Be silenT.  Do not log start/stop/accept error records.'
complete -c socks -s u --description 'Never ask for username authentication.'
complete -c socks -s e --description 'External address.'
complete -c socks -s i --description 'Internal address.  IP address proxy accepts connections to.'
complete -c socks -s p --description 'Port.  Port proxy listens for incoming connections.  Default is 1080.'
complete -c socks -s l --description 'Log.  By default logging is to stdout.'
complete -c socks -s S --description 'Increase or decrease stack size.'

