# sord_validate
# Autogenerated from man page /usr/share/man/man1/sord_validate.1.gz
complete -c sord_validate -s h --description 'Print the command line options.'
complete -c sord_validate -s l --description 'Print errors on a single line.'
complete -c sord_validate -s v --description 'Display version information and exit.'

