# spipe
# Autogenerated from man page /usr/share/man/man1/spipe.1.gz
complete -c spipe -s t --description 'Address to which  spipe should connect.'
complete -c spipe -s k --description 'Use the provided key file to authenticate and encrypt.'
complete -c spipe -s f --description 'Use fast/weak handshaking: This reduces the CPU time spent in the initial con…'
complete -c spipe -s g --description 'Require perfect forward secrecy by dropping connections if the other host is …'
complete -c spipe -s j --description 'Disable transport layer keep-alives.  (By default they are enabled. ).'
complete -c spipe -s o --description 'Timeout, in seconds, after which an attempt to connect to the target or a pro…'
complete -c spipe -s v --description 'Print version number.  SEE ALSO spiped (1).'

