# sploitctl
# Autogenerated from man page /usr/share/man/man1/sploitctl.1.gz
complete -c sploitctl -s f --description '      - ? to list sites.'
complete -c sploitctl -s u --description '      - ? to list sites.'
complete -c sploitctl -s d --description '.'
complete -c sploitctl -s s --description '.'
complete -c sploitctl -s t --description '.'
complete -c sploitctl -s r --description '.'
complete -c sploitctl -s A --description '.'
complete -c sploitctl -s P --description '.'
complete -c sploitctl -s X --description '.'
complete -c sploitctl -s R --description 'MISC.'
complete -c sploitctl -s V --description '.'
complete -c sploitctl -s H --description 'EXAMPLES # download and decompress all exploit archives and remove archive.'

