# srm
# Autogenerated from man page /usr/share/man/man1/srm.1.gz
complete -c srm -s d --description 'ignore the two special dot files .  and .  on the commandline.'
complete -c srm -s f --description 'fast (and insecure mode): no /dev/urandom, no synchronize mode.'
complete -c srm -s l --description 'lessens the security.'
complete -c srm -s r --description 'recursive mode, deletes all subdirectories.'
complete -c srm -s v --description 'verbose mode.'
complete -c srm -s z --description 'wipes the last write with zeros instead of random data LIMITATIONS.'

