# ssdeep
# Autogenerated from man page /usr/share/man/man1/ssdeep.1.gz
complete -c ssdeep -s m --description 'Loads the specified file of known hashes to be used for matching.'
complete -c ssdeep -s k --description 'Load the specified file of known hashes to be used for matching.'
complete -c ssdeep -s v --description 'Verbose mode.'
complete -c ssdeep -s d --description 'Computes a signature for each entry in the FILES and compares it to the set o…'
complete -c ssdeep -s p --description 'Works like the -d flag, but displays all matches for each file.'
complete -c ssdeep -s r --description 'Enables recursive mode.  All subdirectories are traversed.'
complete -c ssdeep -s g --description 'Similar files are grouped together into clusters.'
complete -c ssdeep -s s --description 'Silent mode.  All error messages are suppressed.'
complete -c ssdeep -s b --description 'Enables bare mode.'
complete -c ssdeep -s l --description 'Enables relative file paths.'
complete -c ssdeep -s c --description 'Enables comma separated output mode.'
complete -c ssdeep -s x --description 'Signature file matching.'
complete -c ssdeep -s a --description 'Displays all matches in any of the matching mode, regardless of score.'
complete -c ssdeep -s t --description 'In any of the matching modes, only display matches when match score is greate…'
complete -c ssdeep -s h --description 'Show a help screen and exit.'
complete -c ssdeep -s V --description 'Show the version number and exit.'

