# sshdump
# Autogenerated from man page /usr/share/man/man1/sshdump.1.gz
complete -c sshdump -l help --description 'PD Print program arguments.'
complete -c sshdump -l version --description 'Print program version.'
complete -c sshdump -l extcap-interfaces --description 'List available interfaces.'
complete -c sshdump -l extcap-interface --description 'Use specified interfaces.'
complete -c sshdump -l extcap-dlts --description 'List DLTs of specified interface.'
complete -c sshdump -l extcap-config --description 'List configuration options of specified interface.'
complete -c sshdump -l capture --description 'Start capturing from specified interface and write raw packet data to the loc…'
complete -c sshdump -l fifo --description 'Save captured packet to file or send it through pipe.'
complete -c sshdump -l remote-host --description 'The address of the remote host for capture.'
complete -c sshdump -l remote-port --description 'The \\s-1SSH\\s0 port of the remote host.'
complete -c sshdump -l remote-username --description 'The username for ssh authentication.'
complete -c sshdump -l remote-password --description 'The password to use (if not ssh-agent and pubkey are used).'
complete -c sshdump -l sshkey --description 'The path to a private key for authentication.'
complete -c sshdump -l remote-interface --description 'The remote network interface to capture from.'
complete -c sshdump -l remote-capture-command --description 'A custom remote capture command that produces the remote stream that is shown…'

