# sshmitm
# Autogenerated from man page /usr/share/man/man8/sshmitm.8.gz
complete -c sshmitm -s d --description 'Enable verbose debugging output.'
complete -c sshmitm -s I --description 'Monitor / hijack an interactive session.'
complete -c sshmitm -s p --description 'Specify the local port to listen on.'

