# sshow
# Autogenerated from man page /usr/share/man/man8/sshow.8.gz
complete -c sshow -s d --description 'Enable verbose debugging output.'
complete -c sshow -s i --description 'Specify the interface to listen on.'
complete -c sshow -s p --description 'Process packets from the specified PCAP capture file instead of the network.'

