# sshpass
# Autogenerated from man page /usr/share/man/man1/sshpass.1.gz
complete -c sshpass -o ppassword --description 'The password is given on the command line.'
complete -c sshpass -o ffilename --description 'The password is the first line of the file filename.'
complete -c sshpass -o dnumber --description 'number is a file descriptor inherited by sshpass from the runner.'
complete -c sshpass -s e --description 'The password is taken from the environment variable "SSHPASS".'
complete -c sshpass -s P --description 'Set the password prompt.'
complete -c sshpass -s v --description 'Be verbose.'

