# sslcat
# Autogenerated from man page /usr/share/man/man1/sslcat.1.gz
complete -c sslcat -s B --description 'Enabled debugging output.'
complete -c sslcat -s d --description 'Drop connection on EOF from STDIN.'
complete -c sslcat -s 3 --description 'Force use of SSLv3.'
complete -c sslcat -s T --description 'Force use of TLSv1.'

