# sstrip
# Autogenerated from man page /usr/share/man/man1/sstrip.1.gz
complete -c sstrip -s z -l zeroes --description 'Attempt to also strip trailing zero bytes from the file.'
complete -c sstrip -l help --description 'Display help and exit.'
complete -c sstrip -l version --description 'Display version information and exit.'

