# sswap
# Autogenerated from man page /usr/share/man/man1/sswap.1.gz
complete -c sswap -s f --description 'fast (and insecure mode): no /dev/urandom, no synchronize mode.'
complete -c sswap -s l --description 'lessens the security.'
complete -c sswap -s v --description 'verbose mode.'
complete -c sswap -s z --description 'wipes the last write with zeros instead of random data BEWARE.'

