# stegdetect
# Autogenerated from man page /usr/share/man/man1/stegdetect.1.gz
complete -c stegdetect -s q --description 'Only reports images that are likely to have steganographic content.'
complete -c stegdetect -s h --description 'Only calculates the DCT histogram.   Use the d option to display the values.'
complete -c stegdetect -s n --description 'Enables checking of JPEG header information to surpress false positives.'
complete -c stegdetect -s V --description 'Displays the version number of the software.'
complete -c stegdetect -s s --description 'Changes the sensitivity of the detection algorithms.'
complete -c stegdetect -s C --description 'Feature vectors are being extraced from the images.'
complete -c stegdetect -s c --description 'Reads the data created by the C options and computes the necessary values to …'
complete -c stegdetect -s D --description 'Reads a decision object that contains detection information about a new stega…'
complete -c stegdetect -s d --description 'Prints debug information.'
complete -c stegdetect -s t --description 'Sets the tests that are being run on the image.'

