# stoken-gui
# Autogenerated from man page /usr/share/man/man1/stoken-gui.1.gz
complete -c stoken-gui -l small --description 'Show a minimal window that only displays a tokencode and a progress bar.'
complete -c stoken-gui -l rcfile --description 'Use an alternate . stokenrc file.'
complete -c stoken-gui -l password -s p --description 'Use a password supplied from the command line, instead of prompting the user.'
complete -c stoken-gui -l pin -s n --description 'Use a PIN supplied from the command line, instead of prompting the user.'
complete -c stoken-gui -l force -s f --description 'Override token expiration date check.'
complete -c stoken-gui -l file --description 'Use a token from file instead of the . stokenrc file.'
complete -c stoken-gui -l token --description 'Use a token from the command line instead of the . stokenrc file.'
complete -c stoken-gui -l random --description 'Generate a random token on the fly.   Used for testing or demonstrations only.'
complete -c stoken-gui -l help -s h --description 'Display basic usage information.'

