# stunnel
# Autogenerated from man page /usr/share/man/man8/stunnel.8.gz
complete -c stunnel -o fd --description 'Read the config file from specified file descriptor.'
complete -c stunnel -o help --description 'Print stunnel help menu.'
complete -c stunnel -o version --description 'Print stunnel version and compile time defaults.'
complete -c stunnel -o sockets --description 'Print default socket options.'
complete -c stunnel -o options --description 'Print supported \\s-1TLS\\s0 options.'
complete -c stunnel -o install --description 'Install \\s-1NT\\s0 Service.'
complete -c stunnel -o uninstall --description 'Uninstall \\s-1NT\\s0 Service.'
complete -c stunnel -o start --description 'Start \\s-1NT\\s0 Service.'
complete -c stunnel -o stop --description 'Stop \\s-1NT\\s0 Service.'
complete -c stunnel -o reload --description 'Reload the configuration file of the running \\s-1NT\\s0 Service.'
complete -c stunnel -o reopen --description 'Reopen the log file of the running \\s-1NT\\s0 Service.'
complete -c stunnel -o exit --description 'Exit an already started stunnel.'

