# sucrack
# Autogenerated from man page /usr/man/man1/sucrack.1.gz
complete -c sucrack -s h --description 'print help message.'
complete -c sucrack -s a --description 'use ansi escape codes for nice looking statistics (requires --enable-statisti…'
complete -c sucrack -s s --description 'statistics display intervall (requires --enable-statistics configuration flag…'
complete -c sucrack -s c --description 'only print statistics if a key other than `q\' is pressed.'
complete -c sucrack -s r --description 'enable rewriting of dictionary words (see rules below).'
complete -c sucrack -s w --description 'number of threads to run with.'
complete -c sucrack -s b --description 'size of the word list buffer.'
complete -c sucrack -s u --description 'user account to su to.'
complete -c sucrack -s l --description 'specify certain rules for the rewriting process . PP.'

