# svcrash
# Autogenerated from man page /usr/man/man1/svcrash.1.gz
complete -c svcrash -l version --description 'show program\'s version number and exit.'
complete -c svcrash -s h -l help --description 'show this help message and exit.'
complete -c svcrash -l auto --description 'Automatically send responses to attacks.'
complete -c svcrash -l astlog --description 'Path for the asterisk full logfile.'
complete -c svcrash -s d --description 'specify attacker\'s ip address.'
complete -c svcrash -s p --description 'specify attacker\'s port.'
complete -c svcrash -s b --description 'bruteforce the attacker\'s port.'

