# svreport
# Autogenerated from man page /usr/man/man1/svreport.1.gz
complete -c svreport -l version --description 'show program\'s version number and exit.'
complete -c svreport -s h -l help --description 'show this help message and exit.'
complete -c svreport -s v -l verbose --description 'Increase verbosity.'
complete -c svreport -s q -l quiet --description 'Quiet mode.'
complete -c svreport -s t -l type --description 'Type of session.  This is usually either svmap, svwar or svcrack.'
complete -c svreport -s s -l session --description 'Name of the session.'
complete -c svreport -s f -l format --description 'Format type.  Can be stdout, pdf, xml, csv or txt.'
complete -c svreport -s o -l output --description 'Output filename.'
complete -c svreport -s n --description 'Do not resolve the ip address.'
complete -c svreport -s c -l count --description 'Used togather with \'list\' command to count the number of entries.'

