# swfbbox
# Autogenerated from man page /usr/share/man/man1/swfbbox.1.gz
complete -c swfbbox -s h -l help --description 'Print help and exit.'
complete -c swfbbox -s b -l bbox --description 'Show movie bounding box (default).'
complete -c swfbbox -s B -l newbbox --description 'Show recalculated (optimized/expanded) bounding box.'
complete -c swfbbox -s e -l expand --description 'Write out a new file using the recalculated header bounding box.'
complete -c swfbbox -s O -l optimize --description 'Recalculate all object bounding boxes (except for the header).'
complete -c swfbbox -s S -l swifty --description 'Print out transformed bounding boxes.'
complete -c swfbbox -s c -l clip --description 'Clip bounding boxes to movie size.'
complete -c swfbbox -s o -l output --description 'Set output filename to filename (for -O).'
complete -c swfbbox -s v -l verbose --description 'Be more verbose.'
complete -c swfbbox -s V -l version --description '    Print program version and exit AUTHOR.'

