# swfc
# Autogenerated from man page /usr/share/man/man1/swfc.1.gz
complete -c swfc -s h -l help --description 'Print short help message and exit.'
complete -c swfc -s V -l version --description 'Print version info and exit.'
complete -c swfc -s C -l cgi --description 'Output to stdout (for use in CGI environments).'
complete -c swfc -s v -l verbose --description 'Increase verbosity.  Use more than one -v for greater effect.'
complete -c swfc -s o -l output --description '    Specify output file (Default: output. swf).'

