# swfextract
# Autogenerated from man page /usr/share/man/man1/swfextract.1.gz
complete -c swfextract -s h -l help --description 'Print short help message and exit.'
complete -c swfextract -s o -l output --description 'Write output to file filename.'
complete -c swfextract -s V -l version --description 'Print version info and exit.'
complete -c swfextract -s i -l id --description 'ids is a range of IDs to extract.  E. g.  1-10,14.'
complete -c swfextract -s j -l jpegs --description 'ids is a range of JPEG IDs to extract.  E. g.  1-2,3,14-.'
complete -c swfextract -s p -l pngs --description 'ids is a range of PNG IDs to extract.  E. g.  -10,20-30.'
complete -c swfextract -s f -l frame --description 'frames is a range of frames to extract.  E. g.  1-10,20-30,40-.'
complete -c swfextract -s n -l name --description 'Set the name of the object to extract to name.'
complete -c swfextract -s w -l hollow --description 'Copy empty frames to the output file, too.'
complete -c swfextract -s P -l placeobject --description 'Copy original placeobject tag for the given object into the output file (Use …'
complete -c swfextract -s m -l mp3 --description 'Extract main mp3 stream (There may be substreams in the Movieclips, as well.'

