# swfstrings
# Autogenerated from man page /usr/share/man/man1/swfstrings.1.gz
complete -c swfstrings -s f -l fonts --description 'Print out font information for each text block.'
complete -c swfstrings -s x -l xpos --description 'Set bounding box x coordinate.'
complete -c swfstrings -s y -l ypos --description 'Set bounding box y coordinate.'
complete -c swfstrings -s W -l width --description 'Set bounding box width.'
complete -c swfstrings -s H -l height --description 'Set bounding box height.'
complete -c swfstrings -s V -l version --description '    Print version information and exit AUTHORS.'

