# tcpnice
# Autogenerated from man page /usr/share/man/man8/tcpnice.8.gz
complete -c tcpnice -s A --description 'Inject TCP tiny window advertisements.'
complete -c tcpnice -s I --description 'Inject ICMP source quench replies.'
complete -c tcpnice -s M --description 'Inject ICMP fragmentation-needed replies with tiny next-hop MTUs.'
complete -c tcpnice -s i --description 'Specify the interface to listen on.'

