# tcpreplay-edit
# Autogenerated from man page /usr/share/man/man1/tcpreplay-edit.1.gz
complete -c tcpreplay-edit -l pnat -l endpoints -l fixlen --description 'Override default MTU length (1500 bytes).'

