# tcpxtract
# Autogenerated from man page /usr/man/man1/tcpxtract.1.gz
complete -c tcpxtract -l file -s f --description 'to specify an input capture file instead of a device.'
complete -c tcpxtract -l device -s d --description 'to specify an input device (i. e.  eth0).'
complete -c tcpxtract -l config -s c --description 'use FILE as the config file.'
complete -c tcpxtract -l output -s o --description 'dump files to DIRECTORY instead of current directory.'
complete -c tcpxtract -l version -s v --description 'display the version number of this program.'
complete -c tcpxtract -l help -s h --description 'display this lovely screen SEE ALSO The full documentation for tcpxtract is m…'

