# tesseract
# Autogenerated from man page /usr/share/man/man1/tesseract.1.gz
complete -c tesseract -s c --description 'Set value for parameter CONFIGVAR to VALUE.'
complete -c tesseract -l dpi --description 'Specify the resolution N in DPI for the input image(s).'
complete -c tesseract -s l -s l --description 'The language or script to use.'
complete -c tesseract -l psm --description 'Set Tesseract to only run a subset of layout analysis and assume a certain fo…'
complete -c tesseract -l oem --description 'Specify OCR Engine mode.  The options for N are: . sp . if n \\{\\.'
complete -c tesseract -l tessdata-dir --description 'Specify the location of tessdata path.'
complete -c tesseract -l user-patterns --description 'Specify the location of user patterns file.'
complete -c tesseract -l user-words --description 'Specify the location of user words file.'
complete -c tesseract -s h -l help --description '.'
complete -c tesseract -l help-extra --description '.'
complete -c tesseract -l help-psm --description '.'
complete -c tesseract -l help-oem --description '.'
complete -c tesseract -s v -l version --description '.'
complete -c tesseract -l list-langs --description '.'
complete -c tesseract -l print-parameters --description '.'

