# theme
# Autogenerated from man page /usr/share/man/man1/theme.1.gz
complete -c theme -s d --description 'Set the "document root" to root.'
complete -c theme -s E --description 'Normally theme will not expand "<?theme body?>" or "<?theme toc?>" in the "<h…'
complete -c theme -s f --description 'Forcibly overwrite existing html files.'
complete -c theme -s o --description 'Write the output to filename.'
complete -c theme -s p --description 'Set the pagename to path.'
complete -c theme -s t --description 'Use filename as the template file.'

