# tincd
# Autogenerated from man page /usr/share/man/man8/tincd.8.gz
complete -c tincd -s c --description 'Read configuration files from DIR instead of /etc/tinc/.'
complete -c tincd -s D --description 'Don\'t fork and detach.'
complete -c tincd -s d --description 'Increase debug level or set it to LEVEL (see below).'
complete -c tincd -s k --description 'Attempt to kill a running tincd (optionally with the specified SIGNAL instead…'
complete -c tincd -s n --description 'Connect to net NETNAME.'
complete -c tincd -s K --description 'Generate public/private RSA keypair and exit.'
complete -c tincd -s o --description 'Without specifying a HOST, this will set server configuration variable KEY to…'
complete -c tincd -s L --description 'Lock tinc into main memory.'
complete -c tincd -l logfile --description 'Write log entries to a file instead of to the system logging facility.'
complete -c tincd -l pidfile --description 'Write PID to FILE instead of /var/run/tinc.  Ns Ar NETNAME Ns Pa . pid.'
complete -c tincd -l bypass-security --description 'Disables encryption and authentication of the meta protocol.'
complete -c tincd -s R --description 'With this option tinc chroots into the directory where network config is loca…'
complete -c tincd -s U --description 'setuid to the specified USER after initialization.'
complete -c tincd -l help --description 'Display short list of options.'
complete -c tincd -l version --description 'Output version information and exit.'

