# tinyproxy
# Autogenerated from man page /usr/share/man/man8/tinyproxy.8.gz
complete -c tinyproxy -s c --description 'Use an alternate configuration file.'
complete -c tinyproxy -s d --description 'Don\\(cqt daemonize and stay in the foreground.  Useful for debugging purposes.'
complete -c tinyproxy -s h --description 'Display a short help screen of command line arguments and exit.'
complete -c tinyproxy -s v --description 'Display version information and exit.'

