# tor-resolve
# Autogenerated from man page /usr/share/man/man1/tor-resolve.1.gz
complete -c tor-resolve -s v --description 'Display verbose output.'
complete -c tor-resolve -s x --description 'Perform a reverse lookup: get the PTR record for an IPv4 address.'
complete -c tor-resolve -s 5 --description 'Use the SOCKS5 protocol.  (Default).'
complete -c tor-resolve -s 4 --description 'Use the SOCKS4a protocol rather than the default SOCKS5 protocol.'
complete -c tor-resolve -s p --description 'Override the default SOCKS port without setting the hostname.'

