# ts_uinput
# Autogenerated from man page /usr/share/man/man1/ts_uinput.1.gz
complete -c ts_uinput -s d -l daemonize --description 'Start ts_uinput as a daemon and return.'
complete -c ts_uinput -s v -l verbose --description 'Print debug information to stdout and stderr.'
complete -c ts_uinput -s n -l name --description 'Set the name of the new input event device.  Default: ts_uinput.'
complete -c ts_uinput -s i -l idev --description 'Explicitly choose the original input event device for tslib to use.'
complete -c ts_uinput -s f -l fbdev --description 'Explicitly choose the framebuffer device to use.'
complete -c ts_uinput -s s -l slots --description 'Explicitly set the possible concurrent touch contacts supported.'
complete -c ts_uinput -s b -l nofb --description 'Read the screen resolution values from the input device, not the framebuffer …'

