# u3-tool
# Autogenerated from man page /usr/share/man/man1/u3-tool.1.gz
complete -c u3-tool -s c --description 'Change current password.'
complete -c u3-tool -s d --description 'Disable device security leaving the data intact.'
complete -c u3-tool -s D --description 'Dump all raw info(for debug).'
complete -c u3-tool -s e --description 'Enable device security, protecting all files currently on the data partition …'
complete -c u3-tool -s h --description 'Print a short help message.'
complete -c u3-tool -s i --description 'Display device information.'
complete -c u3-tool -s l --description 'Load a new CD image into the cd partition of the device.'
complete -c u3-tool -s p --description 'Repartition device, reassinging the device space between the cd and data part…'
complete -c u3-tool -s R --description 'Reset device security destroying private data.'
complete -c u3-tool -s u --description 'Unlock secured data partition.  This requires the current password.'
complete -c u3-tool -s v --description 'Use verbose output.'
complete -c u3-tool -s V --description 'Print version information.'

