# uhd_config_info
# Autogenerated from man page /usr/share/man/man1/uhd_config_info.1.gz
complete -c uhd_config_info -l boost-version --description 'Print Boost version used:.'
complete -c uhd_config_info -l build-date --description 'Print C compiler used:.'
complete -c uhd_config_info -l c-compiler --description 'Print C++ compiler used:.'
complete -c uhd_config_info -l cxx-compiler --description 'Print C compile flags:.'
complete -c uhd_config_info -l c-flags --description 'Print C++ compile flags:.'
complete -c uhd_config_info -l cxx-flags --description 'Print UHD components included in this build (comma-delimited):.'
complete -c uhd_config_info -l enabled-components --description 'Print default install prefix for this build:.'
complete -c uhd_config_info -l install-prefix --description 'Print libusb version used.'
complete -c uhd_config_info -l libusb-version --description 'Print all information listed above:.'
complete -c uhd_config_info -l print-all --description 'Print UHD version:.'
complete -c uhd_config_info -l version --description 'This help information:.'
complete -c uhd_config_info -l help --description '.'

