# uhd_find_devices
# Autogenerated from man page /usr/share/man/man1/uhd_find_devices.1.gz
complete -c uhd_find_devices -l args --description 'This help information:.'
complete -c uhd_find_devices -l help --description 'IDENTIFYING DEVICES.'

