# uhd_usrp_probe
# Autogenerated from man page /usr/share/man/man1/uhd_usrp_probe.1.gz
complete -c uhd_usrp_probe -l args --description 'Print a complete property tree:.'
complete -c uhd_usrp_probe -l tree --description 'Query a string value from the properties tree:.'
complete -c uhd_usrp_probe -l string --description 'Print the version string and exit:.'
complete -c uhd_usrp_probe -l version --description 'This help information:.'
complete -c uhd_usrp_probe -l help --description 'IDENTIFYING USRP DEVICES.'

