# uhd_cal_tx_dc_offset
# Autogenerated from man page /usr/share/man/man1/uhd_cal_tx_dc_offset.1.gz
complete -c uhd_cal_tx_dc_offset -l help --description 'help message.'
complete -c uhd_cal_tx_dc_offset -l verbose --description 'enable some verbose.'
complete -c uhd_cal_tx_dc_offset -l args --description 'device address args [default = ""].'
complete -c uhd_cal_tx_dc_offset -l tx_wave_freq --description 'Transmit wave frequency in Hz.'
complete -c uhd_cal_tx_dc_offset -l tx_wave_ampl --description 'Transmit wave amplitude in counts.'
complete -c uhd_cal_tx_dc_offset -l rx_offset --description 'RX LO offset from the TX LO in Hz.'
complete -c uhd_cal_tx_dc_offset -l freq_start --description 'Frequency start in Hz (will use beginning of frequency range if unspecified).'
complete -c uhd_cal_tx_dc_offset -l freq_stop --description 'Frequency stop in Hz (will use end of frequency range if unspecified).'
complete -c uhd_cal_tx_dc_offset -l freq_step --description 'Step size for LO sweep in Hz.'
complete -c uhd_cal_tx_dc_offset -l nsamps --description 'Samples per data capture.'

