# unhide-tcp
# Autogenerated from man page /usr/share/man/man8/unhide-tcp.8.gz
complete -c unhide-tcp -s h -l help --description 'Display help.'
complete -c unhide-tcp -l brief --description 'Don\'t display warning messages, that\'s the default behavior.'
complete -c unhide-tcp -s f -l fuser --description 'Display fuser output (if available) for the hidden port On FreeBSD, instead o…'
complete -c unhide-tcp -s l -l lsof --description 'Display lsof output (if available) for the hidden port.'
complete -c unhide-tcp -s n -l netstat --description 'Use /bin/netstat instead of /sbin/ss.'
complete -c unhide-tcp -s s -l server --description 'Use a very quick strategy of scanning.'
complete -c unhide-tcp -s o -l log --description 'Write a log file (unhide-tcp-AAAA-MM-DD. log) in the current directory.'
complete -c unhide-tcp -s V -l version --description 'Show version and exit.'
complete -c unhide-tcp -s v -l verbose --description 'Be verbose, display warning message (default : don\'t display).'

