# uniconfd
# Autogenerated from man page /usr/share/man/man8/uniconfd.8.gz
complete -c uniconfd -s f --description 'Run in the foreground.   Do not fork into a separate daemon process.'
complete -c uniconfd -s d -o dd --description 'Print debugging messages to the console.'
complete -c uniconfd -s V --description 'Print the version number and exit.'
complete -c uniconfd -s a --description 'Require authentication on incoming connections.'
complete -c uniconfd -s A --description 'Check all accesses against a  perms moniker.'
complete -c uniconfd -s p --description 'Listen on a given TCP  R port .  The default is 4111.'
complete -c uniconfd -s s --description 'Listen on a given TCP  port wrapped in SSL.    The default is 4112.'
complete -c uniconfd -s u --description 'Listen on a given Unix socket filename .  This is disabled by default.'

