# unpack200-openjdk8
# Autogenerated from man page /usr/share/man/man1/unpack200-openjdk8.1.gz
complete -c unpack200-openjdk8 -o Hvalue -l deflate-hint --description 'br Sets the deflation to be \\f3true, \\f3false, or \\f3keep on all entries with…'
complete -c unpack200-openjdk8 -s r -l remove-pack-file --description 'br Removes the input pack file.'
complete -c unpack200-openjdk8 -s v -l verbose --description 'br Displays minimal messages.'
complete -c unpack200-openjdk8 -s q -l quiet --description 'br Specifies quiet operation with no messages.'
complete -c unpack200-openjdk8 -o lfilename -l log-file --description 'br Specifies a log file where output messages are logged.'
complete -c unpack200-openjdk8 -s '?' -s h -l help --description 'br Prints help information about the \\f3unpack200 command.'
complete -c unpack200-openjdk8 -s V -l version --description 'br Prints version information about the \\f3unpack200 command.'
complete -c unpack200-openjdk8 -o Joption --description '.'

