# usnjls
# Autogenerated from man page /usr/share/man/man1/usnjls.1.gz
complete -c usnjls -s f --description 'Specify the file system type.'
complete -c usnjls -s i --description 'Identify the type of image file, such as raw or split.'
complete -c usnjls -s o --description 'The sector offset where the file system starts in the image.'
complete -c usnjls -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c usnjls -s l --description 'Print the output in long format describing the field values and unpacking the…'
complete -c usnjls -s m --description 'Print the output in mactime format.'
complete -c usnjls -s V --description 'Display version.'
complete -c usnjls -s v --description 'verbose output image [images] One (or more if split) disk or partition images…'

