# usrp_n2xx_simple_net_burner
# Autogenerated from man page /usr/share/man/man1/usrp_n2xx_simple_net_burner.1.gz
complete -c usrp_n2xx_simple_net_burner -l addr --description 'This help information:.'
complete -c usrp_n2xx_simple_net_burner -l help --description 'Custom Firmware Filepath:.'
complete -c usrp_n2xx_simple_net_burner -l fw --description 'Custom FPGA Filepath:.'
complete -c usrp_n2xx_simple_net_burner -l fpga --description 'Don\'t burn firmware:.'
complete -c usrp_n2xx_simple_net_burner -l no-fw --description 'Don\'t burn FPGA:.'
complete -c usrp_n2xx_simple_net_burner -l no-fpga --description 'Automatically reboot USRP device after burning.'
complete -c usrp_n2xx_simple_net_burner -l auto_reboot --description 'List all USRP devices without burning.'
complete -c usrp_n2xx_simple_net_burner -l list --description 'EXAMPLES Selecting a USRP device with a non-standard IP address.'

