# usrp2_card_burner
# Autogenerated from man page /usr/share/man/man1/usrp2_card_burner.1.gz
complete -c usrp2_card_burner -l addr --description 'This help information:.'
complete -c usrp2_card_burner -l help --description 'Firmware Filepath:.'
complete -c usrp2_card_burner -l fw --description 'FPGA Filepath:.'
complete -c usrp2_card_burner -l fpga --description 'List all USRP devices without burning.'
complete -c usrp2_card_burner -l list --description 'Override safety check.'
complete -c usrp2_card_burner -l force --description 'EXAMPLES Standard burning procedure.'

