# usrp_x3xx_fpga_burner
# Autogenerated from man page /usr/share/man/man1/usrp_x3xx_fpga_burner.1.gz
complete -c usrp_x3xx_fpga_burner -l addr --description '.'
complete -c usrp_x3xx_fpga_burner -l resource --description '.'
complete -c usrp_x3xx_fpga_burner -l rpc-port --description '.'
complete -c usrp_x3xx_fpga_burner -l type --description '.'
complete -c usrp_x3xx_fpga_burner -l fpga-path --description '.'
complete -c usrp_x3xx_fpga_burner -l configure --description '.'
complete -c usrp_x3xx_fpga_burner -l verify --description '.'
complete -c usrp_x3xx_fpga_burner -l list --description 'This help information:.'
complete -c usrp_x3xx_fpga_burner -l help --description 'EXAMPLES Burning a 1-Gigabit image over Ethernet.'

