# vacuumlo
# Autogenerated from man page /usr/share/man/man1/vacuumlo.1.gz
complete -c vacuumlo -s l --description 'Remove no more than limit large objects per transaction (default 1000).'
complete -c vacuumlo -o 'n
.br
--dry-run' --description 'Don\\*(Aqt remove anything, just show what would be done.'
complete -c vacuumlo -o 'v
.br
--verbose' --description 'Write a lot of progress messages.'
complete -c vacuumlo -o 'V
.br
--version' --description 'Print the vacuumlo version and exit.'
complete -c vacuumlo -o '?
.br
--help' --description 'Show help about vacuumlo command line arguments, and exit.'
complete -c vacuumlo -s h --description 'Database server\\*(Aqs host.'
complete -c vacuumlo -s p --description 'Database server\\*(Aqs port.'
complete -c vacuumlo -s U --description 'User name to connect as.'
complete -c vacuumlo -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c vacuumlo -o 'W
.br
--password' --description 'Force vacuumlo to prompt for a password before connecting to a database.'
complete -c vacuumlo -l limit --description '.'
complete -c vacuumlo -s n --description '.'
complete -c vacuumlo -l dry-run --description '.'
complete -c vacuumlo -s v --description '.'
complete -c vacuumlo -l verbose --description '.'
complete -c vacuumlo -s V --description '.'
complete -c vacuumlo -l version --description '.'
complete -c vacuumlo -s '?' --description '.'
complete -c vacuumlo -l help --description '.'
complete -c vacuumlo -l host --description '.'
complete -c vacuumlo -l port --description '.'
complete -c vacuumlo -l username --description '.'
complete -c vacuumlo -s w --description '.'
complete -c vacuumlo -l no-password --description '.'
complete -c vacuumlo -s W --description '.'
complete -c vacuumlo -l password --description '.'

