# valabind
# Autogenerated from man page /usr/share/man/man1/valabind.1.gz
complete -c valabind -s h --description 'show help message.'
complete -c valabind -s o --description 'specify output file name.'
complete -c valabind -s m --description 'specify module name.'
complete -c valabind -s N --description 'include given namespace for processing.'
complete -c valabind -s D --description 'define a preprocessor symbol inside Vala code.'
complete -c valabind -s p --description 'select Vala profile (posix, gobject, dova).'
complete -c valabind -s x --description 'generate c++ code for SWIG bindings.'
complete -c valabind -s v --description 'show version information.'
complete -c valabind -s V --description 'specify an alternative vapidir path El ENVIRONMENT -tag -width Fl XDG_DATA_DI…'

