# versuck-ng
# Autogenerated from man page /usr/share/man/man1/versuck-ng.1.gz
complete -c versuck-ng -s h --description 'Shows the help screen.'
complete -c versuck-ng -s m --description 'The internal mac address of the device.'
complete -c versuck-ng -s e --description 'The ESSID that the device is using.'

