# vgdb
# Autogenerated from man page /usr/share/man/man1/vgdb.1.gz
complete -c vgdb -l pid --description 'Specifies the PID of the process to which vgdb must connect to.'
complete -c vgdb -l vgdb-prefix --description 'Must be given to both Valgrind and vgdb if you want to change the default pre…'
complete -c vgdb -l wait --description 'Instructs vgdb to search for available Valgrind gdbservers for the specified …'
complete -c vgdb -l max-invoke-ms --description 'Gives the number of milliseconds after which vgdb will force the invocation o…'
complete -c vgdb -l cmd-time-out --description 'Instructs a standalone vgdb to exit if the Valgrind gdbserver it is connected…'
complete -c vgdb -l port --description 'Instructs vgdb to use tcp/ip and listen for GDB on the specified port nr rath…'
complete -c vgdb -s c --description 'To give more than one command to a standalone vgdb, separate the commands by …'
complete -c vgdb -s l --description 'Instructs a standalone vgdb to report the list of the Valgrind gdbserver proc…'
complete -c vgdb -s T --description 'Instructs vgdb to add timestamps to vgdb information messages.'
complete -c vgdb -s D --description 'Instructs a standalone vgdb to show the state of the shared memory used by th…'
complete -c vgdb -s d --description 'Instructs vgdb to produce debugging output.'

