# vifm-convert-dircolors
# Autogenerated from man page /usr/share/man/man1/vifm-convert-dircolors.1.gz
complete -c vifm-convert-dircolors -s h -l help --description 'Displays brief help message.'
complete -c vifm-convert-dircolors -s e -l environment --description 'Instructs the script to use $LS_COLORS environment variable instead of data f…'
complete -c vifm-convert-dircolors -s r -l human-readable --description 'Output patterns on separate lines.'

