# virt-login-shell
# Autogenerated from man page /usr/share/man/man1/virt-login-shell.1.gz
complete -c virt-login-shell -s c --description 'Instruct the shell to run \\s-1CMD\\s0 instead of presenting an interactive she…'
complete -c virt-login-shell -s h -l help --description 'Display command line help usage then exit.'

