# wavemon
# Autogenerated from man page /usr/share/man/man1/wavemon.1.gz
complete -c wavemon -s i --description 'override autodetection and use the specified interface.'
complete -c wavemon -s g --description 'check screen geometry: a minimum size is required for proper display; this fl…'
complete -c wavemon -s h --description 'print help and exit.'

