# webspy
# Autogenerated from man page /usr/share/man/man8/webspy.8.gz
complete -c webspy -s i --description 'Specify the interface to listen on.'
complete -c webspy -s p --description 'Process packets from the specified PCAP capture file instead of the network.'

