# winedbg
# Autogenerated from man page /usr/share/man/man1/winedbg.1.gz
complete -c winedbg -l commandstring --description 'winedbg will execute the command string as if it was keyed on winedbg command…'
complete -c winedbg -l filefilename --description 'winedbg will execute the list of commands contained in file filename as if th…'
complete -c winedbg -l no-start --description 'gdb will not be automatically started.'
complete -c winedbg -l portport --description 'Start the gdb server on the given port.'
complete -c winedbg -l with-xterm --description 'This will run gdb in its own xterm instead of using the current Unix console …'
complete -c winedbg -l gdb --description 'winedbg will be used as a proxy for gdb.'
complete -c winedbg -l auto --description 'This mode is used when winedbg is set up in AeDebug registry entry as the def…'
complete -c winedbg -l minidump --description 'This mode is similar to the --auto one, except that instead of printing the i…'
complete -c winedbg -l command --description 'winedbg will execute the command string as if it was keyed on winedbg command…'
complete -c winedbg -l file --description 'winedbg will execute the list of commands contained in file filename as if th…'
complete -c winedbg -l port --description 'Start the gdb server on the given port.'

