# wineserver
# Autogenerated from man page /usr/share/man/man1/wineserver.1.gz
complete -c wineserver -s d -l debug --description 'Set the debug level to R n .'
complete -c wineserver -s f -l foreground --description 'Make the server remain in the foreground for easier debugging, for instance w…'
complete -c wineserver -s h -l help --description 'Display a help message.'
complete -c wineserver -s k -l kill --description 'Kill the currently running  wineserver , optionally by sending signal n.'
complete -c wineserver -s p -l persistent --description 'Specify the wineserver persistence delay, i. e.'
complete -c wineserver -s v -l version --description 'Display version information and exit.'
complete -c wineserver -s w -l wait --description 'Wait until the currently running wineserver terminates.  ENVIRONMENT.'

