# winecpp
# Autogenerated from man page /usr/share/man/man1/winecpp.1.gz
complete -c winecpp -s b -l target --description 'Specify the target architecture triplet for cross-compiling.'
complete -c winecpp -l wine-objdir --description 'Specify the Wine object directory.'
complete -c winecpp -l winebuild --description 'Specifies the path and name of the winebuild binary that will be launched aut…'
complete -c winecpp -o fno-short-wchar --description 'Override the underlying type for wchar_t to be the default for the  target, i…'
complete -c winecpp -o mconsole --description 'This option passes \'--subsystem console\' to winebuild, to build console appli…'
complete -c winecpp -o mno-cygwin --description 'Use Wine implementation of MSVCRT, instead of linking against the host system…'
complete -c winecpp -o municode --description 'Set the default entry point of the application to be the Unicode wmain() inst…'
complete -c winecpp -o mwindows --description 'This option adds -lgdi32, -lcomdlg32, and -lshell32 to the list of default li…'
complete -c winecpp -o nodefaultlibs --description 'Do not use the standard system libraries when linking.'
complete -c winecpp -o nostartfiles --description 'Do not add the winecrt0 library when linking.'
complete -c winecpp -o Wb --description 'Pass an option to winebuild.'

