# winepath
# Autogenerated from man page /usr/share/man/man1/winepath.1.gz
complete -c winepath -s u -l unix --description 'converts a Windows path to a Unix path.'
complete -c winepath -s w -l windows --description 'converts a Unix path to a long Windows path.'
complete -c winepath -s l -l long --description 'converts the short Windows path of an existing file or directory to the long …'
complete -c winepath -s s -l short --description 'converts the long Windows path of an existing file or directory to the short …'
complete -c winepath -s 0 --description 'separate output with \\\\0 character, instead of a newline.'
complete -c winepath -s h -l help --description 'shows winepath help message and exit.'

