# winpr-makecert
# Autogenerated from man page /usr/share/man/man1/winpr-makecert.1.gz
complete -c winpr-makecert -o rdp --description 'Dummy parameter.'
complete -c winpr-makecert -o silent --description 'Don\'t print the generated certificate to stdout.'
complete -c winpr-makecert -s f --description 'Three formats are supported: crt, pem and pfx.'
complete -c winpr-makecert -s p --description 'Password to use if the pfx format is used as format.'
complete -c winpr-makecert -o live --description 'Don\'t write the key/certificate to disk.'
complete -c winpr-makecert -s n --description 'The common name to use in the certificate.'
complete -c winpr-makecert -s m --description 'Validity period in months.'
complete -c winpr-makecert -s y --description 'Validity period in years.'
complete -c winpr-makecert -o len --description 'Key length in bits to use.'
complete -c winpr-makecert -s a --description 'The hashing algorithm to use.'
complete -c winpr-makecert -s '#' --description 'The serial number to use for the certificate.'
complete -c winpr-makecert -o path --description 'A directory where the certificate should be created in.'

