# wsgen-openjdk8
# Autogenerated from man page /usr/share/man/man1/wsgen-openjdk8.1.gz
complete -c wsgen-openjdk8 -o classpath --description 'br The location of the input class files.'
complete -c wsgen-openjdk8 -o cp --description 'br The location of the input class files.'
complete -c wsgen-openjdk8 -s d --description 'br The location for where to place generated output files.'
complete -c wsgen-openjdk8 -o extension --description 'br Allow vendor extensions.'
complete -c wsgen-openjdk8 -o help --description 'br Displays a help message about the \\f3wsgen command.'
complete -c wsgen-openjdk8 -o keep --description 'br Keeps the generated files.'
complete -c wsgen-openjdk8 -s r --description 'br Uses this option with the \\f3-wsdl option to specify where to place genera…'
complete -c wsgen-openjdk8 -s s --description 'br The location for where to place generated source files.'
complete -c wsgen-openjdk8 -o verbose --description 'br Displays compiler messages.'
complete -c wsgen-openjdk8 -o version --description 'br Prints release information.'
complete -c wsgen-openjdk8 -o wsdl --description 'br An optional command that generates a WSDL file to review before endpoint d…'
complete -c wsgen-openjdk8 -o servicename --description 'br Used only with the \\f3-wsdl option to specify a particular WSDL service (\\…'
complete -c wsgen-openjdk8 -o portname --description '.'

