# wvtag
# Autogenerated from man page /usr/share/man/man1/wvtag.1.gz
complete -c wvtag -l allow-huge-tags --description 'allow tag data up to 16 MB (embedding > 1 MB is not recommended for portable …'
complete -c wvtag -s c --description 'extract cuesheet only to stdout (equivalent to -x \\(lqcuesheet\\(rq).'
complete -c wvtag -o cc --description 'extract cuesheet to source-name.'
complete -c wvtag -l clean -l clear --description 'clean all items from tag (done first).'
complete -c wvtag -s d --description 'delete specified metadata item (text or binary).'
complete -c wvtag -s h -l help --description 'this help display.'
complete -c wvtag -l import-id3 --description 'import applicable tag items from ID3v2.'
complete -c wvtag -s l -l list --description 'list all tag items (done last).'
complete -c wvtag -l no-utf8-convert --description 'don\\*(Aqt recode passed tags from local encoding to UTF-8, assume they are in…'
complete -c wvtag -s q --description 'quiet (keep console output to a minimum).'
complete -c wvtag -s v -l version --description 'write program version to stdout.'
complete -c wvtag -s w --description 'delete specified metadata item (text or binary).'
complete -c wvtag -l write-binary-tag --description 'write the specified binary metadata file to APEv2 tag, normally used for cove…'
complete -c wvtag -s x --description 'extract the specified tag field only to stdout.'
complete -c wvtag -o xx --description 'extract the specified tag field to named file in same directory as source fil…'
complete -c wvtag -s y --description 'yes to all warnings (use with caution!).'

