# x86_64-w64-mingw32-ar
# Autogenerated from man page /usr/share/man/man1/x86_64-w64-mingw32-ar.1.gz
complete -c x86_64-w64-mingw32-ar -l help --description 'Displays the list of command-line options supported by ar and then exits.'
complete -c x86_64-w64-mingw32-ar -l version --description 'Displays the version information of ar and then exits.'
complete -c x86_64-w64-mingw32-ar -o X32_64 --description 'ar ignores an initial option spelled -X32_64, for compatibility with \\s-1AIX.'
complete -c x86_64-w64-mingw32-ar -l plugin --description 'The optional command-line switch --plugin name causes ar to load the plugin c…'
complete -c x86_64-w64-mingw32-ar -l target --description 'The optional command-line switch --target bfdname specifies that the archive …'
complete -c x86_64-w64-mingw32-ar -l output --description 'The --output option can be used to specify a path to a directory into which a…'

