# x86dis
# Autogenerated from man page /usr/share/man/man1/x86dis.1.gz
complete -c x86dis -s f -l file --description 'br  Read input bytes from file instead of stdin.'
complete -c x86dis -s o -l out --description 'br  Write output to file instead of stdout.'
complete -c x86dis -s l -l log --description 'br  Log errors to file instead of stderr.'
complete -c x86dis -s p -l pagesize --description 'br  Set page size for buffering STDIN to num (default 512K).'
complete -c x86dis -s s -l syntax --description 'br  Set output syntax to name, where name is one of intel .'
complete -c x86dis -s d -l desc --description 'br  Print a description of syntax name.'
complete -c x86dis -s a -l addr --description 'br  Disassemble single instruction at offset.'
complete -c x86dis -s e -l entry --description 'br  Disassemble forward from offset.'

