# xapian-compact
# Autogenerated from man page /usr/share/man/man1/xapian-compact.1.gz
complete -c xapian-compact -s b -l blocksize --description 'Set the blocksize in bytes (e. g.  4096) or K (e. g.'
complete -c xapian-compact -s n -l no-full --description 'Disable full compaction.'
complete -c xapian-compact -s F -l fuller --description 'Enable fuller compaction (not recommended if you plan to update the compacted…'
complete -c xapian-compact -s m -l multipass --description 'If merging more than 3 databases, merge the postlists in multiple passes (whi…'
complete -c xapian-compact -l no-renumber --description 'Preserve the numbering of document ids (useful if you have external reference…'
complete -c xapian-compact -s s -l single-file --description 'Produce a single file database (not supported for chert).'
complete -c xapian-compact -l help --description 'display this help and exit.'
complete -c xapian-compact -l version --description 'output version information and exit.'

