# xapian-pos
# Autogenerated from man page /usr/share/man/man1/xapian-pos.1.gz
complete -c xapian-pos -s d -l doc --description 'Show positions for document DOCID.'
complete -c xapian-pos -s s -l start --description 'Specifies the first position to show.'
complete -c xapian-pos -s e -l end --description 'Specifies the last position to show.'
complete -c xapian-pos -l help --description 'display this help and exit.'
complete -c xapian-pos -l version --description 'output version information and exit.'

