# xapian-delve
# Autogenerated from man page /usr/share/man/man1/xapian-delve.1.gz
complete -c xapian-delve -s a --description 'show all terms in the database.'
complete -c xapian-delve -s A --description 'show all terms in the database with given prefix.'
complete -c xapian-delve -s r --description 'for term list(s).'
complete -c xapian-delve -s t --description 'for posting list(s).'
complete -c xapian-delve -s s -l stemmer --description 'set the stemming language, the default is \'none\'.'
complete -c xapian-delve -s 1 --description 'output one list entry per line.'
complete -c xapian-delve -o 'V<valueno>' --description 'output value valueno for each document referred to (or each document in the d…'
complete -c xapian-delve -s V --description 'output all values for each document referred to.  <type> is as above.'
complete -c xapian-delve -s d --description 'output document data for each document referred to.'
complete -c xapian-delve -s z --description 'for db, count documents with length 0.'
complete -c xapian-delve -s v --description 'extra info (wdf and len for postlist; wdf and termfreq for termlist; number o…'
complete -c xapian-delve -o vv --description 'even more info (also show collection freq and wdf upper bound for terms).'
complete -c xapian-delve -l help --description 'display this help and exit.'
complete -c xapian-delve -l version --description 'output version information and exit.'

