# xfce4-power-manager-settings
# Autogenerated from man page /usr/share/man/man1/xfce4-power-manager-settings.1.gz
complete -c xfce4-power-manager-settings -l debug --description 'Have the power manager print debug messages to the console; useful if you hav…'
complete -c xfce4-power-manager-settings -l socket-id --description 'Settings manager socket, used when xfce4-power-manager-settings is embedded i…'
complete -c xfce4-power-manager-settings -l device-id --description 'Display a specific device by a specific UPower UpDevice object path.'

