# xl2tpd
# Autogenerated from man page /usr/share/man/man8/xl2tpd.8.gz
complete -c xl2tpd -s D --description 'This option prevents xl2tpd from detaching from the terminal and daemonizing.'
complete -c xl2tpd -s l --description 'This option tells xl2tpd to use syslog for logging even when -D was specified.'
complete -c xl2tpd -s c --description 'Tells xl2tpd to use an alternate config file.   Default is /etc/xl2tpd/xl2tpd.'
complete -c xl2tpd -s s --description 'Tells xl2tpd to use an alternate "secrets" file.'
complete -c xl2tpd -s p --description 'Tells xl2tpd to use an alternate pid file.'

