# xprobe2
# Autogenerated from man page /usr/man/man1/xprobe2.1.gz
complete -c xprobe2 -s v --description 'be verbose.'
complete -c xprobe2 -s r --description 'display route to target (traceroute-like output).'
complete -c xprobe2 -s c --description 'use configfile to read the configuration file, xprobe2.'
complete -c xprobe2 -s D --description 'disable module number modnum.'
complete -c xprobe2 -s m --description 'set number of results to display to numofmatches.'
complete -c xprobe2 -s o --description 'use logfile to log everything (default output is stderr).'
complete -c xprobe2 -s p --description 'specify port number (portnum), protocol (proto) and it\'s state for xprobe2 to…'
complete -c xprobe2 -s t --description 'set receive timeout to receive\\_timeout in seconds (the default is set to 10 …'
complete -c xprobe2 -s F --description 'generate signature for specified target (use -o to save fingerprint into file…'
complete -c xprobe2 -s X --description 'write XML output to logfile specified with -o.'
complete -c xprobe2 -s B --description 'causes xprobe2 to be a bit more noisy, as -B makes TCP handshake module to tr…'
complete -c xprobe2 -s T -s U --description 'enable built-in portscanning module, which will attempt to scan TCP and/or UD…'
complete -c xprobe2 -s A --description 'enable experimental support for detection of transparent proxies and firewall…'

