# yafMeta2Pcap
# Autogenerated from man page /usr/share/man/man1/yafMeta2Pcap.1.gz
complete -c yafMeta2Pcap -l pcap-meta-file --description '\\s-1META_FILE_NAME\\s0 is the path to the pcap-meta-file as created by yaf.'
complete -c yafMeta2Pcap -l pcap --description '\\s-1PCAP_FILE_NAME\\s0 is the path to the \\s-1PCAP\\s0 file that was given to y…'
complete -c yafMeta2Pcap -l caplist --description 'Instead of listing multiple \\s-1PCAP\\s0 files, use \\s-1CAP_FILE_NAME\\s0 as an…'
complete -c yafMeta2Pcap -l metalist --description 'Instead of listing multiple \\s-1PCAP\\s0 metadata files, use \\s-1META_FILE_NAM…'
complete -c yafMeta2Pcap -l out --description 'The full path of the \\s-1PCAP\\s0 file that will be created containing just th…'
complete -c yafMeta2Pcap -l hash --description 'The flow key hash of the flow as created by getFlowKeyHash.'
complete -c yafMeta2Pcap -l time --description 'The milliseconds since epoch time of the start time of the flow.'
complete -c yafMeta2Pcap -l etime --description 'The milliseconds since epoch time of the end time of the flow.'
complete -c yafMeta2Pcap -l packets --description '\\s-1NUM_PACKETS\\s0 is the total number of packets for the bi-flow.'
complete -c yafMeta2Pcap -l yaf-program --description '\\s-1PATH_TO_YAF\\s0 is the location of the yaf program to use to create the \\s…'

