# yafscii
# Autogenerated from man page /usr/share/man/man1/yafscii.1.gz
complete -c yafscii -l in --description '\\s-1INPUT_SPECIFIER\\s0 is an input specifier.'
complete -c yafscii -l out --description '\\s-1OUTPUT_SPECIFIER\\s0 is an output specifier.'
complete -c yafscii -l tabular --description 'Use tabular output mode, which is designed for easy parsability over human re…'
complete -c yafscii -l mac --description 'Used with --tabular mode to print source and destination \\s-1MAC\\s0 Addresses.'
complete -c yafscii -l print-header --description 'Used with --tabular mode to print column headers.'
complete -c yafscii -l daemon --description 'Run yafscii in daemon mode.'
complete -c yafscii -l lock --description 'Use lockfiles for concurrent file access protection.'
complete -c yafscii -l poll --description '\\s-1POLLING_DELAY\\s0 is the polling delay in seconds; how long yaf will  wait…'
complete -c yafscii -l nextdir --description 'When reading from files, if this option is present, input files will be  move…'
complete -c yafscii -l faildir --description 'When reading from files, if this option is present, input files will be  move…'
complete -c yafscii -l log --description 'Specifies destination for log messages.'
complete -c yafscii -l loglevel --description 'Specify minimum level for logged messages.'
complete -c yafscii -l verbose --description 'Equivalent to --loglevel debug.'

