# yapp
# Autogenerated from man page /usr/share/man/man1/yapp.1p.gz
complete -c yapp -s v --description 'Creates a file grammar. output describing your parser.'
complete -c yapp -s s --description 'Create a standalone module in which the driver is included.'
complete -c yapp -s n --description 'Disable source file line numbering embedded in your parser module.'
complete -c yapp -s m --description 'Gives your parser module the package name (or name space or module name or cl…'
complete -c yapp -s o --description 'The compiled output file will be named outfile for your parser module.'
complete -c yapp -s t --description 'The -t filename option allows you to specify a file which should be  used as …'
complete -c yapp -s b --description 'If you work on systems that understand so called shebangs, and your generated…'
complete -c yapp -s V --description 'Display current version of Parse::Yapp and gracefully exits.'

