# yasat
# Autogenerated from man page /usr/share/man/man8/yasat.8.gz
complete -c yasat -l standard -s a --description 'YASAT will performs a standard check of the system, printing out the results …'
complete -c yasat -l list -s l --description 'List all plugins available.'
complete -c yasat -l html -s H --description 'YASAT will export results in html (default to ~/yasat/yasat. html).'
complete -c yasat -l html-output --description 'With -H, this option permit to change the file where to store html output.'
complete -c yasat -l advice-lang --description 'By default, YASAT print message in english (EN), you can change the displayed…'
complete -c yasat -l full-scan -s f --description 'YASAT will do extra (long) tests (lots of find).'
complete -c yasat -l plugins-dir -s P --description 'Set the path where YASAT can find plugins to use.  (default is . /plugins ).'
complete -c yasat -l nopause --description 'By default, YASAT made a pause after each plugin.'
complete -c yasat -l plugin -s 1 --description 'YASAT will just use the plugin pointed by PATH (ex: yasat -1 kernel).'
complete -c yasat -l scanroot -s r --description 'YASAT will scan PATH instead of / (ex: yasat -r /mnt/centos6).'
complete -c yasat -l compliance --description 'YASAT will check for a specific compliance (nsa, cce, or all) and will print …'
complete -c yasat -l print-level --description 'YASAT will print infos equal or above the level X (All = 0 (default), infos =…'
complete -c yasat -l skip --description 'A comma separated list of tests to skip without the .'
complete -c yasat -l check-update --description 'Check if an update of YASAT exists.'

