# yate-config
# Autogenerated from man page /usr/share/man/man8/yate-config.8.gz
complete -c yate-config -l version --description 'Reports the installed YATE version (in x. y. z format).'
complete -c yate-config -l release --description 'Reports the installed YATE code status (if not release) and release number.'
complete -c yate-config -l config --description 'Returns the configuration files directory.'
complete -c yate-config -l modules --description 'Returns the modules directory.'
complete -c yate-config -l share --description 'Returns the base shared directory.'
complete -c yate-config -l scripts --description 'Returns the scripts directory.'
complete -c yate-config -l skins --description 'Returns the base skins directory . SS Compiler flags.'
complete -c yate-config -l cflags --description 'Various C++ compiler flags.'
complete -c yate-config -l includes --description 'Include option and path to the header files.'
complete -c yate-config -l c-all --description 'All compiler options - the above two concatenated . SS Linker flags.'
complete -c yate-config -l ldflags --description 'Various linker flags.'
complete -c yate-config -l libs --description 'Library option and libraries names.'
complete -c yate-config -l ld-all --description 'All linker options - the above two concatenated AUTHORS Paul Chitescu <paulc@…'

