# zbarcam
# Autogenerated from man page /usr/share/man/man1/zbarcam.1.gz
complete -c zbarcam -s h -l help --description 'Print a short help message describing command line options to standard output…'
complete -c zbarcam -l version --description 'Print program version information to standard output and exit.'
complete -c zbarcam -s v -l verbose --description 'Increase debug output level.  Multiple -v options create more spew.'
complete -c zbarcam -s q -l quiet --description 'Quiet operation; disable the audible beep otherwise emitted when a symbol is …'
complete -c zbarcam -l nodisplay --description 'Disable output video window.'
complete -c zbarcam -l xml --description 'Stream results using an XML output format.'
complete -c zbarcam -l raw --description 'Use raw symbol data output format.'
complete -c zbarcam -l prescale --description 'Request video input scaling from the camera driver.'
complete -c zbarcam -o Sconfig -l set --description '.'

