# zeek-cut
# Autogenerated from man page /usr/share/man/man1/zeek-cut.1.gz
complete -c zeek-cut -s c --description 'Include the first format header block in the output.'
complete -c zeek-cut -s C --description 'Include all format header blocks in the output.'
complete -c zeek-cut -s d --description 'Convert time values into human-readable format.'
complete -c zeek-cut -s h --description 'Show help.'
complete -c zeek-cut -s n --description 'Print all fields except those specified.'
complete -c zeek-cut -s D --description '.'
complete -c zeek-cut -s F --description '.'
complete -c zeek-cut -s u --description 'Like -d, but print timestamps in UTC instead of local time.'
complete -c zeek-cut -s U --description 'ENVIRONMENT.'

