# ziptool
# Autogenerated from man page /usr/share/man/man1/ziptool.1.gz
complete -c ziptool -s c --description 'Check zip archive consistency when opening it.'
complete -c ziptool -s e --description 'Error if archive already exists (only useful with n ).'
complete -c ziptool -s g --description 'Guess file name encoding (for stat command).'
complete -c ziptool -s h --description 'Display help.'
complete -c ziptool -s l --description 'Only read length bytes of archive.  See also o.'
complete -c ziptool -s n --description 'Create archive if it doesn\'t exist.  See also e.'
complete -c ziptool -s o --description 'Start reading input archive from offset.  See also l.'
complete -c ziptool -s r --description 'Print raw file name encoding without translation (for stat command).'
complete -c ziptool -s s --description 'Follow file name convention strictly (for stat command).'
complete -c ziptool -s t --description 'Disregard current file contents, if any.'

