# zssh
# Autogenerated from man page /usr/share/man/man1/zssh.1.gz
complete -c zssh -l force --description 'Do not ask user any question.'
complete -c zssh -l help --description 'show basic help.'
complete -c zssh -l shell --description 'run cmd as remote shell instead of the default  "ssh -e none" (zssh) or "teln…'
complete -c zssh -l version --description 'show version.'
complete -c zssh -s f --description '.'
complete -c zssh -s h --description '.'
complete -c zssh -s s --description '.'
complete -c zssh -s V --description '.'
complete -c zssh -s z --description '.'
complete -c zssh -l zssh-escape --description 'set escape sequence to ^X.'

