# zstdcat
# Autogenerated from man page /usr/share/man/man1/zstdcat.1.gz
complete -c zstdcat -s z -l compress --description 'Compress.'
complete -c zstdcat -s d -l decompress -l uncompress --description 'Decompress.'
complete -c zstdcat -s t -l test --description 'Test the integrity of compressed files.'
complete -c zstdcat -o 'b#' --description 'Benchmark file(s) using compression level # .'
complete -c zstdcat -l train --description 'Use FILEs as a training set to create a dictionary.'

