# zuluMount-cli
# Autogenerated from man page /usr/share/man/man1/zuluMount-cli.1.gz
complete -c zuluMount-cli -s m -s d -s z -s e --description '      -- additional arguments for crypto_LUKS,crypto_PLAIN,crypto_TCRYPT volu…'
complete -c zuluMount-cli -s u --description '.'
complete -c zuluMount-cli -s s --description '.'
complete -c zuluMount-cli -s o --description '      and the option must be given when -u or -s arguments are used with a vo…'
complete -c zuluMount-cli -s M --description '.'
complete -c zuluMount-cli -s l --description '.'
complete -c zuluMount-cli -s Y --description '.'
complete -c zuluMount-cli -s t --description '.'
complete -c zuluMount-cli -s L --description '.'
complete -c zuluMount-cli -s P --description '.'
complete -c zuluMount-cli -s A --description '.'
complete -c zuluMount-cli -s S --description '.'
complete -c zuluMount-cli -s N --description '.'
complete -c zuluMount-cli -s E --description '.'
complete -c zuluMount-cli -s D --description '.'
complete -c zuluMount-cli -s F --description '.'

