# zzat
# Autogenerated from man page /usr/share/man/man1/zzat.1.gz
complete -c zzat -s A -l show-all --description 'Equivalent to -vET.'
complete -c zzat -s b -l number-nonblank --description 'Number nonempty output lines.'
complete -c zzat -s d -l debug --description 'Output debugging information.'
complete -c zzat -s e --description 'Equivalent to -vET.'
complete -c zzat -s E -l show-ends --description 'Display $ at end of each line.'
complete -c zzat -s n -l number --description 'Number all output lines.'
complete -c zzat -s r -l repeat --description 'Concatenate all files loops times.'
complete -c zzat -s t --description 'Equivalent to -vT.'
complete -c zzat -s T -l show-tabs --description 'Display TAB characters as ^I.'
complete -c zzat -s v -l show-nonprinting --description 'Use ^ and M- notation, except for LFD and TAB.'
complete -c zzat -s x -l execute --description 'Read a file or a stream using the instruction sequence specified in sequence.'
complete -c zzat -s l -l list --description 'Display the list of supported keywords and functions and exit.'
complete -c zzat -s h -l help --description 'Display a short help message and exit.'
complete -c zzat -s V -l version --description 'Output version information and exit.  EXAMPLES.'

