#!/bin/sh
USER=`sed -n "1 p" ~/.vpnrc`
PASSWORD=`sed -n "2 p" ~/.vpnrc`

if [ -z $1 ]; then
    sudo killall -SIGINT openconnect
else
    server=`sed -n "$(expr $1 + 2) p" ~/.vpnrc`

    HOST=`echo $server | cut -d' ' -f1`
    country=`echo $server | cut -d' ' -f2`

    echo "connecting to $country"
    echo "$PASSWORD" | sudo openconnect -u $USER -b $HOST --no-dtls
    ping -c4 youtube.com
fi 
