# unbind-key -a

bind R source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded!"

bind ^X lock-server
bind ^D detach

bind - split-window -v
bind | split-window -h
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# bind -n m-j select-window -n
# bind -n m-k select-window -p
# bind -n m-l switch-client -n
# bind -n m-; switch-client -p
bind -n m-tab    select-window -n
bind -n m-btab   select-window -p
bind -n m-c-tab  switch-client -n
bind -n m-c-btab switch-client -p

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi M send -X reverse-search-history

bind : command-prompt
bind q kill-pane
bind x kill-window
bind c swap-pane -D
bind n new-window -c "#{pane_current_path}"
bind N new-window -c "$HOME"
bind r command-prompt "rename-window '%%'"
bind S choose-session
bind * setw synchronize-panes
bind * set pane-border-status

bind o run-shell "tmux neww siscon"

bind -n M-Enter resize-pane -Z
