"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = "q", run = "close", desc = "Close the current tab, or quit if it's last" },
  { on = "l", run = "plugin fast-enter", desc = "Smart enter the subfolder, or open the file" },
  { on = "<Right>", run = "plugin fast-enter", desc = "Smart enter the subfolder, or open the file" },

  { on = "<C-y>", run = "plugin system-clipboard", desc = "Yank selected files to clipboard" },
  { on = "S", run = "plugin fr rg", desc = "Search files by content via ripgrep" },
  { on = "F", run = "filter --smart", desc = "Filter files" },
  { on = "f", run = "plugin smart-filter", desc = "Smart filter" },
  { on = [ "g", "d" ], run = "cd ~/downloads", desc = "Go ~/downloads" },
  { on = [ "g", "a" ], run = "cd /run/media/vss/Storage/Vahid/Films/Anime", desc = "Go Anime" },


  { on = "'", run = "spot", desc = "spot" },
  { on = "<S-tab>", run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
  { on = "<tab>", run = "tab_switch 1 --relative", desc = "Switch to next tab" },

  { on = "<C-n>", run = 'shell -- dragon-drop -x -i -T "$1"', desc = "drag from yazi" },
  { on = [ "T", "b", ], run = 'plugin toggle-pane min-parent', desc = "toggle back (parent)" },
  { on = [ "T", "p", ], run = 'plugin toggle-pane min-preview', desc = "toggle preview" },
  { on = [ "T", "P", ], run = 'plugin toggle-pane max-preview', desc = "max preview" },
  { on = [ "T", "t", ], run = 'plugin toggle-pane max-current', desc = "toggle zen" },
  { on = "C", run = "plugin ouch", desc = "Compress" },
  { on = [ "M", "m" ], run = 'plugin mount', desc = "mount Device" },
  { on = [ "M", "p" ], run = 'plugin simple-mtpfs -- select-then-mount --jump', desc = "mount Phone" },
  { on = [ "M", "r" ], run = "plugin simple-mtpfs -- remount-current-cwd-device", desc = "Remount Phone" },
  { on = [ "M", "u" ], run = "plugin simple-mtpfs -- select-then-unmount", desc = "Unmount phone" },

]
