"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 3, 4]
linemode = "size"
sort_by = "extension"
mouse_events = ["click", "scroll", "drag"]

[plugin]
prepend_previewers = [
  { mime = "application/{*zip,x-tar,x-bzip2,x-7z-compressed,x-rar,x-xz,xz}", run = "ouch" },
]

[which]
sort_by = "key"
